---
title: "Aldex2_Analysis_Revisions_Retro"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ALDEx2)
library(dplyr)
library(broom)
library(kableExtra)

```

# Load in data

```{r}

#Load in Metadata
Combined_data <- readRDS("~/Private/CHAPTER_4/Revised_data/Combined_data.RDS")
Combined_data_filt <- readRDS("~/Private/CHAPTER_4/Revised_data/Combined_data_filt.RDS")

#Load in ASVs
ASV_table <- read.table("~/Private/Previous_Cancer_Project/RERUN_REV1/deblur_output/asv_table/feature-table.tsv",
                        sep="\t", quote="", comment.char="", row.names=1, header=T, skip=1, check.names = F)
colnames(ASV_table)

#Load in Genus table
Genus_table <- read.table("~/Private/Previous_Cancer_Project/RERUN_REV1/taxa/level6/feature-table.tsv",
                          sep="\t", quote="", comment.char="", row.names=1, header=T, skip=1, check.names = F)

#divide data up into different types

Breast_data <- Combined_data %>% filter(Type == "Breast")
Prostate_data <- Combined_data %>% filter(Type == "Prostate")
CRC_data <- Combined_data %>% filter(Type == "Colon")

#divide out asv and genus tables
Breast_ASV <- ASV_table[,Breast_data$X]
Prostate_ASV <- ASV_table[,Prostate_data$X]
Colon_ASV <- ASV_table[,CRC_data$X]

Breast_Genus <- Genus_table[,Breast_data$X]
Prostate_Genus <- Genus_table[,Prostate_data$X]
Colon_Genus <- Genus_table[,CRC_data$X]


Breast_data_noNA <- Breast_data[complete.cases(Breast_data[,c("PM_WAIST_HIP_RATIO", "NUT_VEG_DAY_QTY")]),]
Prostate_data_noNA <- Prostate_data[complete.cases(Prostate_data[,c("PM_WAIST_HIP_RATIO", "NUT_VEG_DAY_QTY")]),]
CRC_data_noNA <- CRC_data[complete.cases(CRC_data[,c("PM_WAIST_HIP_RATIO", "NUT_VEG_DAY_QTY")]),]


Breast_ASV_noNA <- ASV_table[,Breast_data_noNA$X]
Prostate_ASV_noNA <- ASV_table[,Prostate_data_noNA$X]
Colon_ASV_noNA <- ASV_table[,CRC_data_noNA$X]

Breast_Genus_noNA <- Genus_table[,Breast_data_noNA$X]
Prostate_Genus_noNA <- Genus_table[,Prostate_data_noNA$X]
Colon_Genus_noNA <- Genus_table[,CRC_data_noNA$X]
```

# Breast Analysis

## ASVs

### unadjusted
```{r}
BC_model_matrix <- model.matrix(~ Extraction_Number + Case.Control, Breast_data)
BC_clr <- aldex.clr(Breast_ASV, BC_model_matrix, mc.samples = 128)
BC_glm <- aldex.glm(BC_clr, BC_model_matrix)

saveRDS(BC_glm, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/ASV_ALDEX2.RDS")
```

### age
```{r}
BC_model_matrix_age <- model.matrix(~ Extraction_Number + A_SDC_AGE_CALC + Case.Control, Breast_data)
BC_clr_age <- aldex.clr(Breast_ASV, BC_model_matrix_age, mc.samples = 128)
BC_glm_age <- aldex.glm(BC_clr_age, BC_model_matrix_age)

saveRDS(BC_glm_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/ASV_ALDEX2_age.RDS")
```

### age, WHR, height, vegs
```{r}
BC_model_matrix_all <- model.matrix(~ Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY + Case.Control, Breast_data_noNA)

BC_clr_all <- aldex.clr(Breast_ASV_noNA, BC_model_matrix_all, mc.samples = 128)
BC_glm_all <- aldex.glm(BC_clr_all, BC_model_matrix_all)

saveRDS(BC_glm_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/ASV_ALDEX2_all.RDS")
```


## Genus

### unadjusted
```{r}
BC_clr_genus <- aldex.clr(Breast_Genus, BC_model_matrix, mc.samples = 128)
BC_glm_genus <- aldex.glm(BC_clr_genus, BC_model_matrix)

saveRDS(BC_glm_genus, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/Genus_ALDEX2.RDS")
```

### age
```{r}
BC_clr_genus_age <- aldex.clr(Breast_Genus, BC_model_matrix_age, mc.samples = 128)
BC_glm_genus_age <- aldex.glm(BC_clr_genus_age, BC_model_matrix_age)

saveRDS(BC_glm_genus_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/Genus_ALDEX2_age.RDS")
```

### age height, WHR, vegs
```{r}
BC_clr_genus_all <- aldex.clr(Breast_Genus_noNA, BC_model_matrix_all, mc.samples = 128)
BC_glm_genus_all <- aldex.glm(BC_clr_genus_all, BC_model_matrix_all)

saveRDS(BC_glm_genus_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/Genus_ALDEX2_all.RDS")
```

# Prostate

## ASV
### unadjusted
```{r}
PR_model_matrix <- model.matrix(~ Extraction_Number + Case.Control, Prostate_data)
PR_clr <- aldex.clr(Prostate_ASV, PR_model_matrix, mc.samples = 128)
PR_glm <- aldex.glm(PR_clr, PR_model_matrix)

saveRDS(PR_glm, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/ASV_ALDEX2.RDS")
```

### age
```{r}
PR_model_matrix_age <- model.matrix(~ Extraction_Number + A_SDC_AGE_CALC + Case.Control, Prostate_data)
PR_clr_age <- aldex.clr(Prostate_ASV, PR_model_matrix_age, mc.samples = 128)
PR_glm_age <- aldex.glm(PR_clr_age, PR_model_matrix_age)

saveRDS(PR_glm_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/ASV_ALDEX2_age.RDS")
```

### all
```{r}
PR_model_matrix_all <- model.matrix(~ Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY + Case.Control, Prostate_data_noNA)

PR_clr_all <- aldex.clr(Prostate_ASV_noNA, PR_model_matrix_all, mc.samples = 128)
PR_glm_all <- aldex.glm(PR_clr_all, PR_model_matrix_all)

saveRDS(PR_glm_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/ASV_ALDEX2_all.RDS")
```

## Genus

### unadjusted
```{r}
PR_clr_genus <- aldex.clr(Prostate_Genus, PR_model_matrix, mc.samples=128)
PR_glm_genus <- aldex.glm(PR_clr_genus, PR_model_matrix)

saveRDS(PR_glm_genus, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/Genus_ALDEX2.RDS")
```

### age
```{r}
PR_clr_genus_age <- aldex.clr(Prostate_Genus, PR_model_matrix_age, mc.samples=128)
PR_glm_genus_age <- aldex.glm(PR_clr_genus_age, PR_model_matrix_age)

saveRDS(PR_glm_genus_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/Genus_ALDEX2_age.RDS")
```


### all
```{r}
PR_clr_genus_all <- aldex.clr(Prostate_Genus_noNA, PR_model_matrix_all, mc.samples=128)
PR_glm_genus_all <- aldex.glm(PR_clr_genus_all, PR_model_matrix_all)

saveRDS(PR_glm_genus_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/Genus_ALDEX2_all.RDS")
```


# CRC

## ASV

### unadjusted
```{r}
CRC_model_matrix <- model.matrix(~ Extraction_Number + Case.Control, CRC_data)
CRC_clr <- aldex.clr(Colon_ASV, CRC_model_matrix, mc.samples = 128)
CRC_glm <- aldex.glm(CRC_clr, CRC_model_matrix)

saveRDS(CRC_glm, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/ASV_ALDEX2.RDS")
```

### age
```{r}
CRC_model_matrix_age <- model.matrix(~ Extraction_Number + A_SDC_AGE_CALC + A_SDC_GENDER + Case.Control, CRC_data)
CRC_clr_age <- aldex.clr(Colon_ASV, CRC_model_matrix_age, mc.samples = 128)
CRC_glm_age <- aldex.glm(CRC_clr_age, CRC_model_matrix_age)

saveRDS(CRC_glm_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/ASV_ALDEX2_age.RDS")
```

### all
```{r}
CRC_model_matrix_all <- model.matrix(~ Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY + A_SDC_GENDER + Case.Control, CRC_data_noNA)

CRC_clr_all <- aldex.clr(Colon_ASV_noNA, CRC_model_matrix_all, mc.samples = 128)
CRC_glm_all <- aldex.glm(CRC_clr_all, CRC_model_matrix_all)

saveRDS(CRC_glm_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/ASV_ALDEX2_all.RDS")
```

## Genus

### unadjusted
```{r}
CRC_clr_genus <- aldex.clr(Colon_Genus, CRC_model_matrix, mc.samples = 128)
CRC_glm_genus <- aldex.glm(CRC_clr_genus, CRC_model_matrix)

saveRDS(CRC_glm_genus, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/Genus_ALDEX2.RDS")
```

### age
```{r}
CRC_clr_genus_age <- aldex.clr(Colon_Genus, CRC_model_matrix_age, mc.samples = 128)
CRC_glm_genus_age <- aldex.glm(CRC_clr_genus_age, CRC_model_matrix_age)

saveRDS(CRC_glm_genus_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/Genus_ALDEX2_age.RDS")
```

### all
```{r}
CRC_clr_genus_all <- aldex.clr(Colon_Genus_noNA, CRC_model_matrix_all, mc.samples = 128)
CRC_glm_genus_all <- aldex.glm(CRC_clr_genus_all, CRC_model_matrix_all)

saveRDS(CRC_glm_genus_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/Genus_ALDEX2_all.RDS")
```
