---
title: "Ancom_II_Revisions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(exactRankTests)
library(nlme)
library(dplyr)
library(ggplot2)
library(compositions)
library(kableExtra)
library(beeswarm)

source("~/GitHub_Repos/Clean_Hackathon/Pipeline_scripts/Ancom2_Script/ancom_v2.1.R")

```

# Load data

```{r}

#Load in Metadata
Combined_data <- readRDS("~/Private/CHAPTER_4/Revised_data/Combined_data.RDS")
Combined_data_filt <- readRDS("~/Private/CHAPTER_4/Revised_data/Combined_data_filt.RDS")

#Load in ASVs
ASV_table <- read.table("~/Private/Previous_Cancer_Project/RERUN_REV1/deblur_output/asv_table/feature-table.tsv",
                        sep="\t", quote="", comment.char="", row.names=1, header=T, skip=1, check.names = F)
colnames(ASV_table)

#Load in Genus table
Genus_table <- read.table("~/Private/Previous_Cancer_Project/RERUN_REV1/taxa/level6/feature-table.tsv",
                          sep="\t", quote="", comment.char="", row.names=1, header=T, skip=1, check.names = F)

#divide data up into different types

Breast_data <- Combined_data %>% filter(Type == "Breast")
Prostate_data <- Combined_data %>% filter(Type == "Prostate")
CRC_data <- Combined_data %>% filter(Type == "Colon")

#divide out asv and genus tables
Breast_ASV <- ASV_table[,Breast_data$X]
Prostate_ASV <- ASV_table[,Prostate_data$X]
Colon_ASV <- ASV_table[,CRC_data$X]

Breast_Genus <- Genus_table[,Breast_data$X]
Prostate_Genus <- Genus_table[,Prostate_data$X]
Colon_Genus <- Genus_table[,CRC_data$X]
```

# Breast Analysis

```{r}
identical(Breast_data$X, colnames(Breast_ASV))

prepro_breast_ASV <- feature_table_pre_process(feature_table = Breast_ASV, meta_data = Breast_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_breast_ASV <- ANCOM(feature_table = prepro_breast_ASV$feature_table,
                        meta_data = prepro_breast_ASV$meta_data,
                        struc_zero = prepro_breast_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_breast_ASV, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/ASV_ANCOM.RDS")


res_breast_ASV_age <- ANCOM(feature_table = prepro_breast_ASV$feature_table,
                        meta_data = prepro_breast_ASV$meta_data,
                        struc_zero = prepro_breast_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC',
                        rand_formula = NULL)

saveRDS(res_breast_ASV_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/ASV_ANCOM_age.RDS")


res_breast_ASV_all <- ANCOM(feature_table = prepro_breast_ASV$feature_table,
                        meta_data = prepro_breast_ASV$meta_data,
                        struc_zero = prepro_breast_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY',
                        rand_formula = NULL)

saveRDS(res_breast_ASV_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/ASV_ANCOM_all.RDS")
```

```{r}
identical(Breast_data$X, colnames(Breast_Genus))

prepro_breast_Genus <- feature_table_pre_process(feature_table = Breast_Genus, meta_data = Breast_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_breast_Genus <- ANCOM(feature_table = prepro_breast_Genus$feature_table,
                        meta_data = prepro_breast_Genus$meta_data,
                        struc_zero = prepro_breast_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_breast_Genus, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/Genus_ANCOM.RDS")

res_breast_Genus_age <- ANCOM(feature_table = prepro_breast_Genus$feature_table,
                        meta_data = prepro_breast_Genus$meta_data,
                        struc_zero = prepro_breast_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC',
                        rand_formula = NULL)

saveRDS(res_breast_Genus_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/Genus_ANCOM_age.RDS")


res_breast_Genus_all <- ANCOM(feature_table = prepro_breast_Genus$feature_table,
                        meta_data = prepro_breast_Genus$meta_data,
                        struc_zero = prepro_breast_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY',
                        rand_formula = NULL)

saveRDS(res_breast_Genus_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Breast/Genus_ANCOM_all.RDS")
```

# Prostate Analysis
```{r}
identical(Prostate_data$X, colnames(Prostate_ASV))

prepro_prostate_ASV <- feature_table_pre_process(feature_table = Prostate_ASV, meta_data = Prostate_data, sample_var='X',
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_prostate_ASV <- ANCOM(feature_table = prepro_prostate_ASV$feature_table,
                        meta_data = prepro_prostate_ASV$meta_data,
                        struc_zero = prepro_prostate_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_prostate_ASV, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/ASV_ANCOM.RDS")

res_prostate_ASV_age <- ANCOM(feature_table = prepro_prostate_ASV$feature_table,
                        meta_data = prepro_prostate_ASV$meta_data,
                        struc_zero = prepro_prostate_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC',
                        rand_formula = NULL)

saveRDS(res_prostate_ASV_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/ASV_ANCOM_age.RDS")

res_prostate_ASV_all <- ANCOM(feature_table = prepro_prostate_ASV$feature_table,
                        meta_data = prepro_prostate_ASV$meta_data,
                        struc_zero = prepro_prostate_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY',
                        rand_formula = NULL)

saveRDS(res_prostate_ASV_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/ASV_ANCOM_all.RDS")

```

```{r}
identical(Prostate_data$X, colnames(Prostate_Genus))


prepro_prostate_Genus <- feature_table_pre_process(feature_table = Prostate_Genus, meta_data = Prostate_data, sample_var='X',
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_prostate_Genus <- ANCOM(feature_table = prepro_prostate_Genus$feature_table,
                        meta_data = prepro_prostate_Genus$meta_data,
                        struc_zero = prepro_prostate_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_prostate_Genus, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/Genus_ANCOM.RDS")

res_prostate_Genus_age <- ANCOM(feature_table = prepro_prostate_Genus$feature_table,
                        meta_data = prepro_prostate_Genus$meta_data,
                        struc_zero = prepro_prostate_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC',
                        rand_formula = NULL)

saveRDS(res_prostate_Genus_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/Genus_ANCOM_age.RDS")

res_prostate_Genus_all <- ANCOM(feature_table = prepro_prostate_Genus$feature_table,
                        meta_data = prepro_prostate_Genus$meta_data,
                        struc_zero = prepro_prostate_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY',
                        rand_formula = NULL)

saveRDS(res_prostate_Genus_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/Prostate/Genus_ANCOM_all.RDS")
```

# CRC Analysis
```{r}
identical(CRC_data$X, colnames(Colon_ASV))

prepro_CRC_ASV <- feature_table_pre_process(feature_table = Colon_ASV, meta_data = CRC_data, sample_var='X',
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_CRC_ASV <- ANCOM(feature_table = prepro_CRC_ASV$feature_table,
                        meta_data = prepro_CRC_ASV$meta_data,
                        struc_zero = prepro_CRC_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_CRC_ASV, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/ASV_ANCOM.RDS")

res_CRC_ASV_age <- ANCOM(feature_table = prepro_CRC_ASV$feature_table,
                        meta_data = prepro_CRC_ASV$meta_data,
                        struc_zero = prepro_CRC_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + A_SDC_GENDER',
                        rand_formula = NULL)

saveRDS(res_CRC_ASV_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/ASV_ANCOM_age.RDS")


res_CRC_ASV_all <- ANCOM(feature_table = prepro_CRC_ASV$feature_table,
                        meta_data = prepro_CRC_ASV$meta_data,
                        struc_zero = prepro_CRC_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY + A_SDC_GENDER',
                        rand_formula = NULL)

saveRDS(res_CRC_ASV_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/ASV_ANCOM_all.RDS")
```

```{r}
identical(CRC_data$X, colnames(Colon_Genus))

prepro_CRC_Genus <- feature_table_pre_process(feature_table = Colon_Genus, meta_data = CRC_data, sample_var='X',
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_CRC_Genus <- ANCOM(feature_table = prepro_CRC_Genus$feature_table,
                        meta_data = prepro_CRC_Genus$meta_data,
                        struc_zero = prepro_CRC_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_CRC_Genus, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/Genus_ANCOM.RDS")


res_CRC_Genus_age <- ANCOM(feature_table = prepro_CRC_Genus$feature_table,
                        meta_data = prepro_CRC_Genus$meta_data,
                        struc_zero = prepro_CRC_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + A_SDC_GENDER',
                        rand_formula = NULL)

saveRDS(res_CRC_Genus_age, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/Genus_ANCOM_age.RDS")


res_CRC_Genus_all <- ANCOM(feature_table = prepro_CRC_Genus$feature_table,
                        meta_data = prepro_CRC_Genus$meta_data,
                        struc_zero = prepro_CRC_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number + A_SDC_AGE_CALC + PM_WAIST_HIP_RATIO + PM_STANDING_HEIGHT_AVG + NUT_VEG_DAY_QTY + A_SDC_GENDER',
                        rand_formula = NULL)

saveRDS(res_CRC_Genus_all, "~/Private/CHAPTER_4/Revised_data/DA/PATH_Retro/CRC/Genus_ANCOM_all.RDS")
```
