---
title: "ANCOM Prospec. PATH"
author: "Jacob T. Nearing"
date: "2/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(broom)
source("~/GitHub_Repos/Clean_Hackathon/Pipeline_scripts/Ancom2_Script/ancom_v2.1.R")

remove_rare_features <- function( table , cutoff_pro=0.1, parallel=1 ) {
  if(cutoff_pro<=0){
    message("No filtering will be done due to cutoff_pro set to 0 or below")
    return(table)
  }
  row2keep <- c()
  cutoff <- ceiling( cutoff_pro * ncol(table) )
  if(parallel <= 1){
    for ( i in 1:nrow(table) ) {
      row_nonzero <- length( which( table[ i , ]  > 0 ) )
      if ( row_nonzero > cutoff ) {
        row2keep <- c( row2keep , i)
      }
    }
    return( table [ row2keep , , drop=F ])
  }else{
    `%dopar%` <- foreach::`%dopar%`
    cl <- parallel::makeCluster(parallel)
    doParallel::registerDoParallel(cl)
    message("Running with: ", foreach::getDoParWorkers(), " cores")

    res <- foreach::foreach(i = 1:nrow(table), .combine = c) %dopar% {
      row_nonzero <- length( which ( table[ i , ] > 0))
      if(row_nonzero > cutoff){
        i
      }else
        NULL
    }
    parallel::stopCluster(cl)
    return( table[res, , drop=F])

  }

}


remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(((is.na(df[i,'age_diff']) | df[i,'age_diff'] < 0)) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}
```

```{r}
Metadata_Breast <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_Breast.RDS")
Metadata_Breast$Case_Control <- as.character(Metadata_Breast$`Case/Control`)
Metadata_Prostate <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_Prostate.RDS")
Metadata_Prostate$Case_Control <- as.character(Metadata_Prostate$`Case/Control`)
Metadata_CRC <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_CRC.RDS")
Metadata_CRC$Case_Control <- as.character(Metadata_CRC$`Case/Control`)

Metadata_Breast$Case.Control <- ifelse(Metadata_Breast$`CASE/CONTROL`==1, "Case", "Control")
Metadata_Prostate$Case.Control <- ifelse(Metadata_Prostate$`CASE/CONTROL`==1, "Case", "Control")
Metadata_CRC$Case.Control <- ifelse(Metadata_CRC$`CASE/CONTROL`==1, "Case", "Control")

Metadata_Breast$Case.Control <- factor(Metadata_Breast$Case.Control, levels=c("Control", "Case"))
Metadata_Prostate$Case.Control <- factor(Metadata_Prostate$Case.Control, levels=c("Control", "Case"))
Metadata_CRC$Case.Control <- factor(Metadata_CRC$Case.Control, levels=c("Control", "Case"))

Faiths <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/faiths/alpha-diversity.tsv",
                     header=T, row.names=1)
Evenness <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/evenness/alpha-diversity.tsv",
                        header=T, row.names = 1)

Richness <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/richness/alpha-diversity.tsv", 
                       header=T, row.names = 1)

Shannon <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/shannon/alpha-diversity.tsv",
                      header=T, row.names = 1)

Alpha_data <- cbind(Faiths, Evenness, Richness, Shannon)

Alpha_data$`Saliva ID Ship` <- rownames(Alpha_data)

Alpha_Breast <- Alpha_data %>% inner_join(Metadata_Breast, by="Saliva ID Ship")
Alpha_Prostate <- Alpha_data %>% inner_join(Metadata_Prostate, by="Saliva ID Ship")
Alpha_CRC  <- Alpha_data %>% inner_join(Metadata_CRC, by="Saliva ID Ship")

Alpha_Breast$X <- Alpha_Breast$`Saliva ID Ship`
Alpha_Prostate$X <- Alpha_Prostate$`Saliva ID Ship`
Alpha_CRC$X <- Alpha_CRC$`Saliva ID Ship`

Alpha_Breast$age_diff <- Alpha_Breast$F1_DIS_CANCER1_AGE - Alpha_Breast$SDC_AGE_CALC
Alpha_Prostate$age_diff <- Alpha_Prostate$F1_DIS_CANCER1_AGE - Alpha_Prostate$SDC_AGE_CALC
Alpha_CRC$age_diff <- Alpha_CRC$F1_DIS_CANCER1_AGE - Alpha_CRC$SDC_AGE_CALC

Alpha_Breast$Type <- "Breast"
Alpha_Prostate$Type <- "Prostate"
Alpha_CRC$Type <- "Colon"

Alpha_Breast <- remove_non_matching_caseIDS(Alpha_Breast)
Alpha_Prostate <- remove_non_matching_caseIDS(Alpha_Prostate)
Alpha_CRC <- remove_non_matching_caseIDS(Alpha_CRC)

Breast_data_comb <- Alpha_Breast %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

Prostate_data_comb <- Alpha_Prostate %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

CRC_data_comb <- Alpha_CRC %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)


Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)

Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r}


Genera <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/Taxa/genus_table/feature-table.tsv", sep="\t", header=T, row.names=1, skip=1, comment.char="",
                     check.names=F)

ASV <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/deblur_output/raw_table/feature-table.tsv", sep="\t", header=T, row.names=1, skip=1, comment.char="", check.names = F)


Breast_Genera <- Genera[,Breast_data$X]
Breast_ASV <- ASV[,Breast_data$X]


Prostate_Genera <- Genera[,Prostate_data$X]
Prostate_ASV <- ASV[,Prostate_data$X]


CRC_Genera <- Genera[,CRC_data$X]
CRC_ASV <- ASV[,CRC_data$X]
```

# Breast Cancer
```{r}
identical(colnames(Breast_ASV), Breast_data$X)
identical(colnames(Breast_Genera), Breast_data$X)
```
## ASV
```{r}
prepro_breast_ASV <- feature_table_pre_process(feature_table = Breast_ASV, meta_data = Breast_data, sample_var="X",
                                               group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.9,
                                               lib_cut = 1000, neg_lb = FALSE)

res_breast_ASV <- ANCOM(feature_table = prepro_breast_ASV$feature_table, 
                        meta_data = prepro_breast_ASV$meta_data,
                        struc_zero = prepro_breast_ASV$structure_zeros, 
                        main_var = "Case.Control", 
                        p_adj_method = "BH",
                        alpha = 0.05, adj_formula = NULL, rand_formula = NULL) 

saveRDS(res_breast_ASV$out, "~/Private/CHAPTER_4/Prospec/PATH/Data/Breast/ASV_ANCOM.RDS")
```

## Genera
```{r}
prepro_breast_genera <- feature_table_pre_process(feature_table = Breast_Genera, meta_data = Breast_data, sample_var="X",
                                               group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.9,
                                               lib_cut = 1000, neg_lb = FALSE)

res_breast_genera <- ANCOM(feature_table = prepro_breast_genera$feature_table, 
                        meta_data = prepro_breast_genera$meta_data,
                        struc_zero = prepro_breast_genera$structure_zeros, 
                        main_var = "Case.Control", 
                        p_adj_method = "BH",
                        alpha = 0.05, adj_formula = NULL, rand_formula = NULL) 

saveRDS(res_breast_genera$out, "~/Private/CHAPTER_4/Prospec/PATH/Data/Breast/Genera_ANCOM.RDS")
```

# Prostate Cancer
```{r}
identical(colnames(Prostate_ASV), Prostate_data$X)
identical(colnames(Prostate_Genera), Prostate_data$X)
```

## ASV
```{r}
prepro_prostate_asv <- feature_table_pre_process(feature_table = Prostate_ASV, meta_data = Prostate_data, sample_var = "X",
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.9,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_prostate_asv <- ANCOM(feature_table = prepro_prostate_asv$feature_table, 
                        meta_data = prepro_prostate_asv$meta_data,
                        struc_zero = prepro_prostate_asv$structure_zeros, 
                        main_var = "Case.Control", 
                        p_adj_method = "BH",
                        alpha = 0.05, adj_formula = NULL, rand_formula = NULL)

saveRDS(res_prostate_asv$out, "~/Private/CHAPTER_4/Prospec/PATH/Data/Prostate/ASV_ANCOM.RDS")
```

## Genera
```{r}
prepro_prostate_genera <- feature_table_pre_process(feature_table = Prostate_Genera, meta_data = Prostate_data, sample_var = "X",
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.9,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_prostate_genera <- ANCOM(feature_table = prepro_prostate_genera$feature_table, 
                        meta_data = prepro_prostate_genera$meta_data,
                        struc_zero = prepro_prostate_genera$structure_zeros, 
                        main_var = "Case.Control", 
                        p_adj_method = "BH",
                        alpha = 0.05, adj_formula = NULL, rand_formula = NULL)

saveRDS(res_prostate_genera$out, "~/Private/CHAPTER_4/Prospec/PATH/Data/Prostate/Genera_ANCOM.RDS")
```

# Colon Cancer

## ASV
```{r}
prepro_colon_asv <- feature_table_pre_process(feature_table = CRC_ASV, meta_data = CRC_data, sample_var = "X",
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.9,
                                                 lib_cut = 1000, neg_lb = FALSE)



res_colon_asv <- ANCOM(feature_table = prepro_colon_asv$feature_table, 
                        meta_data = prepro_colon_asv$meta_data,
                        struc_zero = prepro_colon_asv$structure_zeros, 
                        main_var = "Case.Control", 
                        p_adj_method = "BH",
                        alpha = 0.05, adj_formula = NULL, rand_formula = NULL)

saveRDS(res_colon_asv$out, "~/Private/CHAPTER_4/Prospec/PATH/Data/Colon/ASV_ANCOM.RDS")

```

## Genera
```{r}
prepro_colon_genera <- feature_table_pre_process(feature_table = CRC_Genera, meta_data = CRC_data, sample_var = "X",
                                                 group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.9,
                                                 lib_cut = 1000, neg_lb = FALSE)

res_colon_genera <- ANCOM(feature_table = prepro_colon_genera$feature_table, 
                        meta_data = prepro_colon_genera$meta_data,
                        struc_zero = prepro_colon_genera$structure_zeros, 
                        main_var = "Case.Control", 
                        p_adj_method = "BH",
                        alpha = 0.05, adj_formula = NULL, rand_formula = NULL)


saveRDS(res_colon_genera, "~/Private/CHAPTER_4/Prospec/PATH/Data/Colon/Genera_ANCOM.RDS")
```