---
title: "CRC_RF_LOOCV_ret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(randomForest)
library(caret)
library(dplyr)
library(readxl)

library(ROCR)
library(cvAUC)

library(rfUtilities)

library(doParallel)
cl <- makePSOCKcluster(40)
registerDoParallel(cl)

remove_rare_features <- function( table , cutoff_pro=0.1, parallel=1 ) {
  if(cutoff_pro<=0){
    message("No filtering will be done due to cutoff_pro set to 0 or below")
    return(table)
  }
  row2keep <- c()
  cutoff <- ceiling( cutoff_pro * ncol(table) )
  if(parallel <= 1){
    for ( i in 1:nrow(table) ) {
      row_nonzero <- length( which( table[ i , ]  > 0 ) )
      if ( row_nonzero > cutoff ) {
        row2keep <- c( row2keep , i)
      }
    }
    return( table [ row2keep , , drop=F ])
  }else{
    `%dopar%` <- foreach::`%dopar%`
    cl <- parallel::makeCluster(parallel)
    doParallel::registerDoParallel(cl)
    message("Running with: ", foreach::getDoParWorkers(), " cores")

    res <- foreach::foreach(i = 1:nrow(table), .combine = c) %dopar% {
      row_nonzero <- length( which ( table[ i , ] > 0))
      if(row_nonzero > cutoff){
        i
      }else
        NULL
    }
    parallel::stopCluster(cl)
    return( table[res, , drop=F])

  }

}

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}



```


```{r load_metadata}

Metadata_Breast <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Breast_21_03_11.csv", row.names = 1)
Metadata_CRC <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_CRC_21_03_11.csv", row.names = 1)
Metadata_Prostate <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Prostate_21_03_11.csv", row.names = 1)


### Load in alpha data

Alpha_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_Breast.RDS")
Alpha_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_CRC.RDS")
Alpha_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_prostate.RDS")


Metadata_Breast <- Metadata_Breast[rownames(Alpha_Breast),]
Metadata_CRC <- Metadata_CRC[rownames(Alpha_CRC),]
Metadata_Prostate <- Metadata_Prostate[rownames(Alpha_Prostate),]

Metadata_Breast_Cases <- Metadata_Breast[which(Metadata_Breast$Case.Control==1),]
Metadata_CRC_Cases <- Metadata_CRC[which(Metadata_CRC$Case.Control==1),]
Metadata_Prostate_Cases <- Metadata_Prostate[which(Metadata_Prostate$Case.Control==1),]

Alpha_Breast_Cases <- Alpha_Breast[rownames(Metadata_Breast_Cases),]
Alpha_CRC_Cases <- Alpha_CRC[rownames(Metadata_CRC_Cases),]
Alpha_Prostate_Cases <- Alpha_Prostate[rownames(Metadata_Prostate_Cases),]

Alpha_Breast$X <- rownames(Alpha_Breast)
Breast_data <- Alpha_Breast %>% left_join(Metadata_Breast, by="X")
Breast_data$Case.Control <- ifelse(Breast_data$Case.Control==1, "Case", "Control")

Alpha_Prostate$X <- rownames(Alpha_Prostate)
Prostate_data <- Alpha_Prostate %>% left_join(Metadata_Prostate, by="X")
Prostate_data$Case.Control <- ifelse(Prostate_data$Case.Control==1, "Case", "Control")

Alpha_CRC$X <- rownames(Alpha_CRC)
CRC_data <- Alpha_CRC %>% left_join(Metadata_CRC, by="X")
CRC_data$Case.Control <- ifelse(CRC_data$Case.Control==1, "Case", "Control")

Alpha_Breast_Cases$X <- rownames(Alpha_Breast_Cases)
Breast_case_data <- Alpha_Breast_Cases %>% left_join(Metadata_Breast_Cases, by="X")
Breast_case_data$Case.Control <- ifelse(Breast_case_data$Case.Control==1, "Case", "Control")

Alpha_Prostate_Cases$X <- rownames(Alpha_Prostate_Cases)
Prostate_case_data <- Alpha_Prostate_Cases %>% left_join(Metadata_Prostate_Cases, by="X")
Prostate_case_data$Case.Control <- ifelse(Prostate_case_data$Case.Control==1, "Case", "Control")

Alpha_CRC_Cases$X <- rownames(Alpha_CRC_Cases)
CRC_case_data <- Alpha_CRC_Cases %>% left_join(Metadata_CRC_Cases, by="X")
CRC_case_data$Case.Control <- ifelse(CRC_case_data$Case.Control==1, "Case", "Control")


Breast_data$age_diff <- Breast_data$YEARS_SINCE_BC
Prostate_data$age_diff <- Prostate_data$YEARS_SINCE_PC
CRC_data$age_diff <- CRC_data$YEARS_SINCE_CRC_CANCER

Breast_data$Type <- "Breast"
Prostate_data$Type <- "Prostate"
CRC_data$Type <- "Colon"

Breast_data$Case.Control <- factor(Breast_data$Case.Control, levels=c("Control", "Case"))
Prostate_data$Case.Control <- factor(Prostate_data$Case.Control, levels=c("Control", "Case"))
CRC_data$Case.Control <- factor(CRC_data$Case.Control, levels=c("Control","Case"))

Breast_data <- remove_non_matching_caseIDS(Breast_data)
Prostate_data <- remove_non_matching_caseIDS(Prostate_data)
CRC_data <- remove_non_matching_caseIDS(CRC_data)

Breast_data_comb <- Breast_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)
Prostate_data_comb <- Prostate_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)
CRC_data_comb <- CRC_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)


Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)

Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r load_feature_data}

ASV_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_breast.RDS")
ASV_Breast <- ASV_Breast[-which(rowSums(ASV_Breast)==0),]

ASV_Breast <- ASV_Breast[,Breast_data$X]


ASV_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_CRC.RDS")
ASV_CRC <- ASV_CRC[-which(rowSums(ASV_CRC)==0),]
ASV_CRC <- ASV_CRC[,CRC_data$X]


ASV_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_Prostate.RDS")
ASV_Prostate <- ASV_Prostate[-which(rowSums(ASV_Prostate)==0),]
ASV_Prostate <- ASV_Prostate[,Prostate_data$X]





## load in Genus
Genus_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_breast.RDS")
Genus_Breast <- Genus_Breast[-which(rowSums(Genus_Breast)==0),]
Genus_Breast <- Genus_Breast[,Breast_data$X]


Genus_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_CRC.RDS")
Genus_CRC <- Genus_CRC[-which(rowSums(Genus_CRC)==0),]
Genus_CRC <- Genus_CRC[,CRC_data$X]

Genus_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_prostate.RDS")
Genus_Prostate <- Genus_Prostate[-which(rowSums(Genus_Prostate)==0),]
Genus_Prostate <- Genus_Prostate[,Prostate_data$X]



```


```{r}
ASV_Breast_CLR <- data.frame(apply(ASV_Breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_CRC_CLR <- data.frame(apply(ASV_CRC + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_Prostate_CLR <- data.frame(apply(ASV_Prostate + 1, 2, function(x){log(x) - mean (log(x))}), check.names = F)

ASV_Breast_CLR_flip <- data.frame(t(ASV_Breast_CLR), check.names = F)
ASV_Breast_CLR_flip$X <- rownames(ASV_Breast_CLR_flip)

ASV_CRC_CLR_flip <- data.frame(t(ASV_CRC_CLR), check.names = F)
ASV_CRC_CLR_flip$X <- rownames(ASV_CRC_CLR_flip)

ASV_Prostate_CLR_flip <- data.frame(t(ASV_Prostate_CLR), check.names = F)
ASV_Prostate_CLR_flip$X <- rownames(ASV_Prostate_CLR_flip)

Genus_Breast_CLR <- data.frame(apply(Genus_Breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_CRC_CLR <- data.frame(apply(Genus_CRC + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_Prostate_CLR <- data.frame(apply(Genus_Prostate + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)

Genus_Breast_CLR_flip <- data.frame(t(Genus_Breast_CLR), check.names = F)
Genus_Breast_CLR_flip$X <- rownames(Genus_Breast_CLR_flip)

Genus_CRC_CLR_flip <- data.frame(t(Genus_CRC_CLR), check.names = F)
Genus_CRC_CLR_flip$X <- rownames(Genus_CRC_CLR_flip)

Genus_Prostate_CLR_flip <- data.frame(t(Genus_Prostate_CLR), check.names = F)
Genus_Prostate_CLR_flip$X <- rownames(Genus_Prostate_CLR_flip)


ASV_Breast_RA <- sweep(ASV_Breast, 2, colSums(ASV_Breast), '/')
ASV_CRC_RA <- sweep(ASV_CRC, 2, colSums(ASV_CRC), '/')
ASV_Prostate_RA <- sweep(ASV_Prostate, 2, colSums(ASV_Prostate), '/')

ASV_Breast_RA_flip <- data.frame(t(ASV_Breast_RA), check.names=F)
ASV_Breast_RA_flip$X <- rownames(ASV_Breast_RA_flip)

ASV_CRC_RA_flip <- data.frame(t(ASV_CRC_RA), check.names = F)
ASV_CRC_RA_flip$X <- rownames(ASV_CRC_RA_flip)

ASV_Prostate_RA_flip <- data.frame(t(ASV_Prostate_RA), check.names = F)
ASV_Prostate_RA_flip$X <- rownames(ASV_Prostate_RA_flip)

Genus_Breast_RA <- sweep(Genus_Breast, 2, colSums(Genus_Breast), '/')
Genus_CRC_RA <- sweep(Genus_CRC, 2, colSums(Genus_CRC), '/')
Genus_Prostate_RA <- sweep(Genus_Prostate, 2, colSums(Genus_Prostate), '/')

Genus_Breast_RA_flip <- data.frame(t(Genus_Breast_RA), check.names = F)
Genus_Breast_RA_flip$X <- rownames(Genus_Breast_RA_flip)

Genus_CRC_RA_flip <- data.frame(t(Genus_CRC_RA), check.names = F)
Genus_CRC_RA_flip$X <- rownames(Genus_CRC_RA_flip)

Genus_Prostate_RA_flip <- data.frame(t(Genus_Prostate_RA), check.names = F)
Genus_Prostate_RA_flip$X <- rownames(Genus_Prostate_RA_flip)
```

```{r}
ASV_Breast_RA_filt <- remove_rare_features(table = ASV_Breast_RA, cutoff_pro = 0.05)
ASV_Prostate_RA_filt <- remove_rare_features(table=ASV_Prostate_RA, cutoff_pro = 0.05)
ASV_CRC_RA_filt <- remove_rare_features(table=ASV_CRC_RA, cutoff_pro = 0.05)

ASV_Breast_RA_filt_flip <- data.frame(t(ASV_Breast_RA_filt), check.names = F)
ASV_Prostate_RA_filt_flip <- data.frame(t(ASV_Prostate_RA_filt), check.names = F)
ASV_CRC_RA_filt_flip <- data.frame(t(ASV_CRC_RA_filt), check.names = F)




Genus_Breast_RA_filt <- remove_rare_features(table=Genus_Breast_RA, cutoff_pro = 0.05)
Genus_Prostate_RA_filt <- remove_rare_features(table=Genus_Prostate_RA, cutoff_pro = 0.05)
Genus_CRC_RA_filt <- remove_rare_features(table=Genus_CRC_RA, cutoff_pro = 0.05)

Genus_Breast_RA_filt_flip <- data.frame(t(Genus_Breast_RA_filt), check.names = F)
Genus_Prostate_RA_filt_flip <- data.frame(t(Genus_Prostate_RA_filt), check.names = F)
Genus_CRC_RA_filt_flip <- data.frame(t(Genus_CRC_RA_filt), check.names = F)


ASV_Breast_CLR_filt_flip <- ASV_Breast_CLR_flip[,colnames(ASV_Breast_RA_filt_flip)]
ASV_Prostate_CLR_filt_flip <- ASV_Prostate_CLR_flip[,colnames(ASV_Prostate_RA_filt_flip)]
ASV_CRC_CLR_filt_flip <- ASV_CRC_CLR_flip[,colnames(ASV_CRC_RA_filt_flip)]

Genus_Breast_CLR_filt_flip <- Genus_Breast_CLR_flip[,colnames(Genus_Breast_RA_filt_flip)]
Genus_Prostate_CLR_filt_flip <- Genus_Prostate_CLR_flip[,colnames(Genus_Prostate_RA_filt_flip)]
Genus_CRC_CLR_filt_flip <- Genus_CRC_CLR_flip[,colnames(Genus_CRC_RA_filt_flip)]


fit_control_down_rcv <- trainControl(method="repeatedcv", savePredictions = T, summaryFunction = twoClassSummary, classProbs = T, sampling = "down", repeats = 100, number = 5)
```

# CRC

## ASV RA
```{r}
set.seed(10)

ASV_RCV_down <- train(ASV_CRC_RA_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001, 
                      tuneGrid = data.frame(mtry=21), trControl = fit_control_down_rcv, importance=T)

ASV_RCV_down
saveRDS(ASV_RCV_down, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/ASV_RCV_down_caret.RDS")
```

## ASV CLR
```{r}
set.seed(10)

ASV_CLR_RCV_down <- train(ASV_CRC_CLR_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001, 
                      tuneGrid = data.frame(mtry=21), trControl = fit_control_down_rcv, importance=T)
ASV_CLR_RCV_down
saveRDS(ASV_CLR_RCV_down, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/ASV_CLR_RCV_down_caret.RDS")
```

## Genus RA
```{r}
set.seed(10)

Genus_RA_RCV_down <- train(Genus_CRC_RA_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                           tuneGrid = data.frame(mtry=12), trControl = fit_control_down_rcv, importance=T)

Genus_RA_RCV_down

saveRDS(Genus_RA_RCV_down, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/Genus_RA_RCV_down_caret.RDS")
```

## Genus CLR
```{r}
set.seed(10)

Genus_CLR_RCV_down <- train(Genus_CRC_CLR_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                            tuneGrid = data.frame(mtry=12), trControl = fit_control_down_rcv, importance=T)
Genus_CLR_RCV_down

saveRDS(Genus_CLR_RCV_down, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/Genus_CLR_RCV_down_caret.RDS")
```

# Breast

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_Breast_RA_filt_flip), Breast_data$X))
set.seed(10)

ASV_RCV_down_Breast <- train(ASV_Breast_RA_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001, 
                      tuneGrid = data.frame(mtry=21), trControl = fit_control_down_rcv, importance=T)
ASV_RCV_down_Breast
saveRDS(ASV_RCV_down_Breast, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/ASV_RA_RCV_down_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_Breast_CLR_filt_flip), Breast_data$X))
set.seed(10)

ASV_CLR_RCV_down_Breast <- train(ASV_Breast_CLR_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                                 tuneGrid = data.frame(mtry=21), trControl = fit_control_down_rcv, importance=T)

ASV_CLR_RCV_down_Breast
saveRDS(ASV_CLR_RCV_down_Breast, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/ASV_CLR_RCV_down_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_Breast_RA_filt_flip), Breast_data$X))

set.seed(10)

Genus_RA_RCV_down_Breast <- train(Genus_Breast_RA_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                                  tuneGrid = data.frame(mtry=12), trControl = fit_control_down_rcv, importance=T)
Genus_RA_RCV_down_Breast
saveRDS(Genus_RA_RCV_down_Breast, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/Genus_RA_RCV_down_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_Breast_CLR_filt_flip), Breast_data$X))

set.seed(10)

Genus_CLR_RCV_down_Breast <- train(Genus_Breast_CLR_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                                   tuneGrid = data.frame(mtry=12), trControl = fit_control_down_rcv, importance=T)
Genus_CLR_RCV_down_Breast
saveRDS(Genus_CLR_RCV_down_Breast, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/Genus_CLR_RCV_down_caret.RDS")
```
# Prostate

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_Prostate_RA_filt_flip), Prostate_data$X))

set.seed(10)

ASV_RCV_down_Prostate <- train(ASV_Prostate_RA_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                               tuneGrid = data.frame(mtry=22), trControl = fit_control_down_rcv, importance=T)

ASV_RCV_down_Prostate

saveRDS(ASV_RCV_down_Prostate, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/ASV_RA_RCV_down_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_Prostate_CLR_filt_flip), Prostate_data$X))

set.seed(10)

ASV_RCV_down_Prostate_CLR <- train(ASV_Prostate_CLR_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                                   tuneGrid = data.frame(mtry=22), trControl = fit_control_down_rcv, importance=T)

ASV_RCV_down_Prostate_CLR

saveRDS(ASV_RCV_down_Prostate_CLR, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/ASV_CLR_RCV_down_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_Prostate_RA_filt_flip), Prostate_data$X))

set.seed(10)

Genus_RCV_down_Prostate <- train(Genus_Prostate_RA_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                                 tuneGrid = data.frame(mtry=11), trControl = fit_control_down_rcv, importance=T)


Genus_RCV_down_Prostate

saveRDS(Genus_RCV_down_Prostate, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/Genus_RA_RCV_down_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_Prostate_CLR_filt_flip), Prostate_data$X))

set.seed(10)

Genus_RCV_down_Prostate_CLR <- train(Genus_Prostate_CLR_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                                     tuneGrid = data.frame(mtry=11), trControl = fit_control_down_rcv, importance=T)


Genus_RCV_down_Prostate_CLR

saveRDS(Genus_RCV_down_Prostate_CLR, "~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/Genus_CLR_RCV_down_caret.RDS")
```