---
title: "Reterospective_metadata_Table"
author: "Jacob T. Nearing"
date: "6/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readxl)

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}
```

```{r}

Metadata_Breast <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Breast_21_03_11.csv", row.names = 1)
Metadata_CRC <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_CRC_21_03_11.csv", row.names = 1)
Metadata_Prostate <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Prostate_21_03_11.csv", row.names = 1)


### Load in alpha data

Alpha_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_Breast.RDS")
Alpha_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_CRC.RDS")
Alpha_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_prostate.RDS")

#filter to only keep those that passed sequencing QC
Metadata_Breast <- Metadata_Breast[rownames(Alpha_Breast),]
Metadata_CRC <- Metadata_CRC[rownames(Alpha_CRC),]
Metadata_Prostate <- Metadata_Prostate[rownames(Alpha_Prostate),]

Metadata_Breast_Cases <- Metadata_Breast[which(Metadata_Breast$Case.Control==1),]
Metadata_CRC_Cases <- Metadata_CRC[which(Metadata_CRC$Case.Control==1),]
Metadata_Prostate_Cases <- Metadata_Prostate[which(Metadata_Prostate$Case.Control==1),]

Alpha_Breast_Cases <- Alpha_Breast[rownames(Metadata_Breast_Cases),]
Alpha_CRC_Cases <- Alpha_CRC[rownames(Metadata_CRC_Cases),]
Alpha_Prostate_Cases <- Alpha_Prostate[rownames(Metadata_Prostate_Cases),]

Alpha_Breast$X <- rownames(Alpha_Breast)
Breast_data <- Alpha_Breast %>% left_join(Metadata_Breast, by="X")
Breast_data$Case.Control <- ifelse(Breast_data$Case.Control==1, "Case", "Control")

Alpha_Prostate$X <- rownames(Alpha_Prostate)
Prostate_data <- Alpha_Prostate %>% left_join(Metadata_Prostate, by="X")
Prostate_data$Case.Control <- ifelse(Prostate_data$Case.Control==1, "Case", "Control")

Alpha_CRC$X <- rownames(Alpha_CRC)
CRC_data <- Alpha_CRC %>% left_join(Metadata_CRC, by="X")
CRC_data$Case.Control <- ifelse(CRC_data$Case.Control==1, "Case", "Control")

Alpha_Breast_Cases$X <- rownames(Alpha_Breast_Cases)
Breast_case_data <- Alpha_Breast_Cases %>% left_join(Metadata_Breast_Cases, by="X")
Breast_case_data$Case.Control <- ifelse(Breast_case_data$Case.Control==1, "Case", "Control")

Alpha_Prostate_Cases$X <- rownames(Alpha_Prostate_Cases)
Prostate_case_data <- Alpha_Prostate_Cases %>% left_join(Metadata_Prostate_Cases, by="X")
Prostate_case_data$Case.Control <- ifelse(Prostate_case_data$Case.Control==1, "Case", "Control")

Alpha_CRC_Cases$X <- rownames(Alpha_CRC_Cases)
CRC_case_data <- Alpha_CRC_Cases %>% left_join(Metadata_CRC_Cases, by="X")
CRC_case_data$Case.Control <- ifelse(CRC_case_data$Case.Control==1, "Case", "Control")


Breast_data$age_diff <- Breast_data$YEARS_SINCE_BC
Prostate_data$age_diff <- Prostate_data$YEARS_SINCE_PC
CRC_data$age_diff <- CRC_data$YEARS_SINCE_CRC_CANCER

Breast_data$Type <- "Breast"
Prostate_data$Type <- "Prostate"
CRC_data$Type <- "Colon"

Breast_data$Case.Control <- factor(Breast_data$Case.Control, levels=c("Control", "Case"))
Prostate_data$Case.Control <- factor(Prostate_data$Case.Control, levels=c("Control", "Case"))
CRC_data$Case.Control <- factor(CRC_data$Case.Control, levels=c("Control","Case"))

Breast_data <- remove_non_matching_caseIDS(Breast_data)
Prostate_data <- remove_non_matching_caseIDS(Prostate_data)
CRC_data <- remove_non_matching_caseIDS(CRC_data)


```

## Breast data stats

```{r}
table(Breast_data$Case.Control)

Breast_data %>% group_by(Case.Control) %>% summarize(mean(A_SDC_AGE_CALC))
Breast_data %>% group_by(Case.Control) %>% summarize(mean(PM_BIOIMPED_BMI))
Breast_data %>% group_by(Case.Control) %>% summarize(median(age_diff))

Breast_data %>% group_by(Case.Control) %>% summarize(sd(A_SDC_AGE_CALC))
Breast_data %>% group_by(Case.Control) %>% summarize(sd(PM_BIOIMPED_BMI))
```

## Prostate data stats

```{r}
table(Prostate_data$Case.Control)

Prostate_data %>% group_by(Case.Control) %>% summarize(mean(A_SDC_AGE_CALC))
Prostate_data %>% group_by(Case.Control) %>% summarize(mean(PM_BIOIMPED_BMI))
Prostate_data %>% group_by(Case.Control) %>% summarize(median(age_diff))

Prostate_data %>% group_by(Case.Control) %>% summarize(sd(A_SDC_AGE_CALC))
Prostate_data %>% group_by(Case.Control) %>% summarize(sd(PM_BIOIMPED_BMI))
```

## CRC data stats

```{r}
table(CRC_data$Case.Control)

CRC_data %>% group_by(Case.Control) %>% summarize(mean(A_SDC_AGE_CALC))
CRC_data %>% group_by(Case.Control) %>% summarize(mean(PM_BIOIMPED_BMI))
CRC_data %>% group_by(Case.Control) %>% summarize(median(age_diff))

CRC_data %>% group_by(Case.Control) %>% summarize(sd(A_SDC_AGE_CALC))
CRC_data %>% group_by(Case.Control) %>% summarize(sd(PM_BIOIMPED_BMI))
```

## Final Metadata

```{r}
#select metadata of interest from each df
Breast_data_filt <- Breast_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number, A_SDC_GENDER)

Prostate_data_filt <- Prostate_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number, A_SDC_GENDER)

CRC_data_filt <- CRC_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number, A_SDC_GENDER)


PATH_Ret_data <- rbind(Breast_data_filt, Prostate_data_filt)
PATH_Ret_data <- rbind(PATH_Ret_data, CRC_data_filt)

write.table(x=PATH_Ret_data, file="~/Private/CHAPTER_4/Cleaned_Repo_D1/Data/Reterospective/PATH_Ret_metadata.csv", col.names = NA, row.names = T, quote=F, sep=",")

```



```{r}
case_samples <- PATH_Ret_data %>% filter(Case.Control=="Case") %>% select(X)
write.table(case_samples, "~/Private/Previous_Cancer_Project/Re_Run/case_samps.txt")
```