---
title: "ReteroSpective Figures"
author: "Jacob T. Nearing"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


display_items_out <-  "~/Private/CHAPTER_4/Publication_Markdowns/Display_items"

library(cowplot)
library(ggplot2)
```

# Main Figures

## Diversity Figure
```{r}
alpha_all_cancer <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/ret_path_alpha_all.RDS")

top_layer_ret_div <- plot_grid(alpha_all_cancer[[2]] + theme_cowplot() + theme(legend.position = "none", text = element_text(size = 20), 
                                                                               axis.text.x = element_text(size = 14, angle=65, vjust = .5)),
                               alpha_all_cancer[[3]] + theme_cowplot() + theme(legend.position = "none", text = element_text(size = 20),
                                                                               axis.text.x = element_text(size = 14, angle = 65, vjust = .5)),
                               #cowplot::get_legend(alpha_all_cancer[[2]]),
                               nrow=1, labels = c("A","B"))
                               #rel_widths = c(1,1,.2))
top_layer_ret_div
```


```{r}
beta_weighted <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Ret_PATH_wuni.RDS")

ret_div_fig <- plot_grid(top_layer_ret_div,
                         beta_weighted + theme_cowplot() + coord_fixed() + theme(text = element_text(size = 20)),
                         nrow=2,
                         labels=c("","C"))
ret_div_fig
```



```{r}
breast_indiv <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Breast_plots_all_beta.RDS")

Prostate_indiv <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Prostate_plots_all_beta.RDS")

CRC_indiv <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/CRC_plots_all_beta.RDS")


breast_indiv_filt <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Breast_plots_all_beta_time6.RDS")

Prostate_indiv_filt <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Prostate_plots_all_beta_time6.RDS")

CRC_indiv_filt <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/CRC_plots_all_beta_time6.RDS")



```

## Indiv beta

```{r}
top <- plot_grid(#breast_indiv[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
          breast_indiv[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
          breast_indiv[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
          nrow=1, labels=c("A",""))

mid <- plot_grid(#Prostate_indiv[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                 Prostate_indiv[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                 Prostate_indiv[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                 nrow=1, labels=c("B",""))
bot <- plot_grid(#CRC_indiv[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                 CRC_indiv[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                 CRC_indiv[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                 nrow=1, labels=c("C",""))


indiv_beta <- plot_grid(top, mid, bot, nrow=3)
indiv_beta_leg <- plot_grid(indiv_beta, get_legend(breast_indiv[[1]][[1]]), ncol = 2,
                            rel_widths = c(1,.1))

indiv_beta_leg
```

```{r}
bottom_ret_div_2 <- plot_grid(breast_indiv[[1]][[1]] + theme_cowplot() + theme(legend.position = "none") + ggtitle(""),
                              Prostate_indiv[[1]][[1]] + theme_cowplot() + theme(legend.position = "none") + ggtitle(""),
                              CRC_indiv[[1]][[1]] + theme_cowplot() + theme(legend.position = "none") + ggtitle(""),
                              nrow=1)
bottom_ret_div_2 <- plot_grid(bottom_ret_div_2, get_legend(breast_indiv[[1]][[1]]), ncol=2,
                              rel_widths = c(1,.1),
                              labels=c("C",""))

ret_div_fig_2 <- plot_grid(top_layer_ret_div, bottom_ret_div_2, nrow=2)
ret_div_fig_2

ggsave("~/Private/CHAPTER_4/Cleaned_Repo_D1/Display_Items/Main_Figures/Figure1.pdf", plot=ret_div_fig_2, dpi = 600, width = 9, height = 9, units = "in")

ggsave("~/Private/CHAPTER_4/Cleaned_Repo_D1/Display_Items/Main_Figures/Figure1.png",
       plot=ret_div_fig_2, dpi=600, width=9, height=9, units="in")
```


```{r}
beta_weighted <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Ret_PATH_wuni.RDS")
beta_unweighted <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Ret_PATH_uuni.RDS")
beta_bray <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Ret_PATH_bray.RDS")


all_comp_ret_beta <- plot_grid(beta_weighted + theme_cowplot() + theme(legend.position = "none"), 
                               beta_unweighted + theme_cowplot() + theme(legend.position = "none"), 
                               beta_bray + theme_cowplot() + theme(legend.position = "none"),
                               ncol=1)

all_comp_ret_beta_leg <- plot_grid(all_comp_ret_beta, get_legend(beta_weighted), ncol=2,
                                   rel_widths = c(1,.2))
all_comp_ret_beta_leg
```

## Genus DA Figure

```{r}
genus_heat <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS/Ret_PATH_Genus_DA_heat_show_all.RDS")

genus_heat

```

## ML Figure

```{r}


```


# Supplemental

## Alpha All Cancer

```{r}
alpha_all_cancer <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/ret_path_alpha_all.RDS")

alpha_all_cancer_plot <- plot_grid(alpha_all_cancer[[1]] + theme_cowplot() + theme(legend.position = "none"),
                                   # alpha_all_cancer[[2]] + theme_cowplot() + theme(legend.position = "none"),
                                   # alpha_all_cancer[[3]] + theme_cowplot() + theme(legend.position = "none"),
                                   alpha_all_cancer[[4]] + theme_cowplot() + theme(legend.position = "none"),
                                   nrow=2)
alpha_all_cancer_plot

alpha_all_cancer_final <- plot_grid(alpha_all_cancer_plot, cowplot::get_legend(alpha_all_cancer[[1]]),
                                    nrow=1, rel_widths = c(1,.15))
alpha_all_cancer_final


ggsave(filename=paste(display_items_out, "Supp_Figures", "Alpha_overall_cancer.pdf", sep="/"),
       plot=alpha_all_cancer_plot, width=9, height = 9, units = "in", dpi = 600)
```

## Alpha All Cancer Time_filt

```{r}
alpha_all_cancer_time <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/ret_path_alpha_all_time6.RDS")

alpha_all_cancer_plot_time <- plot_grid(alpha_all_cancer_time[[1]] + theme_cowplot() + theme(legend.position = "none"),
                                   alpha_all_cancer_time[[2]] + theme_cowplot() + theme(legend.position = "none"),
                                   alpha_all_cancer_time[[3]] + theme_cowplot() + theme(legend.position = "none"),
                                   alpha_all_cancer_time[[4]] + theme_cowplot() + theme(legend.position = "none"),
                                   nrow=4)
alpha_all_cancer_plot_time

alpha_all_cancer_plot_time_final <- plot_grid(alpha_all_cancer_plot_time,
                                              cowplot::get_legend(alpha_all_cancer_time[[1]]),
                                              nrow=1, rel_widths = c(1,.15))
alpha_all_cancer_plot_time_final
```

# DA analysis

## ASVs

```{r}
DA_ASVs <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Ret_PATH_ASV_DA_heats_show_diffs.RDS")

DA_ASVs

```

## Genera

```{r}
DA_Genera <- readRDS("~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS/Ret_PATH_Genus_DA_heat_show_all.RDS")


DA_Genera

##1000, 760

ggsave("~/Private/CHAPTER_4/Cleaned_Repo_D1/Display_Items/Main_Figures/Figure2.pdf",
       width=1000, height=760, units = "px", dpi=600, scale=1)

ggsave("~/Private/CHAPTER_4/Cleaned_Repo_D1/Display_Items/Main_Figures/Figure2.png",
       width=1000, height=760, units="px", dpi=600)

```


# ML

