---
title: "RF_overall_analysis_caret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(pROC)
library(dplyr)

library(cvAUC)

library(cowplot)
library(randomForest)
library(ggbeeswarm)
library(reshape2)

col_list <- col_list <- c('#b74a8c',
              '#8c7029',
              '#7464c0',
              '#ac5a51')

make_pROC_curve_mean <- function(list_of_models, col_list, legend=F){
  
  text_pos <- c(0.3,0.25,0.2,0.15)
  add <- F
  
  roc_list <- list()
  for(i in 1:length(list_of_models)){
    name <- names(list_of_models)[i]
    mean_votes <- list_of_models[[i]]$pred %>% group_by(rowIndex) %>% summarize_if(is.numeric, list(name=mean))
    mean_votes$obs <- list_of_models[[i]]$trainingData$.outcome[mean_votes$rowIndex]
    
    temp_roc <- roc(response=mean_votes$obs, predictor = mean_votes$Case_name, ci=T, levels=c("Control", "Case"),
                    direction="<")
    roc_list[[name]] <- temp_roc
  }
  ci.list <- lapply(roc_list, ci.se, specificities=seq(0,1,0.05))
  
  dat.ci.list <- lapply(ci.list, function(ciobj)
    data.frame(x=as.numeric(rownames(ciobj)),
               lower=ciobj[,1],
               upper=ciobj[,3]))
  
  dat.auc.list <- lapply(roc_list, function(x)
    data.frame(lower=x$ci[1],
               mid=x$ci[2],
               upper=x$ci[3]))
  
  p <- ggroc(roc_list) + theme_minimal() + 
   geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") +
   coord_equal() +
     scale_color_manual("Feature type", values=col_list) +
     scale_fill_manual("Feature type", values=col_list)
  


  
  for(i in 1:length(dat.ci.list)) {
    dat.ci.list[[i]]$name <- factor(names(dat.ci.list)[i], levels=c("ASV RA", "ASV CLR", "Genus CLR", "Genus RA"))
    
    p <- p + geom_ribbon(
      data = dat.ci.list[[i]],
      aes(x = x, ymin = lower, ymax = upper, fill=name),
      alpha = .1,
      inherit.aes = F)
  
    dat.auc.list[[i]]$name <- factor(names(dat.ci.list)[i], levels=c("ASV RA", "ASV CLR", "Genus CLR", "Genus RA"))
    

    p <- p + geom_text(
      data=dat.auc.list[[i]],
      aes(x=.25,
          label = paste("AUC: ", round(mid, 3), " (", round(lower, 3), " - ", round(upper, 3), ")", sep=""),
          color=name),
      inherit.aes=F,
      y=text_pos[i],
      show.legend=FALSE)
    message(text_pos[i])
  } 
  
  return(p)
}


```

# Model ROCs

## Breast

```{r}
Br_ASV_RA <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/ASV_RA_RCV_down_caret.RDS")
Br_ASV_CLR <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/ASV_CLR_RCV_down_caret.RDS")

Br_Genus_RA <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/Genus_RA_RCV_down_caret.RDS")
Br_Genus_CLR <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Breast/Genus_CLR_RCV_down_caret.RDS")

Br_models <- list("ASV CLR"=Br_ASV_CLR, 
                  "ASV RA"=Br_ASV_RA, 
                  "Genus CLR"=Br_Genus_CLR, 
                  "Genus RA"=Br_Genus_RA)

Br_plot_mean <- make_pROC_curve_mean(Br_models, col_list)
Br_plot_mean
```

## Prostate

```{r}
Pr_ASV_RA <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/ASV_RA_RCV_down_caret.RDS")
Pr_ASV_CLR <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/ASV_CLR_RCV_down_caret.RDS")

Pr_Genus_RA <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/Genus_RA_RCV_down_caret.RDS")
Pr_Genus_CLR <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/Prostate/Genus_CLR_RCV_down_caret.RDS")

Pr_models <- list("ASV CLR"=Pr_ASV_CLR, 
                  "ASV RA"=Pr_ASV_RA, 
                  "Genus CLR"=Pr_Genus_CLR, 
                  "Genus RA"=Pr_Genus_RA)

Pr_plot <- make_pROC_curve_mean(Pr_models, col_list)
Pr_plot
```

## Colon

```{r}
Cr_ASV_RA <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/ASV_RCV_down_caret.RDS")
Cr_ASV_CLR <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/ASV_CLR_RCV_down_caret.RDS")

Cr_Genus_RA <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/Genus_RA_RCV_down_caret.RDS")
Cr_Genus_CLR <- readRDS("~/Private/CHAPTER_4/Retero/PATH/Random_Forest/CRC/Genus_CLR_RCV_down_caret.RDS")

Cr_models <- list("ASV CLR"=Cr_ASV_CLR, 
                  "ASV RA"=Cr_ASV_RA, 
                  "Genus CLR"=Cr_Genus_CLR, 
                  "Genus RA"=Cr_Genus_RA)


Cr_plot_mean <- make_pROC_curve_mean(Cr_models, col_list)
Cr_plot_mean
```

## Final plot

```{r}
Ret_AUC_plot <- plot_grid(Br_plot_mean + ggtitle("Breast") + 
                            theme(legend.position = "none", plot.title = element_text(hjust=0.5)), 
                          Pr_plot + ggtitle("Prostate") + 
                            theme(legend.position = "none", plot.title = element_text(hjust=0.5)), 
                          Cr_plot_mean + ggtitle("Colon") + 
                            theme(legend.position = "none", plot.title = element_text(hjust=0.5)), 
                          nrow=1, labels=c("A", "B", "C"),
                          label_y=.1)

Ret_AUC_plot

Ret_AUC_plot_leg <- plot_grid(NULL,
                              Ret_AUC_plot, 
                              NULL,
                              get_legend(Br_plot_mean + theme(legend.position = "bottom")),
                              nrow=4,
                              rel_heights = c(-.3, 1,-.4, .2))
Ret_AUC_plot_leg
# ggsave("~/Private/CHAPTER_4/Cleaned_Repo_D1/Display_Items/Main_Figures/Figure3.pdf",
#         width = 13, height = 7, units = "in", dpi = 600, plot = Ret_AUC_plot_leg)
# ggsave("~/Private/CHAPTER_4/Cleaned_Repo_D1/Display_Items/Main_Figures/Figure3.png",
#        width=13, height=7, units="in", dpi=600, plot=Ret_AUC_plot_leg)
```

# top features

```{r}

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}


#takes in a list and generates the plots
#barplot of the right and then a violin plot of abundances on the left

Comp_var_imp <- function(list_of_models, list_of_abs, metadata, top=5, taxa_classes){
  
  #make barplots of feat_imp
  barplots <- list()
  for(i in 1:length(list_of_models)){
    imp_df <- list_of_models[[i]]$finalModel$importance
    
    imp_df <- imp_df %>% data.frame() %>% arrange(desc(MeanDecreaseAccuracy)) %>% head(n=top)
    imp_df$feature <- rownames(imp_df)
    
    #dealing with ASVs
    if(i < 3){
      imp_df <- imp_df %>% left_join(Taxa_classifications, by="feature")
    }else{
      imp_df$Taxon <- gsub(".*D_.__(?=.*D_.__)", "", imp_df$feature, perl=T)
    }
    
    #get SDs
    sd_df <- list_of_models[[i]]$finalModel$importanceSD %>% data.frame()
    colnames(sd_df) <- paste(colnames(sd_df), "_SD", sep="")
    sd_df$feature <- rownames(sd_df)
    
    imp_df <- imp_df %>% left_join(sd_df, by="feature")
    #imp_df$feature <- factor(imp_df$feature, levels=rev(imp_df$feature))
    imp_df$Taxon <- factor(imp_df$Taxon, levels=rev(imp_df$Taxon))
    

    p <- ggplot(imp_df, aes(y=MeanDecreaseAccuracy, x=Taxon)) +
      geom_col(fill="#999999", col="black") +
      geom_errorbar(aes(ymin=MeanDecreaseAccuracy-MeanDecreaseAccuracy_SD,
                        ymax=MeanDecreaseAccuracy+MeanDecreaseAccuracy_SD),
                    width=.2) +
      coord_flip()
      
    barplots[[i]] <- p
  }
  #make boxplots from ab data

  ab_boxplots <- list()
  for(i in 1:length(list_of_models)){
   
    
    ab_data <- list_of_abs[[i]][,as.character(barplots[[i]]$data$feature)]
    
    
    stopifnot(identical(rownames(ab_data), as.character(metadata$X)))
    
    ab_data$Case.Control <- metadata$Case.Control
    
    ab_data_melt <- melt(ab_data)

    if(i < 3){
      ab_data_melt$Taxon <- taxa_classes$Taxon[match(ab_data_melt$variable, taxa_classes$feature)]
    }else{
      ab_data_melt$Taxon <- gsub(".*D_.__(?=.*D_.__)", "", ab_data_melt$variable, perl=T)
    }
    
    ab_data_melt$Taxon <- factor(ab_data_melt$Taxon, levels=rev(levels(barplots[[i]]$data$Taxon)))
  
    if(i %% 2==0){
      p <- ggplot(ab_data_melt, aes(x=Case.Control, y=log10(value+0.00001), fill=Case.Control)) +
        geom_boxplot(outlier.shape = NA) +
        geom_quasirandom(alpha=0.2) +
        coord_flip() +
        facet_wrap(~Taxon, nrow=top) +
        ylab("log10(Relative Abundance)") +
        xlab("")
    }else{
      p <- ggplot(ab_data_melt, aes(x=Case.Control, y=value, fill=Case.Control)) +
        geom_boxplot(outlier.shape = NA) +
        geom_quasirandom(alpha=0.2) +
        coord_flip() +
        facet_wrap(~Taxon, nrow=top) +
        ylab("Center-Log-Ratio Abundance") +
        xlab("")
    }

    
    ab_boxplots[[i]] <- p
  }
  
  return(list(barplots, ab_boxplots))
}

Taxa_classifications <- read.table("~/Private/Sequences/Redo_Combined_Data/deblur/Freq_filt_18/taxonomy/taxa/taxonomy.tsv", sep="\t",
                                   header=T, stringsAsFactors = F)

Taxa_classifications$Taxon <- gsub(".*D_.__(?=.*D_.__)", "", Taxa_classifications$Taxon, perl=T)
Taxa_classifications$Taxon <- make.unique(Taxa_classifications$Taxon)
colnames(Taxa_classifications)[1] <- "feature"
```

## Load in data
```{r load_metadata}

Metadata_Breast <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Breast_21_03_11.csv", row.names = 1)
Metadata_CRC <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_CRC_21_03_11.csv", row.names = 1)
Metadata_Prostate <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Prostate_21_03_11.csv", row.names = 1)


### Load in alpha data

Alpha_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_Breast.RDS")
Alpha_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_CRC.RDS")
Alpha_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_prostate.RDS")


Metadata_Breast <- Metadata_Breast[rownames(Alpha_Breast),]
Metadata_CRC <- Metadata_CRC[rownames(Alpha_CRC),]
Metadata_Prostate <- Metadata_Prostate[rownames(Alpha_Prostate),]

Metadata_Breast_Cases <- Metadata_Breast[which(Metadata_Breast$Case.Control==1),]
Metadata_CRC_Cases <- Metadata_CRC[which(Metadata_CRC$Case.Control==1),]
Metadata_Prostate_Cases <- Metadata_Prostate[which(Metadata_Prostate$Case.Control==1),]

Alpha_Breast_Cases <- Alpha_Breast[rownames(Metadata_Breast_Cases),]
Alpha_CRC_Cases <- Alpha_CRC[rownames(Metadata_CRC_Cases),]
Alpha_Prostate_Cases <- Alpha_Prostate[rownames(Metadata_Prostate_Cases),]

Alpha_Breast$X <- rownames(Alpha_Breast)
Breast_data <- Alpha_Breast %>% left_join(Metadata_Breast, by="X")
Breast_data$Case.Control <- ifelse(Breast_data$Case.Control==1, "Case", "Control")

Alpha_Prostate$X <- rownames(Alpha_Prostate)
Prostate_data <- Alpha_Prostate %>% left_join(Metadata_Prostate, by="X")
Prostate_data$Case.Control <- ifelse(Prostate_data$Case.Control==1, "Case", "Control")

Alpha_CRC$X <- rownames(Alpha_CRC)
CRC_data <- Alpha_CRC %>% left_join(Metadata_CRC, by="X")
CRC_data$Case.Control <- ifelse(CRC_data$Case.Control==1, "Case", "Control")

Alpha_Breast_Cases$X <- rownames(Alpha_Breast_Cases)
Breast_case_data <- Alpha_Breast_Cases %>% left_join(Metadata_Breast_Cases, by="X")
Breast_case_data$Case.Control <- ifelse(Breast_case_data$Case.Control==1, "Case", "Control")

Alpha_Prostate_Cases$X <- rownames(Alpha_Prostate_Cases)
Prostate_case_data <- Alpha_Prostate_Cases %>% left_join(Metadata_Prostate_Cases, by="X")
Prostate_case_data$Case.Control <- ifelse(Prostate_case_data$Case.Control==1, "Case", "Control")

Alpha_CRC_Cases$X <- rownames(Alpha_CRC_Cases)
CRC_case_data <- Alpha_CRC_Cases %>% left_join(Metadata_CRC_Cases, by="X")
CRC_case_data$Case.Control <- ifelse(CRC_case_data$Case.Control==1, "Case", "Control")


Breast_data$age_diff <- Breast_data$YEARS_SINCE_BC
Prostate_data$age_diff <- Prostate_data$YEARS_SINCE_PC
CRC_data$age_diff <- CRC_data$YEARS_SINCE_CRC_CANCER

Breast_data$Type <- "Breast"
Prostate_data$Type <- "Prostate"
CRC_data$Type <- "Colon"

Breast_data$Case.Control <- factor(Breast_data$Case.Control, levels=c("Control", "Case"))
Prostate_data$Case.Control <- factor(Prostate_data$Case.Control, levels=c("Control", "Case"))
CRC_data$Case.Control <- factor(CRC_data$Case.Control, levels=c("Control","Case"))

Breast_data <- remove_non_matching_caseIDS(Breast_data)
Prostate_data <- remove_non_matching_caseIDS(Prostate_data)
CRC_data <- remove_non_matching_caseIDS(CRC_data)

Breast_data_comb <- Breast_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)
Prostate_data_comb <- Prostate_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)
CRC_data_comb <- CRC_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)


Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)

Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r load_feature_data}

ASV_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_breast.RDS")
ASV_Breast <- ASV_Breast[-which(rowSums(ASV_Breast)==0),]

ASV_Breast <- ASV_Breast[,Breast_data$X]


ASV_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_CRC.RDS")
ASV_CRC <- ASV_CRC[-which(rowSums(ASV_CRC)==0),]
ASV_CRC <- ASV_CRC[,CRC_data$X]


ASV_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_Prostate.RDS")
ASV_Prostate <- ASV_Prostate[-which(rowSums(ASV_Prostate)==0),]
ASV_Prostate <- ASV_Prostate[,Prostate_data$X]





## load in Genus
Genus_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_breast.RDS")
Genus_Breast <- Genus_Breast[-which(rowSums(Genus_Breast)==0),]
Genus_Breast <- Genus_Breast[,Breast_data$X]


Genus_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_CRC.RDS")
Genus_CRC <- Genus_CRC[-which(rowSums(Genus_CRC)==0),]
Genus_CRC <- Genus_CRC[,CRC_data$X]

Genus_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_prostate.RDS")
Genus_Prostate <- Genus_Prostate[-which(rowSums(Genus_Prostate)==0),]
Genus_Prostate <- Genus_Prostate[,Prostate_data$X]



```


```{r normalize_features}
ASV_Breast_CLR <- data.frame(apply(ASV_Breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_CRC_CLR <- data.frame(apply(ASV_CRC + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_Prostate_CLR <- data.frame(apply(ASV_Prostate + 1, 2, function(x){log(x) - mean (log(x))}), check.names = F)

ASV_Breast_CLR_flip <- data.frame(t(ASV_Breast_CLR), check.names = F)
ASV_Breast_CLR_flip$X <- rownames(ASV_Breast_CLR_flip)

ASV_CRC_CLR_flip <- data.frame(t(ASV_CRC_CLR), check.names = F)
ASV_CRC_CLR_flip$X <- rownames(ASV_CRC_CLR_flip)

ASV_Prostate_CLR_flip <- data.frame(t(ASV_Prostate_CLR), check.names = F)
ASV_Prostate_CLR_flip$X <- rownames(ASV_Prostate_CLR_flip)

Genus_Breast_CLR <- data.frame(apply(Genus_Breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_CRC_CLR <- data.frame(apply(Genus_CRC + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_Prostate_CLR <- data.frame(apply(Genus_Prostate + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)

Genus_Breast_CLR_flip <- data.frame(t(Genus_Breast_CLR), check.names = F)
Genus_Breast_CLR_flip$X <- rownames(Genus_Breast_CLR_flip)

Genus_CRC_CLR_flip <- data.frame(t(Genus_CRC_CLR), check.names = F)
Genus_CRC_CLR_flip$X <- rownames(Genus_CRC_CLR_flip)

Genus_Prostate_CLR_flip <- data.frame(t(Genus_Prostate_CLR), check.names = F)
Genus_Prostate_CLR_flip$X <- rownames(Genus_Prostate_CLR_flip)


ASV_Breast_RA <- sweep(ASV_Breast, 2, colSums(ASV_Breast), '/')
ASV_CRC_RA <- sweep(ASV_CRC, 2, colSums(ASV_CRC), '/')
ASV_Prostate_RA <- sweep(ASV_Prostate, 2, colSums(ASV_Prostate), '/')

ASV_Breast_RA_flip <- data.frame(t(ASV_Breast_RA), check.names=F)
ASV_Breast_RA_flip$X <- rownames(ASV_Breast_RA_flip)

ASV_CRC_RA_flip <- data.frame(t(ASV_CRC_RA), check.names = F)
ASV_CRC_RA_flip$X <- rownames(ASV_CRC_RA_flip)

ASV_Prostate_RA_flip <- data.frame(t(ASV_Prostate_RA), check.names = F)
ASV_Prostate_RA_flip$X <- rownames(ASV_Prostate_RA_flip)

Genus_Breast_RA <- sweep(Genus_Breast, 2, colSums(Genus_Breast), '/')
Genus_CRC_RA <- sweep(Genus_CRC, 2, colSums(Genus_CRC), '/')
Genus_Prostate_RA <- sweep(Genus_Prostate, 2, colSums(Genus_Prostate), '/')

Genus_Breast_RA_flip <- data.frame(t(Genus_Breast_RA), check.names = F)
Genus_Breast_RA_flip$X <- rownames(Genus_Breast_RA_flip)

Genus_CRC_RA_flip <- data.frame(t(Genus_CRC_RA), check.names = F)
Genus_CRC_RA_flip$X <- rownames(Genus_CRC_RA_flip)

Genus_Prostate_RA_flip <- data.frame(t(Genus_Prostate_RA), check.names = F)
Genus_Prostate_RA_flip$X <- rownames(Genus_Prostate_RA_flip)
```


## Breast
```{r}
Br_ab_data <- list(ASV_Breast_CLR_flip,
                   ASV_Breast_RA_flip,
                   Genus_Breast_CLR_flip,
                   Genus_Breast_RA_flip)

Var_imp_plots <- Comp_var_imp(list_of_models = Br_models,
                              list_of_abs = Br_ab_data, metadata = Breast_data, top = 10)

Var_imp_plots[[1]][[1]]
```

## Prostate
```{r}

```

## Colon
```{r}
Cr_ab_data <- list(ASV_CRC_CLR_flip,
                   ASV_CRC_RA_flip,
                   Genus_CRC_CLR_flip,
                   Genus_CRC_RA_flip)

Var_imp_plots_Cr <- Comp_var_imp(list_of_models = Cr_models,
                                 list_of_abs = Cr_ab_data, metadata=CRC_data, top=10,
                                 taxa_classes = Taxa_classifications)



plot_grid(Var_imp_plots_Cr[[1]][[2]] + theme_cowplot(),
Var_imp_plots_Cr[[2]][[2]] + theme_cowplot())



plot_grid(Var_imp_plots_Cr[[1]][[4]] + theme_cowplot(),
          Var_imp_plots_Cr[[2]][[4]] + theme_cowplot())
```