---
title: "Prospective_Figures_ATP"
author: "Jacob T. Nearing"
date: "08/03/2022"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(broom)
library(kableExtra)
library(ggplot2)
library(ggbeeswarm)
library(cowplot)

library(reshape2)
library(ggpubr)
library(rstatix)
library(vegan)

theme_set(theme_cowplot())


run_lm_comb_data <- function(data, type_split, main_variable, covariates, estimate_var){
  
  anova_res <- list()
  ggpubr_res <- list()
  
  for(i in unique(data[,type_split])){
    pass_in_data <- data %>% filter(!!sym(type_split)==i)
    
    res <- run_lm_add_using_ggplot(pass_in_data, main_variable = main_variable, covariates = covariates,
                            estimate_var = estimate_var, fct=i, type_split)
    anova_res[[i]] <- res[[1]]
    ggpubr_res[[i]] <- res[[2]]
  }
  ggpurb_df <- do.call(rbind, ggpubr_res)
  
  return(list(anova_res, ggpurb_df))
  
}

run_lm_add_using_ggplot <- function(data, main_variable, covariates, estimate_var, fct, type_split){
    
  
    formula <- paste(covariates, main_variable, sep=" + ")
    final_formula <- paste(estimate_var, "~", formula, sep=" ")
    message(final_formula)
    model <- lm(final_formula, data)
    anova_res <- anova(model)
    anova_res$feat <- rownames(anova_res)
    anova_filt <- anova_res %>% filter(feat==main_variable)
    pval <- anova_filt$`Pr(>F)`
    
    if(is.null(fct)){
      ggpurb_format <- data.frame(group1=levels(data[,main_variable])[1],
                                group2=levels(data[,main_variable])[2],
                                p.adj=pval)
    }else{
      ggpurb_format <- data.frame(group1=levels(data[,main_variable])[1],
                                group2=levels(data[,main_variable])[2],
                                p.adj=round(pval,3),
                                supp=fct,
                                .y.=max(data[,estimate_var])*1.20)
      
      colnames(ggpurb_format)[4] <- type_split
      
    }
    
    return(list(anova_res, ggpurb_format))
}


make_alpha_div_plot <- function(df, split_type, main_variable, covariates, estimate_var,ylab,pval=T,hide.ns){
  
  stats <- run_lm_comb_data(data=df, type_split = split_type, main_variable = main_variable,
                                        covariates = covariates, estimate_var = estimate_var)
  
  plot <- ggplot(df, aes_string(x=main_variable, y=estimate_var)) +
  geom_boxplot(alpha=0.1, width=0.1, outlier.alpha = 0) +
  geom_violin(alpha=0.2, aes_string(fill=main_variable)) +
  geom_quasirandom(alpha=0.2) +
  xlab("") +
  ylab(ylab) +
  facet_grid(reformulate(split_type))

  if(pval==T){
    plot <- plot + stat_pvalue_manual(stats[[2]], label="p.adj", hide.ns=hide.ns, y.position = '.y.')
  }
  
  return(plot)
}

make_all_alpha_div_plots <- function(df, split_type, main_variable, covariates, estimate_var, ylab, pval=T, hide.ns=T){
  plot_list <- list()
  j <- 1
  for(i in ylab){
    plot_list[[i]] <- make_alpha_div_plot(df, split_type, main_variable, covariates, estimate_var[j], i, pval,hide.ns)
    j <- j + 1
  }
  return(plot_list)
  
}
```


```{r}
# Load data
Combined_data <- readRDS("~/Private/CHAPTER_4/Revised_data/Combined_data_ATP_Pro.RDS")
Combined_data_filt <- readRDS("~/Private/CHAPTER_4/Revised_data/Combined_data_ATP_Pro_filt.RDS")

Combined_data_filt$X <- as.character(Combined_data_filt$X)
```

# Alpha Diversity

## no time filt

```{r}
est_vars <- c("faith_pd", "shannon_entropy", "pielou_evenness", "observed_features")
ylabs <- c("Faith's PD", "Shannon Div.", "Evenness", "Richness")


all_cancer_plots <- make_all_alpha_div_plots(df=Combined_data, split_type = "Type", main_variable = "Case.Control", covariates = NULL,
                                             estimate_var = est_vars, ylab = ylabs, hide.ns=T)


Sup_fig_alpha <- plot_grid(all_cancer_plots[[1]] + theme_cowplot() + theme(legend.position = "none"),
                           #all_cancer_plots[[2]]+ theme_cowplot() + theme(legend.position = "none") ,
                           all_cancer_plots[[3]] + theme_cowplot() + theme(legend.position = "none"),
                           #all_cancer_plots[[4]] + theme_cowplot() + theme(legend.position = "none"),
                           nrow=2)


Sup_fig_alpha_leg <- plot_grid(Sup_fig_alpha,
                               get_legend(all_cancer_plots[[1]]),
                               nrow=1,
                               rel_widths = c(1,.1))

Sup_fig_alpha_leg


lm_alpha_res_faith <- run_lm_comb_data(data = Combined_data, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[1]])

lm_alpha_res[[1]]

lm_alpha_res_shannon <- run_lm_comb_data(data = Combined_data, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[2]])

lm_alpha_res_shannon[[1]]

lm_alpha_res_even <- run_lm_comb_data(data = Combined_data, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[3]])

lm_alpha_res_even[[1]]

lm_alpha_res_rich <- run_lm_comb_data(data = Combined_data, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[4]])

lm_alpha_res_rich[[1]]


test <- lm(Breast_data_comb$faith_pd ~ Breast_data_comb$Case.Control)
anova(test)

saveRDS(all_cancer_plots, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_alpha_all.RDS")


```

## Covar analysis
```{r}
est_vars <- c("faith_pd", "observed_features", "shannon_entropy", "pielou_evenness")

covar_stat_res <- list()
covar_stat_res_age <- list()
unadjusted_res <- list()


covars_age <- "`SALIVA AGE` + PARTICIPANT_SEX"

covars_all <- "`SALIVA AGE` + PARTICIPANT_SEX + Comb_WHR + Comb_Height + Comb_Veg"

for(i in est_vars){
  
  covar_stat_res[[i]] <- run_lm_comb_data(data=Combined_data, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars_all, 
                                     estimate_var = i)
  covar_stat_res_age[[i]] <- run_lm_comb_data(data=Combined_data, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars_age, 
                                     estimate_var = i)
  
  unadjusted_res[[i]] <- run_lm_comb_data(data=Combined_data, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = NULL, 
                                     estimate_var = i)
  
}

unadjusted_res
covar_stat_res_age

covar_stat_res
```



## Time filt

```{r}
all_cancer_plots_filt <- make_all_alpha_div_plots(df=Combined_data_filt, split_type = "Type", main_variable = "Case.Control", covariates = NULL,
                                             estimate_var = est_vars, ylab = ylabs)


Sup_fig_alpha_time <- plot_grid(all_cancer_plots_filt[[1]] + theme_cowplot() + theme(legend.position = "none"),
                                all_cancer_plots_filt[[2]] + theme_cowplot() + theme(legend.position = "none"),
                                all_cancer_plots_filt[[3]] + theme_cowplot() + theme(legend.position = "none"),
                                all_cancer_plots_filt[[4]] + theme_cowplot() + theme(legend.position = "none"),
                                nrow=4)
                                
Sup_fig_alpha_time_leg <- plot_grid(Sup_fig_alpha_time,
                                    get_legend(all_cancer_plots_filt[[1]]),
                                    nrow=1, 
                                    rel_widths = c(1,.1))

Sup_fig_alpha_time_leg

lm_alpha_res_faith <- run_lm_comb_data(data = Combined_data_filt, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[1]])

lm_alpha_res_faith[[1]]

lm_alpha_res_shannon <- run_lm_comb_data(data = Combined_data_filt, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[2]])

lm_alpha_res_shannon[[1]]

lm_alpha_res_even <- run_lm_comb_data(data = Combined_data_filt, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[3]])

lm_alpha_res_even[[1]]

lm_alpha_res_rich <- run_lm_comb_data(data = Combined_data_filt, type_split = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars[[4]])

lm_alpha_res_rich[[1]]


saveRDS(all_cancer_plots_filt, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_alpha_all_time4.RDS")
```


## Covar filt
```{r}
filt_covar_stat_res <- list()
filt_covar_stat_res_age <- list()
filt_unadjusted_res <- list()

for(i in est_vars){
  filt_covar_stat_res[[i]] <- run_lm_comb_data(data=Combined_data_filt, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars_all, 
                                     estimate_var = i)
  
    filt_covar_stat_res_age[[i]] <- run_lm_comb_data(data=Combined_data_filt, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars_age, 
                                     estimate_var = i)
    
    filt_unadjusted_res[[i]] <- run_lm_comb_data(data=Combined_data_filt, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = NULL, 
                                     estimate_var = i)
}


filt_unadjusted_res

filt_covar_stat_res_age

filt_covar_stat_res

```

# Beta Diversity
```{r}
plot_pca_all <- function(dist, meta, title, facet_type=NULL){
  
  dist_filt <- dist[meta$X, meta$X]
  
  dist_pca <- cmdscale(dist_filt, eig=T)
  
  dist_plot_data <- data.frame(PC1=dist_pca$points[,1],
                               PC2=dist_pca$points[,2],
                               Case.Control=meta$Case.Control_type,
                               facet=meta[,facet_type])
  PC1_size <- round(dist_pca$eig[1]/sum(dist_pca$eig)*100,1)
  PC2_size <- round(dist_pca$eig[2]/sum(dist_pca$eig)*100,1)
  
  PC1_lab <- paste0("PC1 ", PC1_size, "%")
  PC2_lab <- paste0("PC2 ", PC2_size, "%")
  
  if(!is.null(facet_type)){
    dist_plot <- ggplot(dist_plot_data, aes(x=PC1, y=PC2)) +
      geom_point(aes(fill=Case.Control, color=Case.Control)) +
      stat_ellipse(aes(group=Case.Control, color=Case.Control)) +
      theme(legend.title = element_blank()) +
      xlab(PC1_lab) +
      ylab(PC2_lab) +
      ggtitle(title) +
      facet_grid(~ facet)
    
    return(dist_plot)
    
  }else{
      
  dist_plot <- ggplot(dist_plot_data, aes(x=PC1, y=PC2, fill=Case.Control, group=Case.Control, color=Case.Control)) +
    geom_point() +
    stat_ellipse() +
    theme(legend.title = element_blank()) +
    xlab(PC1_lab) +
    ylab(PC2_lab) +
    ggtitle(title)
  
  return(dist_plot)
    
  }

}


run_adonis_by_facet <- function(dist, meta, facet, covariates, main_variable){
  
  formula <- paste(covariates, main_variable, sep=" + ")
  final_formula <- as.formula(paste("temp_dist", formula, sep="~"))
  message(final_formula)
  message(facet)
  meta_splits <- group_split(meta, !!ensym(facet))
  adonis_res <- list()

  for(i in 1:length(meta_splits)){
    name <- as.character(meta_splits[[i]][1,facet,drop=T])
    message(name)
    samps <- as.data.frame(meta_splits[[i]][,"X"])
    temp_dist <- dist[samps$X, samps$X]
    message("running adonis")
    
    temp_res<- adonis(formula=final_formula, data=meta_splits[[i]], by="margin")
    temp_res <- as.data.frame(temp_res$aov.tab)
    temp_res$feature <- rownames(temp_res)
    
    adonis_res[[name]] <- temp_res
  }
  
  main_vars_p <- c()
  for(i in 1:length(adonis_res)){
    temp_p <- adonis_res[[i]] %>% filter(feature==main_variable) %>% select(`Pr(>F)`)
    main_vars_p <- c(main_vars_p, paste("p: ",as.character(temp_p), sep=""))
  }
  
  annotation_df <- data.frame(col1=levels(meta[,facet]),
                              label=main_vars_p)
  colnames(annotation_df)[1] <- "facet"
  return(list(annotation_df,adonis_res))
}



make_all_plots_and_adonis <- function(list_dist, list_title, metadata, facet, covariate, main_variable){
  
  pca_plots <- list()
  adonis_res <- list()
  
  for(i in names(list_dist)){
    pca_plots[[i]] <- plot_pca_all(dist=list_dist[[i]], meta = metadata, title = list_title[[i]], facet_type = facet)
    adonis_res[[i]] <- run_adonis_by_facet(dist=list_dist[[i]], meta=metadata, facet = facet, covariates = covariate, main_variable = main_variable) 
  }
  
  return(list(pca_plots, adonis_res))
}
```

```{r}
WEIGHTED_UNIFRAC <- "~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_beta/weighted_unifrac.tsv"
BRAY_CURTIS <- "~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_beta/bray_curt.tsv"
UNWEIGHTED_UNIFRAC <- "~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_beta/unweighted_unifrac.tsv"
RPCA <- "~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_beta/rpca_distance.tsv"

w_unifrac <- read.table(WEIGHTED_UNIFRAC, sep="\t", header=T, row.names = 1, comment.char="", quote="", check.names = F)

bray_curt <- read.table(BRAY_CURTIS, sep="\t", header=T, row.names = 1, comment.char = "", quote="", check.names = F)

u_unifrac <- read.table(UNWEIGHTED_UNIFRAC, sep="\t", header=T, row.names = 1, comment.char="", quote="", check.names = F)

rpca <- read.table(RPCA, sep="\t", header=T, row.names=1, comment.char="", quote="", check.names=F)

Combined_data$Case.Control_type <- as.character(Combined_data$Case.Control)

Combined_data$Case.Control_type[which(Combined_data$Case.Control_type=="case")] <- as.character(Combined_data$Type[which(Combined_data$Case.Control=="case")])


Combined_data_filt$Case.Control_type <- as.character(Combined_data_filt$Case.Control)

Combined_data_filt$Case.Control_type[which(Combined_data_filt$Case.Control_type=="case")] <- as.character(Combined_data_filt$Type[which(Combined_data_filt$Case.Control=="case")])
```

## no time filt
```{r}
Combined_data$X <- as.character(Combined_data$X)

weighted_uni_comb <- w_unifrac[as.character(Combined_data$X), as.character(Combined_data$X)]

unweighted_uni_comb <- u_unifrac[as.character(Combined_data$X), as.character(Combined_data$X)]

bray_comb <- bray_curt[as.character(Combined_data$X), as.character(Combined_data$X)]

rpca_comb <- rpca[as.character(Combined_data$X), as.character(Combined_data$X)]
```

```{r}
weighted_comb_plot <- plot_pca_all(weighted_uni_comb, Combined_data, "Weighted UniFrac")
weighted_comb_plot
saveRDS(weighted_comb_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_atp_beta_wuni.RDS")

unweighted_comb_plot <- plot_pca_all(unweighted_uni_comb, Combined_data, "Unweighted UniFrac")
unweighted_comb_plot
saveRDS(unweighted_comb_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_beta_uuni.RDS")


bray_comb_plot <- plot_pca_all(bray_comb, Combined_data, "Bray Curtis")
saveRDS(bray_comb_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_beta_bray.RDS")
```

```{r}
library(vegan)
adonis(weighted_uni_comb ~ Combined_data$Case.Control_type)
adonis(bray_comb ~ Combined_data$Case.Control_type)
adonis(unweighted_uni_comb ~ Combined_data$Case.Control_type)
```


## Time filt

```{r}
Combined_data_filt$X <- as.character(Combined_data_filt$X)

weighted_comb_time_plot <- plot_pca_all(weighted_uni_comb, Combined_data_filt, "Weighted UniFrac")
saveRDS(weighted_comb_time_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_beta_wuni_time.RDS")

unweighted_comb_time_plot <- plot_pca_all(unweighted_uni_comb, Combined_data_filt, "Unweighted UniFrac")
saveRDS(unweighted_comb_time_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_uuni_time.RDS")

bray_comb_time_plot <- plot_pca_all(bray_comb, Combined_data_filt, "Bray Curtis")
saveRDS(bray_comb_time_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_bray_time.RDS")
```

## Invidivudal

### no time filt

```{r}
dist_list <- list(
  'W_uni' = weighted_uni_comb,
  'U_uni' =  unweighted_uni_comb,
  'bray' = bray_comb,
  'rpca' = rpca_comb
)

title_list <- list(
  'W_uni' = "Weighted UniFrac",
  'U_uni' = "Unweighted UniFrac",
  'bray' = "Bray Curtis",
  'rpca' = " Robust Aitchison"
)

Breast_data_comb <- Combined_data %>% filter(Type=="Breast")
Breast_data_comb$Case.Control_type <- Breast_data_comb$Case.Control
Breast_data_comb$Type <- factor(Breast_data_comb$Type)

Breast_beta_plots <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Breast_data_comb, facet="Type", covariate = NULL,
                                               main_variable = "Case.Control")

Breast_beta_plots

saveRDS(Breast_beta_plots, "~/Private/CHAPTER_4/Revised_Figures/RDS/ATP_Pro_Breast_beta_all.RDS")
```

### adjusted results
```{r}
Br_unadjusted_stat <- list()
Br_adjusted_stat_age <- list()
Br_adjusted_stat <- list()

covars_age <- "`SALIVA AGE` + PARTICIPANT_SEX"

covars_all <- "`SALIVA AGE` + PARTICIPANT_SEX + Comb_WHR + Comb_Height + Comb_Veg"

#need to filter metadata so that it only has samples that are fully complete...

Breast_data_comb_noNA <- Breast_data_comb[-which(is.na(Breast_data_comb$Comb_Height)),]
Breast_data_comb_noNA <- Breast_data_comb_noNA[-which(is.na(Breast_data_comb_noNA$Comb_Veg)),]

Breast_data_comb_noNA <- Breast_data_comb_noNA[-which(is.na(Breast_data_comb_noNA$Comb_WHR)),]


dim(Breast_data_comb_noNA)
dim(Breast_data_comb)
table(Breast_data_comb$Case.Control)
table(Breast_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  Br_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Br_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Br_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_all)
  
  
  
}

names(Br_unadjusted_stat)
Br_unadjusted_stat

names(Br_adjusted_stat_age)
Br_adjusted_stat_age

names(Br_adjusted_stat)
Br_adjusted_stat

```



```{r}
Prostate_data_comb <- Combined_data %>% filter(Type=="Prostate")
Prostate_data_comb$Case.Control_type <- Prostate_data_comb$Case.Control
Prostate_data_comb$Type <- factor(Prostate_data_comb$Type)

Prostate_beta_plots <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Prostate_data_comb, facet="Type", covariate = NULL,
                                                 main_variable="Case.Control")


saveRDS(Prostate_beta_plots, "~/Private/CHAPTER_4/Revised_Figures/RDS/ATP_Pro_Prostate_beta_all.RDS")
```

### adjusted
```{r}
Pr_unadjusted_stat <- list()
Pr_adjusted_stat_age <- list()
Pr_adjusted_stat <- list()


#need to filter metadata so that it only has samples that are fully complete...

Prostate_data_comb_noNA <- Prostate_data_comb[-which(is.na(Prostate_data_comb$Comb_Height)),]

Prostate_data_comb_noNA <- Prostate_data_comb_noNA[-which(is.na(Prostate_data_comb_noNA$Comb_Veg)),]

Prostate_data_comb_noNA <- Prostate_data_comb_noNA[-which(is.na(Prostate_data_comb_noNA$Comb_WHR)),]

table(Prostate_data_comb$Case.Control)
table(Prostate_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  Pr_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Pr_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Pr_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_all)
  
  
  
}

names(Pr_unadjusted_stat)
Pr_unadjusted_stat

names(Pr_adjusted_stat_age)
Pr_adjusted_stat_age

names(Pr_adjusted_stat)
Pr_adjusted_stat

```


```{r}
CRC_data_comb <- Combined_data %>% filter(Type=="Colon")
CRC_data_comb$Case.Control_type <- CRC_data_comb$Case.Control
CRC_data_comb$Type <- factor(CRC_data_comb$Type)

CRC_beta_plots <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=CRC_data_comb, facet="Type", covariate = NULL,
                                            main_variable = "Case.Control")

saveRDS(CRC_beta_plots, "~/Private/CHAPTER_4/Revised_Figures/RDS/ATP_Pro_CRC_beta_all.RDS")
```

```{r}
CRC_unadjusted_stat <- list()
CRC_adjusted_stat_age <- list()
CRC_adjusted_stat <- list()

#need to filter metadata so that it only has samples that are fully complete...
CRC_data_comb_noNA <- CRC_data_comb[-which(is.na(CRC_data_comb$Comb_Height)),]

CRC_data_comb_noNA <- CRC_data_comb_noNA[-which(is.na(CRC_data_comb_noNA$Comb_Veg)),]

CRC_data_comb_noNA <- CRC_data_comb_noNA[-which(is.na(CRC_data_comb_noNA$Comb_WHR)),]

table(CRC_data_comb$Case.Control)
table(CRC_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  CRC_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  CRC_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  CRC_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_all)
  
  
  
}

names(CRC_unadjusted_stat)
CRC_unadjusted_stat

CRC_adjusted_stat_age


CRC_adjusted_stat
```


```{r}
Breast_beta_plots <- readRDS("~/Private/CHAPTER_4/Revised_Figures/RDS/ATP_Pro_Breast_beta_all.RDS")
Prostate_beta_plots <- readRDS("~/Private/CHAPTER_4/Revised_Figures/RDS/ATP_Pro_Prostate_beta_all.RDS")
CRC_beta_plots <- readRDS("~/Private/CHAPTER_4/Revised_Figures/RDS/ATP_Pro_CRC_beta_all.RDS")

Breast_beta_plot <- plot_grid(#Breast_beta_plots[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                              Breast_beta_plots[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                              Breast_beta_plots[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                              Breast_beta_plots[[1]][[4]] + theme_cowplot() + theme(legend.position = "none"),
                              nrow=1)

Prostate_beta_plot <- plot_grid(#Prostate_beta_plots[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                                Prostate_beta_plots[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                                Prostate_beta_plots[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                                Prostate_beta_plots[[1]][[4]] + theme_cowplot() + theme(legend.position = "none"),
                                nrow=1)

CRC_beta_plot <- plot_grid(#CRC_beta_plots[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                           CRC_beta_plots[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                           CRC_beta_plots[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                           CRC_beta_plots[[1]][[4]] + theme_cowplot() + theme(legend.position = "none"),
                           nrow=1)

Sup_beta_ATP <- plot_grid(Breast_beta_plot, Prostate_beta_plot, CRC_beta_plot, nrow=3,
                          labels=c("A", "B", "C"))


Sup_beta_ATP_leg <- plot_grid(Sup_beta_ATP, 
                              get_legend(Breast_beta_plots[[1]][[1]]),
                              rel_widths = c(1,.1))

Sup_beta_ATP_leg

ggsave("~/Private/CHAPTER_4/Revised_Figures/Display_items/Supplemental/ATP_Pro_beta_sup.pdf",
       width=9, height=9)
```

### time fitl

```{r}
Breast_data_comb <- Combined_data_filt %>% filter(Type=="Breast")
Breast_data_comb$Case.Control_type <- Breast_data_comb$Case.Control
Breast_data_comb$Type <- factor(Breast_data_comb$Type)

Breast_beta_plots_time4 <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata = Breast_data_comb, facet="Type", covariate = NULL,
                                                     main_variable = "Case.Control")
saveRDS(Breast_beta_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_breast_beta_time4.RDS")
```

```{r}
Br_unadjusted_stat <- list()
Br_adjusted_stat_age <- list()
Br_adjusted_stat <- list()

covars_age <- "`SALIVA AGE` + PARTICIPANT_SEX"

covars_all <- "`SALIVA AGE` + PARTICIPANT_SEX + Comb_WHR + Comb_Height + Comb_Veg"

#need to filter metadata so that it only has samples that are fully complete...

Breast_data_comb_noNA <- Breast_data_comb[-which(is.na(Breast_data_comb$Comb_Height)),]
Breast_data_comb_noNA <- Breast_data_comb_noNA[-which(is.na(Breast_data_comb_noNA$Comb_Veg)),]

Breast_data_comb_noNA <- Breast_data_comb_noNA[-which(is.na(Breast_data_comb_noNA$Comb_WHR)),]


dim(Breast_data_comb_noNA)
dim(Breast_data_comb)
table(Breast_data_comb$Case.Control)
table(Breast_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  Br_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Br_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Br_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_all)
  
  
  
}

names(Br_unadjusted_stat)
Br_unadjusted_stat

names(Br_adjusted_stat_age)
Br_adjusted_stat_age

names(Br_adjusted_stat)
Br_adjusted_stat

```


```{r}
Prostate_data_comb <- Combined_data_filt %>% filter(Type=="Prostate")
Prostate_data_comb$Case.Control_type <- Prostate_data_comb$Case.Control
Prostate_data_comb$Type <- factor(Prostate_data_comb$Type)

Prostate_beta_plots_time4 <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Prostate_data_comb, facet="Type", covariate = NULL,
                                                       main_variable = "Case.Control")
saveRDS(Prostate_beta_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_prostate_beta_time4.RDS")

```

```{r}
Pr_unadjusted_stat <- list()
Pr_adjusted_stat_age <- list()
Pr_adjusted_stat <- list()


#need to filter metadata so that it only has samples that are fully complete...

Prostate_data_comb_noNA <- Prostate_data_comb[-which(is.na(Prostate_data_comb$Comb_Height)),]

Prostate_data_comb_noNA <- Prostate_data_comb_noNA[-which(is.na(Prostate_data_comb_noNA$Comb_Veg)),]

Prostate_data_comb_noNA <- Prostate_data_comb_noNA[-which(is.na(Prostate_data_comb_noNA$Comb_WHR)),]

table(Prostate_data_comb$Case.Control)
table(Prostate_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  Pr_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Pr_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Pr_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_all)
  
  
  
}

names(Pr_unadjusted_stat)
Pr_unadjusted_stat

names(Pr_adjusted_stat_age)
Pr_adjusted_stat_age

names(Pr_adjusted_stat)
Pr_adjusted_stat
```

```{r}
CRC_data_comb <- Combined_data_filt %>% filter(Type=="Colon")
CRC_data_comb$Case.Control_type <- CRC_data_comb$Case.Control
CRC_data_comb$Type <- factor(CRC_data_comb$Type)

CRC_beta_plots_time4 <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=CRC_data_comb, facet="Type", covariate = NULL,
                                                  main_variable = "Case.Control")

saveRDS(CRC_beta_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_CRC_beta_time4.RDS")
```

```{r}
CRC_unadjusted_stat <- list()
CRC_adjusted_stat_age <- list()
CRC_adjusted_stat <- list()

#need to filter metadata so that it only has samples that are fully complete...
CRC_data_comb_noNA <- CRC_data_comb[-which(is.na(CRC_data_comb$Comb_Height)),]

CRC_data_comb_noNA <- CRC_data_comb_noNA[-which(is.na(CRC_data_comb_noNA$Comb_WHR)),]

table(CRC_data_comb$Case.Control)
table(CRC_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  CRC_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  CRC_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  CRC_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_all)
  
  
  
}

names(CRC_unadjusted_stat)
CRC_unadjusted_stat

CRC_adjusted_stat_age


CRC_adjusted_stat
```

#time vs. alpha

```{r}
Combined_data %>% filter(Case.Control=="control", Type=="Breast") %>% summarize(mean(faith_pd))
Combined_data %>% filter(Case.Control=="control", Type=="Prostate") %>% summarize(mean(faith_pd))
Combined_data %>% filter(Case.Control=="control", Type=="Colon") %>% summarize(mean(faith_pd))

Case_samples <- Combined_data %>% filter(Case.Control=="case")

Case_samples$mean_faith <- 10.104
Case_samples$mean_faith[which(Case_samples$Type=="Prostate")] <- 10.648
Case_samples$mean_faith[which(Case_samples$Type=="Colon")] <- 10.200



faiths_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=faith_pd)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_faith), color="red", linetype="dashed") +
  ylab("Faith's Phylogenetic Diversity") + xlab("Time since diagnosis") +
  theme_cowplot()
faiths_cor_data

Combined_data %>% filter(Case.Control=="control", Type=="Breast") %>% summarize(mean(observed_features))
Combined_data %>% filter(Case.Control=="control", Type=="Prostate") %>% summarize(mean(observed_features))
Combined_data %>% filter(Case.Control=="control", Type=="Colon") %>% summarize(mean(observed_features))

Case_samples$mean_rich <- 97.976
Case_samples$mean_rich[which(Case_samples$Type=="Prostate")] <- 100.484
Case_samples$mean_rich[which(Case_samples$Type=="Colon")] <- 95.636


richness_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=observed_features)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_rich), color="red", linetype="dashed") +
  ylab("Richness") + xlab("Time since diagnosis") + theme_cowplot()


Combined_data %>% filter(Case.Control=="control", Type=="Breast") %>% summarize(mean(shannon_entropy))
Combined_data %>% filter(Case.Control=="control", Type=="Prostate") %>% summarize(mean(shannon_entropy))
Combined_data %>% filter(Case.Control=="control", Type=="Colon") %>% summarize(mean(shannon_entropy))

Case_samples$mean_shannon <- 4.257
Case_samples$mean_shannon[which(Case_samples$Type=="Prostate")] <- 4.349
Case_samples$mean_shannon[which(Case_samples$Type=="Colon")] <- 4.268

shannon_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=shannon_entropy)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_shannon), color="red", linetype="dashed") +
  ylab("Shannon Diversity") + xlab("Time since diagnosis") + theme_cowplot()


Combined_data %>% filter(Case.Control=="control", Type=="Breast") %>% summarize(mean(pielou_evenness))
Combined_data %>% filter(Case.Control=="control", Type=="Prostate") %>% summarize(mean(pielou_evenness))
Combined_data %>% filter(Case.Control=="control", Type=="Colon") %>% summarize(mean(pielou_evenness))


Case_samples$mean_even <- 0.647
Case_samples$mean_even[which(Case_samples$Type=="Prostate")] <- 0.658
Case_samples$mean_even[which(Case_samples$Type=="Colon")] <- 0.651


even_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=pielou_evenness)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_even), color="red", linetype="dashed") +
  ylab("Evenness") + xlab("Time since diagnosis") + theme_cowplot()

```


```{r}
cor_plot_fin <- plot_grid(faiths_cor_data, richness_cor_data, shannon_cor_data, even_cor_data)
cor_plot_fin

ggsave("~/Private/CHAPTER_4/Revised_Figures/Display_items/Supplemental/ATP_Pro_alpha_cor.pdf",
       width=9, height=9)

```

```{r}
Breast_case <- Case_data %>% filter(Type=="Breast")

cor.test(Breast_case$age_diff, Breast_case$faith_pd, method="spearman")
cor.test(Breast_case$age_diff, Breast_case$pielou_evenness, method="spearman")
cor.test(Breast_case$age_diff, Breast_case$shannon_entropy, method="spearman")
cor.test(Breast_case$age_diff, Breast_case$observed_features, method="spearman")
```

```{r}
Prostate_case <- Case_data %>% filter(Type=="Prostate")

cor.test(Prostate_case$age_diff, Prostate_case$faith_pd, method="spearman")
cor.test(Prostate_case$age_diff, Prostate_case$pielou_evenness, method="spearman")
cor.test(Prostate_case$age_diff, Prostate_case$shannon_entropy, method="spearman")
cor.test(Prostate_case$age_diff, Prostate_case$observed_features, method="spearman")



```


```{r}
Colon_case <- Case_data %>% filter(Type=="Colon")

cor.test(Colon_case$age_diff, Colon_case$faith_pd, method="spearman")
cor.test(Colon_case$age_diff, Colon_case$pielou_evenness, method="spearman")
cor.test(Colon_case$age_diff, Colon_case$shannon_entropy, method="spearman")
cor.test(Colon_case$age_diff, Colon_case$observed_features, method="spearman")
```