---
title: "Metadata_Analysis"
author: "Jacob T. Nearing"
date: "6/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(dplyr)
library(reshape2)

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls\n"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

### test case for above function

test_df <- data.frame(CaseID = c(paste0(seq(1,100), "ID"), paste0(seq(1,100), "ID")),
                      Case.Control=c(rep("case", 100), rep("control",100)))

test_res <- remove_non_matching_caseIDS(test_df)

#lets remove CaseID 1
test_df <- test_df[-1,]

test_res <- remove_non_matching_caseIDS(test_df)
table(test_res$CaseID)

#that works. Lets now remove some controls and cases
test_df[c(102,5,87,192),]

test_df <- test_df[-c(102, 5, 87, 192),]
table(test_df$Case.Control)
which(table(test_df$CaseID)==1)

test_res <- remove_non_matching_caseIDS(test_df)
table(test_res$Case.Control)
table(test_res$CaseID)
which(table(test_res$CaseID)==1)

#this function works as expected.

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}


#test above function

test_df <- data.frame(CaseID = c(paste0(seq(1,100), "ID"), paste0(seq(1,100), "ID")),
                      Case.Control=c(rep("case", 100), rep("control",100)),
                      age_diff=c(rnorm(100, mean=5, sd=1), rep(NA, 100)))

matching_age <- match_age_diff(test_df)
table(matching_age$age_diff)
which(table(matching_age$age_diff)==1)

## double check that they are correctly matched
identical(matching_age$age_diff[1:100], matching_age$age_diff[101:200])

## this function works as expected.
```


```{r}
base_metadata <- readRDS("~/Private/ATP/Metadata/Base_microbiome_metadata.RDS")
base_metadata$ParticipantKey <- as.character(base_metadata$ParticipantKey)
rownames(base_metadata) <- base_metadata$researcher



sheet_names <- c("ACR", "ACR_Treatment", "Core", "Core_Chronic", "HLQ", "Master_Data", "Case_Control_Match", "PANS", "PM_data", "UHLQ", "UHLQ_Cond")

Metadata <- list()

for(i in 1:length(sheet_names)){
  
  Metadata[[sheet_names[i]]] <- read_excel("~/Private/ATP/Metadata/ATP_MASTER_DATA.xls", sheet=i)
  
}

Metadata[["Age_casetype"]] <- read_excel("~/Private/ATP/Metadata/SalivaAge_Groupings_2021-12-06.xlsx")

Metadata[[7]]$matchID <- seq(1:207)

case_control_match <- melt(Metadata[[7]][,-3], id.vars = 'matchID')



Shannon_div <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/shannon.tsv",
                          sep="\t", header=T)
colnames(Shannon_div)[1] <- "researcher"

#faith pd
faith_pd <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/faiths_pd.tsv",
                       sep="\t", header=T)
colnames(faith_pd)[1] <- "researcher"

#raw richness
richness <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/observed_feats.tsv",
                       sep="\t", header=T)
colnames(richness)[1] <- "researcher"

#evenness
evenness <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/evenness.tsv",
                       sep="\t", header=T)
colnames(evenness)[1] <- "researcher"


## remove samples that didn't sequence well.
Alpha_div <- Shannon_div %>% left_join(faith_pd, by="researcher") %>% left_join(richness, by="researcher") %>% left_join(evenness, by="researcher")


Full_data <- Alpha_div %>% inner_join(base_metadata, by="researcher")
Full_data$Case.Control <- factor(Full_data$ARM.x, levels=c("control", "case"))



### I need to scan through the core data and see which are within 1 year of the saliva age
Metadata[["Core"]]$ParticipantKey <- as.character(Metadata[["Core"]]$ParticipantKey)

Full_data <- Full_data %>% left_join(Metadata[["Core"]][,c("ParticipantKey",
                                                           "CORE_AGE_AT_SURVEY_RECEIPT")])

Full_data$use_core <- abs(Full_data$`SALIVA AGE` - Full_data$CORE_AGE_AT_SURVEY_RECEIPT) <= 1

Metadata[["PANS"]]$ParticipantKey <- as.character(Metadata[["PANS"]]$ParticipantKey)

Full_data <- Full_data %>% left_join(Metadata[["PANS"]][,c("ParticipantKey", "PANS_AGE_AT_SURVEY_RECEIPT")])

Full_data$use_PANS <- abs(Full_data$`SALIVA AGE` - Full_data$PANS_AGE_AT_SURVEY_RECEIPT) <= 1


#all the ones with PANS data can be used.

Metadata[["PM_data"]]$ParticipantKey <- as.character(Metadata[["PM_data"]]$ParticipantKey)

Full_data <- Full_data %>% left_join(Metadata[["PM_data"]][,c("ParticipantKey",
                                                              "PM_AGE_AT_PM")])

Full_data$use_PM <- abs(Full_data$`SALIVA AGE` - Full_data$PM_AGE_AT_PM) <= 3



Metadata[["UHLQ"]]$ParticipantKey <- as.character(Metadata[["UHLQ"]]$ParticipantKey)

Full_data <- Full_data %>% left_join(Metadata[["UHLQ"]][,c("ParticipantKey",
                                                           "UHLQ_AGE_AT_SURVEY_RECEIPT")])

Full_data$use_UHLQ <- abs(Full_data$`SALIVA AGE` - Full_data$UHLQ_AGE_AT_SURVEY_RECEIPT) <= 1


CORE_data <- Metadata[["Core"]][,c("ParticipantKey", "CORE_SMK_STATUS", 
                                   "CORE_BMI", "CORE_AVG_HEIGHT", 
                                   "CORE_AVG_HIP", "CORE_AVG_ABDOMEN",
                                   "CORE_FC01_VEG_DAY_NUM")]

CORE_data$WAIST_HIP_RATIO <- CORE_data$CORE_AVG_ABDOMEN/CORE_data$CORE_AVG_HIP



## okay now we get the list of participants that have core data within a year.
Core_participants <- Full_data$ParticipantKey[which(Full_data$use_core==T)]

CORE_data <- CORE_data %>% filter(ParticipantKey %in% Core_participants)

Full_data <- Full_data %>% left_join(CORE_data)

#first filter to make sure they are within a year
Missing_PM_data <- Full_data %>% filter(use_PM==T)

#now get keys that are missing core data for biometrics
Missing_PM_data <- Missing_PM_data$ParticipantKey[is.na(Missing_PM_data$CORE_AVG_HIP)]

## okay now we need to get the samples without the CORE data are fill them in with the other participant data.

PM_data <- Metadata[["PM_data"]] %>% 
  filter(ParticipantKey %in% Missing_PM_data) %>% 
  select(PM_BIOIMPED_BMI, PM_WAIST_HIP_RATIO, PM_STANDING_HEIGHT_AVG, ParticipantKey)

Missing_SMK <- Full_data %>% filter(use_UHLQ)
Missing_SMK <- Missing_SMK$ParticipantKey[which(is.na(Missing_SMK$CORE_SMK_STATUS))]

UHLQ_Data <- Metadata[["UHLQ"]] %>%
  filter(ParticipantKey %in% Missing_SMK) %>%
  select(UHLQ_SMK_STATUS, ParticipantKey)


Missing_Veg <- Full_data %>% filter(use_PANS==T)
Missing_Veg <- Missing_Veg$ParticipantKey[which(is.na(Missing_Veg$CORE_FC01_VEG_DAY_NUM))]

Veg_data <- Metadata[["PANS"]] %>%
  filter(ParticipantKey %in% Missing_Veg) %>%
  select(PANS_NT_1, ParticipantKey)


Full_data <- Full_data %>% left_join(PM_data) %>% left_join(UHLQ_Data) %>% left_join(Veg_data)

#need to combined data now...
#take CORE and then fill in the rest as needed...

Full_data$Comb_BMI <- Full_data$CORE_BMI
missing_BMI <- which(is.na(Full_data$Comb_BMI))
Full_data$Comb_BMI[missing_BMI] <- Full_data$PM_BIOIMPED_BMI[missing_BMI]


Full_data$Comb_WHR <- Full_data$WAIST_HIP_RATIO
missing_WHR <- which(is.na(Full_data$WAIST_HIP_RATIO))
Full_data$Comb_WHR[missing_WHR] <- Full_data$PM_WAIST_HIP_RATIO[missing_WHR]


Full_data$Comb_Height <- Full_data$CORE_AVG_HEIGHT
missing_height <- which(is.na(Full_data$Comb_Height))
Full_data$Comb_Height[missing_height] <- Full_data$PM_STANDING_HEIGHT_AVG[missing_height]

Full_data$Comb_Veg <- Full_data$CORE_FC01_VEG_DAY_NUM
missing_veg <- which(is.na(Full_data$Comb_Veg))
Full_data$Comb_Veg[missing_veg] <- Full_data$PANS_NT_1[missing_veg]

Full_data$Comb_SMK <- Full_data$CORE_SMK_STATUS
missing_SMK <- which(is.na(Full_data$Comb_SMK))
Full_data$Comb_SMK[missing_SMK] <- Full_data$UHLQ_SMK_STATUS[missing_SMK]


Metadata_sex <- Metadata[["Master_Data"]][,c("ParticipantKey", "PARTICIPANT_SEX")]
Metadata_sex$ParticipantKey <- as.character(Metadata_sex$ParticipantKey)

Full_data <- Full_data %>% left_join(Metadata_sex)

```

```{r}
#filter to individual cancer types
Alpha_Breast <- Full_data %>% filter(Type=="Breast")
Alpha_Prostate <- Full_data %>% filter(Type=="Prostate")
Alpha_CRC <- Full_data %>% filter(Type=="Colon") 

#rename sample id column
Alpha_Breast$X <- Alpha_Breast$researcher
Alpha_Prostate$X <- Alpha_Prostate$researcher
Alpha_CRC$X <- Alpha_CRC$researcher

#add caseIDs (so we know the matching case and control samples)
Alpha_Breast$CaseID <- case_control_match$matchID[match(Alpha_Breast$ParticipantKey, case_control_match$value)]

Alpha_Prostate$CaseID <- case_control_match$matchID[match(Alpha_Prostate$ParticipantKey, case_control_match$value)]

Alpha_CRC$CaseID <- case_control_match$matchID[match(Alpha_CRC$ParticipantKey, case_control_match$value)]

#remove cases or controls that do not have corresponding case/control samples
Alpha_Breast <- remove_non_matching_caseIDS(Alpha_Breast)
Alpha_Prostate <- remove_non_matching_caseIDS(Alpha_Prostate)
Alpha_CRC <- remove_non_matching_caseIDS(Alpha_CRC)


Combined_data <- rbind(Alpha_Breast, Alpha_Prostate, Alpha_CRC)

saveRDS(Combined_data, "~/Private/CHAPTER_4/Revised_data/Combined_data_ATP_Pro.RDS")


Case_data_filt <- Combined_data %>% filter(Case.Control=="case") %>% filter(age_diff <= 4)

Case_time_keep <- Case_data_filt$CaseID

Combined_data_filt <- Combined_data %>% filter(CaseID %in% Case_time_keep)

saveRDS(Combined_data_filt, "~/Private/CHAPTER_4/Revised_data/Combined_data_ATP_Pro_filt.RDS")
```

# Breast Cancer

```{r}
Alpha_Breast %>% group_by(Case.Control) %>% summarize(n())

Alpha_Breast %>% group_by(Case.Control) %>% summarize(mean(`SALIVA AGE`))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(sd(`SALIVA AGE`))
t.test(Alpha_Breast$`SALIVA AGE` ~ Alpha_Breast$Case.Control)


Alpha_Breast %>% group_by(Case.Control) %>% summarize(median(age_diff))


Alpha_Breast %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_BMI))))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(mean(Comb_BMI, na.rm=T))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(sd(Comb_BMI, na.rm=T))
t.test(Alpha_Breast$Comb_BMI ~ Alpha_Breast$Case.Control)

Alpha_Breast %>% group_by(Case.Control, Comb_SMK) %>% summarize(n())


Alpha_Breast %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_WHR))))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(mean(Comb_WHR, na.rm=T))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(sd(Comb_WHR, na.rm=T))
t.test(Alpha_Breast$Comb_WHR ~ Alpha_Breast$Case.Control)


Alpha_Breast %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_Veg))))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(mean(Comb_Veg, na.rm=T))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(sd(Comb_Veg, na.rm=T))
t.test(Alpha_Breast$Comb_Veg ~ Alpha_Breast$Case.Control)

Alpha_Breast %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_Height))))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(mean(Comb_Height, na.rm=T))
Alpha_Breast %>% group_by(Case.Control) %>% summarize(sd(Comb_Height, na.rm=T))
t.test(Alpha_Breast$Comb_Height ~ Alpha_Breast$Case.Control)

```


# Prostate Cancer

```{r}
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(n())

Alpha_Prostate %>% group_by(Case.Control) %>% summarize(mean(`SALIVA AGE`))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(sd(`SALIVA AGE`))
t.test(Alpha_Prostate$`SALIVA AGE` ~ Alpha_Prostate$Case.Control)

Alpha_Prostate %>% group_by(Case.Control) %>% summarize(median(age_diff))

Alpha_Prostate %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_BMI))))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(mean(Comb_BMI, na.rm=T))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(sd(Comb_BMI, na.rm=T))
t.test(Alpha_Prostate$Comb_BMI ~ Alpha_Prostate$Case.Control)


Alpha_Prostate %>% group_by(Case.Control, CORE_SMK_STATUS) %>% summarize(n())


Alpha_Prostate %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_WHR))))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(mean(Comb_WHR, na.rm=T))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(sd(Comb_WHR, na.rm=T))
t.test(Alpha_Prostate$Comb_WHR ~ Alpha_Prostate$Case.Control)


Alpha_Prostate %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_Veg))))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(mean(Comb_Veg, na.rm=T))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(sd(Comb_Veg, na.rm=T))
t.test(Alpha_Prostate$Comb_Veg ~ Alpha_Prostate$Case.Control)

Alpha_Prostate %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_Height))))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(mean(Comb_Height, na.rm=T))
Alpha_Prostate %>% group_by(Case.Control) %>% summarize(sd(Comb_Height, na.rm=T))
t.test(Alpha_Prostate$Comb_Height ~ Alpha_Prostate$Case.Control)
```


# Colon Cancer

```{r}
Alpha_CRC %>% group_by(Case.Control) %>% summarize(n())

Alpha_CRC %>% group_by(Case.Control) %>% summarize(mean(`SALIVA AGE`))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(sd(`SALIVA AGE`))
t.test(Alpha_CRC$`SALIVA AGE` ~ Alpha_CRC$Case.Control)

Alpha_CRC %>% group_by(Case.Control) %>% summarize(median(age_diff))

Alpha_CRC %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_BMI))))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(mean(Comb_BMI, na.rm=T))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(sd(Comb_BMI, na.rm=T))
t.test(Alpha_CRC$Comb_BMI ~ Alpha_CRC$Case.Control)

Alpha_CRC %>% group_by(Case.Control, CORE_SMK_STATUS) %>% summarize(n())

Alpha_CRC %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_WHR))))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(mean(Comb_WHR, na.rm=T))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(sd(Comb_WHR, na.rm=T))
t.test(Alpha_CRC$Comb_WHR ~ Alpha_CRC$Case.Control)


Alpha_CRC %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_Veg))))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(mean(Comb_Veg, na.rm=T))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(sd(Comb_Veg, na.rm=T))
t.test(Alpha_CRC$Comb_Veg ~ Alpha_CRC$Case.Control)

Alpha_CRC %>% group_by(Case.Control) %>% summarize(length(which(is.na(Comb_Height))))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(mean(Comb_Height, na.rm=T))
Alpha_CRC %>% group_by(Case.Control) %>% summarize(sd(Comb_Height, na.rm=T))
t.test(Alpha_CRC$Comb_Height ~ Alpha_CRC$Case.Control)
```

# save metadata that can be released
```{r}
ATP_pro_metadata <- rbind(Alpha_Breast, Alpha_CRC)
ATP_pro_metadata <- rbind(ATP_pro_metadata, Alpha_Prostate)


ATP_pro_metadata <- ATP_pro_metadata %>% select(X, Case.Control, Type, shannon_entropy, faith_pd, observed_features, pielou_evenness, CaseID, CANCER_SITE.x, PARTICIPANT_SEX, age_diff)
# table with full metadata
# double check ethics if this can be released.
write.table(x=ATP_pro_metadata, file="~/Private/CHAPTER_4/Cleaned_Repo_D1/Data/Prospective/ATP_metadata_with_extra.csv",
           col.names=NA, row.names=T, quote=F, sep=",")

```

```{r}
samp_names <- ATP_pro_metadata %>% select(X)
write.table(samp_names, file="~/Private/CHAPTER_4/UPLOAD_Data/ATP_pro_samps.txt", col.names = NA, quote=F, sep=" ")
```