---
title: "Prospective_Figures"
author: "Jacob T. Nearing"
date: "3/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(broom)
library(kableExtra)
library(ggplot2)
library(ggbeeswarm)
library(cowplot)

library(reshape2)
library(ggpubr)
library(rstatix)
library(vegan)

theme_set(theme_cowplot())


remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}

run_lm_comb_data <- function(data, type_split, main_variable, covariates, estimate_var){
  
  anova_res <- list()
  ggpubr_res <- list()
  
  for(i in unique(data[,type_split])){
    pass_in_data <- data %>% filter(!!sym(type_split)==i)
    
    res <- run_lm_add_using_ggplot(pass_in_data, main_variable = main_variable, covariates = covariates,
                            estimate_var = estimate_var, fct=i, type_split)
    anova_res[[i]] <- res[[1]]
    ggpubr_res[[i]] <- res[[2]]
  }
  ggpurb_df <- do.call(rbind, ggpubr_res)
  
  return(list(anova_res, ggpurb_df))
  
}

run_lm_add_using_ggplot <- function(data, main_variable, covariates, estimate_var, fct, type_split){
    
  
    formula <- paste(covariates, main_variable, sep=" + ")
    final_formula <- paste(estimate_var, "~", formula, sep=" ")
    message(final_formula)
    model <- lm(final_formula, data)
    anova_res <- anova(model)
    anova_res$feat <- rownames(anova_res)
    anova_filt <- anova_res %>% filter(feat==main_variable)
    pval <- anova_filt$`Pr(>F)`
    
    if(is.null(fct)){
      ggpurb_format <- data.frame(group1=levels(data[,main_variable])[1],
                                group2=levels(data[,main_variable])[2],
                                p.adj=pval)
    }else{
      ggpurb_format <- data.frame(group1=levels(data[,main_variable])[1],
                                group2=levels(data[,main_variable])[2],
                                p.adj=round(pval,3),
                                supp=fct,
                                .y.=max(data[,estimate_var])*1.02)
      
      colnames(ggpurb_format)[4] <- type_split
      
    }
    
    return(list(anova_res, ggpurb_format))
}


make_alpha_div_plot <- function(df, split_type, main_variable, covariates, estimate_var,ylab,pval=T,hide.ns){
  
  stats <- run_lm_comb_data(data=df, type_split = split_type, main_variable = main_variable,
                                        covariates = covariates, estimate_var = estimate_var)
  
  plot <- ggplot(df, aes_string(x=main_variable, y=estimate_var)) +
  geom_boxplot(alpha=0.1, width=0.1, outlier.alpha = 0) +
  geom_violin(alpha=0.2, aes_string(fill=main_variable)) +
  geom_quasirandom(alpha=0.2) +
  xlab("") +
  ylab(ylab) +
  facet_grid(reformulate(split_type))

  if(pval==T){
    plot <- plot + stat_pvalue_manual(stats[[2]], label="p.adj", hide.ns=hide.ns, y.position = '.y.')
  }
  
  return(plot)
}

make_all_alpha_div_plots <- function(df, split_type, main_variable, covariates, estimate_var, ylab, pval=T, hide.ns=T){
  plot_list <- list()
  j <- 1
  for(i in ylab){
    plot_list[[i]] <- make_alpha_div_plot(df, split_type, main_variable, covariates, estimate_var[j], i, pval,hide.ns)
    j <- j + 1
  }
  return(plot_list)
  
}
```


# PATH
```{r}
Metadata_Breast <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_Breast.RDS")
Metadata_Breast$Case_Control <- as.character(Metadata_Breast$`Case/Control`)
Metadata_Prostate <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_Prostate.RDS")
Metadata_Prostate$Case_Control <- as.character(Metadata_Prostate$`Case/Control`)
Metadata_CRC <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_CRC.RDS")
Metadata_CRC$Case_Control <- as.character(Metadata_CRC$`Case/Control`)

Metadata_Breast$Case.Control <- ifelse(Metadata_Breast$`CASE/CONTROL`==1, "Case", "Control")
Metadata_Prostate$Case.Control <- ifelse(Metadata_Prostate$`CASE/CONTROL`==1, "Case", "Control")
Metadata_CRC$Case.Control <- ifelse(Metadata_CRC$`CASE/CONTROL`==1, "Case", "Control")

Metadata_Breast$Case.Control <- factor(Metadata_Breast$Case.Control, levels=c("Control", "Case"))
Metadata_Prostate$Case.Control <- factor(Metadata_Prostate$Case.Control, levels=c("Control", "Case"))
Metadata_CRC$Case.Control <- factor(Metadata_CRC$Case.Control, levels=c("Control", "Case"))

Faiths <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/faiths/alpha-diversity.tsv",
                     header=T, row.names=1)
Evenness <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/evenness/alpha-diversity.tsv",
                        header=T, row.names = 1)

Richness <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/richness/alpha-diversity.tsv", 
                       header=T, row.names = 1)

Shannon <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/shannon/alpha-diversity.tsv",
                      header=T, row.names = 1)

Alpha_data <- cbind(Faiths, Evenness, Richness, Shannon)

Alpha_data$`Saliva ID Ship` <- rownames(Alpha_data)

Alpha_Breast <- Alpha_data %>% inner_join(Metadata_Breast, by="Saliva ID Ship")
Alpha_Prostate <- Alpha_data %>% inner_join(Metadata_Prostate, by="Saliva ID Ship")
Alpha_CRC  <- Alpha_data %>% inner_join(Metadata_CRC, by="Saliva ID Ship")

Alpha_Breast$X <- Alpha_Breast$`Saliva ID Ship`
Alpha_Prostate$X <- Alpha_Prostate$`Saliva ID Ship`
Alpha_CRC$X <- Alpha_CRC$`Saliva ID Ship`

Alpha_Breast$age_diff <- Alpha_Breast$F1_DIS_CANCER1_AGE - Alpha_Breast$SDC_AGE_CALC
Alpha_Prostate$age_diff <- Alpha_Prostate$F1_DIS_CANCER1_AGE - Alpha_Prostate$SDC_AGE_CALC
Alpha_CRC$age_diff <- Alpha_CRC$F1_DIS_CANCER1_AGE - Alpha_CRC$SDC_AGE_CALC

Alpha_Breast$Type <- "Breast"
Alpha_Prostate$Type <- "Prostate"
Alpha_CRC$Type <- "Colon"

Alpha_Breast <- remove_non_matching_caseIDS(Alpha_Breast)
Alpha_Prostate <- remove_non_matching_caseIDS(Alpha_Prostate)
Alpha_CRC <- remove_non_matching_caseIDS(Alpha_CRC)

Breast_data_comb <- Alpha_Breast %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID, PM_WAIST_HIP_RATIO, PM_STANDING_HEIGHT_AVG, SDC_AGE_CALC, SDC_GENDER, NUT_VEG_QTY, PM_BIOIMPED_BMI)

Prostate_data_comb <- Alpha_Prostate %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID, PM_WAIST_HIP_RATIO, PM_STANDING_HEIGHT_AVG, SDC_AGE_CALC, SDC_GENDER, NUT_VEG_QTY, PM_BIOIMPED_BMI)

CRC_data_comb <- Alpha_CRC %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID, PM_WAIST_HIP_RATIO, PM_STANDING_HEIGHT_AVG, SDC_AGE_CALC, SDC_GENDER, NUT_VEG_QTY, PM_BIOIMPED_BMI)


Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)


Case_data_filt <- Combined_data %>% filter(Case.Control=="Case") %>% filter(age_diff <= 4)

Case_time_keep <- Case_data_filt$CaseID

Combined_data_filt <- Combined_data %>% filter(CaseID %in% Case_time_keep)

saveRDS(Combined_data, "~/Private/CHAPTER_4/Revised_data/Combined_data_PATH_Pro.RDS")
saveRDS(Combined_data_filt, "~/Private/CHAPTER_4/Revised_data/Combined_data_filt_PATH_Pro.RDS")
```

# Alpha Div

### No Time filt

```{r}
est_vars <- c("faith_pd", "shannon_entropy", "pielou_evenness", "observed_features")
ylabs <- c("Faith's PD", "Shannon Div.", "Evenness", "Richness")

all_cancer_plots <- make_all_alpha_div_plots(df=Combined_data, split_type = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars, ylab=ylabs, hide.ns = T)


saveRDS(all_cancer_plots, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_alpha_all.RDS")

Sup_fig_alpha <- plot_grid(all_cancer_plots[[1]] + theme(legend.position = "none"),
                           #all_cancer_plots[[2]] + theme(legend.position = "none"),
                           all_cancer_plots[[3]] + theme(legend.position = "none"),
                           #all_cancer_plots[[4]] + theme(legend.position = "none"),
                           nrow=2)

Sup_fig_alpha_leg <- plot_grid(Sup_fig_alpha, 
                               get_legend(all_cancer_plots[[1]]),
                               nrow=1,
                               rel_widths = c(1,.1))

Sup_fig_alpha_leg


all_cancer_plots <- make_all_alpha_div_plots(df=Combined_data, split_type = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars, ylab=ylabs, pval=F)

saveRDS(all_cancer_plots, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_alpha_all_no_p.RDS")
```


### Adjusted models

```{r}
est_vars <- c("faith_pd", "observed_features", "shannon_entropy", "pielou_evenness")

covar_stat_res <- list()
covar_stat_res_age <- list()
unadjusted_res <- list()

covars_age <- "SDC_AGE_CALC + SDC_GENDER"
covars <- "SDC_AGE_CALC + PM_STANDING_HEIGHT_AVG + PM_WAIST_HIP_RATIO + SDC_GENDER + NUT_VEG_QTY"

for(i in est_vars){
  
  covar_stat_res[[i]] <- run_lm_comb_data(data=Combined_data, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars, 
                                     estimate_var = i)
  covar_stat_res_age[[i]] <- run_lm_comb_data(data=Combined_data, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars_age, 
                                     estimate_var = i)
  
  unadjusted_res[[i]] <- run_lm_comb_data(data=Combined_data, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = NULL, 
                                     estimate_var = i)
}



unadjusted_res

covar_stat_res_age

covar_stat_res

```


### Time Filter

Within 4 years after sample collection

```{r}
all_cancer_plots_time4 <- make_all_alpha_div_plots(df=Combined_data_filt, split_type = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars, ylab=ylabs)


Sup_alpha_filt <- plot_grid(all_cancer_plots_time4[[1]] + theme_cowplot() + theme(legend.position = "none"),
                            all_cancer_plots_time4[[2]] + theme_cowplot() + theme(legend.position = "none"),
                            all_cancer_plots_time4[[3]] + theme_cowplot() + theme(legend.position = "none"),
                            all_cancer_plots_time4[[4]] + theme_cowplot() + theme(legend.position = "none"),
                            nrow=4)


Sup_alpha_filt_leg <- plot_grid(Sup_alpha_filt, 
                                get_legend(all_cancer_plots_time4),
                                nrow=1,
                                rel_widths = c(1, .1))

Sup_alpha_filt_leg

saveRDS(all_cancer_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_alpha_all_time4.RDS")

all_cancer_plots_time4 <- make_all_alpha_div_plots(df=Combined_data_filt, split_type = "Type", main_variable = "Case.Control", covariates = NULL, estimate_var = est_vars, ylab=ylabs,
                                                   pval=F)
saveRDS(all_cancer_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_alpha_all_time4_no_p.RDS")
```

### adjusted

```{r}
filt_covar_stat_res <- list()
filt_covar_stat_res_age <- list()
filt_unadjusted_res <- list()

for(i in est_vars){
  filt_covar_stat_res[[i]] <- run_lm_comb_data(data=Combined_data_filt, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars, 
                                     estimate_var = i)
  
    filt_covar_stat_res_age[[i]] <- run_lm_comb_data(data=Combined_data_filt, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = covars_age, 
                                     estimate_var = i)
    
    filt_unadjusted_res[[i]] <- run_lm_comb_data(data=Combined_data_filt, type_split = "Type", main_variable = "Case.Control",  
                                     covariates = NULL, 
                                     estimate_var = i)
}


filt_unadjusted_res

filt_covar_stat_res_age

filt_covar_stat_res
```


## Beta Diversity

```{r}
WEIGHTED_UNIFRAC <- "~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_beta/weighted_unifrac/distance-matrix.tsv"
BRAY_CURTIS <- "~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_beta/bray_curt/distance-matrix.tsv"
UNWEIGHTED_UNIFRAC <- "~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_beta/unweighted_unifrac/distance-matrix.tsv"
RPCA <- "~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_beta/rpca/rpca_distance.tsv"

w_unifrac <- read.table(WEIGHTED_UNIFRAC, sep="\t", header=T, row.names = 1, comment.char="", quote="", check.names = F)

bray_curt <- read.table(BRAY_CURTIS, sep="\t", header=T, row.names = 1, comment.char = "", quote="", check.names = F)

u_unifrac <- read.table(UNWEIGHTED_UNIFRAC, sep="\t", header=T, row.names = 1, comment.char="", quote="", check.names = F)

rpca <- read.table(RPCA, sep="\t", header=T, row.names=1, comment.char="", quote="", check.names = F)

Combined_data$Case.Control_type <- as.character(Combined_data$Case.Control)

Combined_data$Case.Control_type[which(Combined_data$Case.Control_type=="Case")] <- Combined_data$Type[which(Combined_data$Case.Control=="Case")]


Combined_data_filt$Case.Control_type <- as.character(Combined_data_filt$Case.Control)

Combined_data_filt$Case.Control_type[which(Combined_data_filt$Case.Control_type=="Case")] <- Combined_data_filt$Type[which(Combined_data_filt$Case.Control=="Case")]
```

### All in one

#### no time filt
```{r}
weighted_uni_comb <- w_unifrac[Combined_data$X, Combined_data$X]
unweighted_uni_comb <- u_unifrac[Combined_data$X, Combined_data$X]
bray_comb <- bray_curt[Combined_data$X, Combined_data$X]
rpca_comb <- rpca[Combined_data$X, Combined_data$X]
```

```{r}
plot_pca_all <- function(dist, meta, title, facet_type=NULL){
  
  dist_filt <- dist[meta$X, meta$X]
  
  dist_pca <- cmdscale(dist_filt, eig=T)
  
  dist_plot_data <- data.frame(PC1=dist_pca$points[,1],
                               PC2=dist_pca$points[,2],
                               Case.Control=meta$Case.Control_type,
                               facet=meta[,facet_type])
  PC1_size <- round(dist_pca$eig[1]/sum(dist_pca$eig)*100,1)
  PC2_size <- round(dist_pca$eig[2]/sum(dist_pca$eig)*100,1)
  
  PC1_lab <- paste0("PC1 ", PC1_size, "%")
  PC2_lab <- paste0("PC2 ", PC2_size, "%")
  
  if(!is.null(facet_type)){
    dist_plot <- ggplot(dist_plot_data, aes(x=PC1, y=PC2)) +
      geom_point(aes(fill=Case.Control, color=Case.Control)) +
      stat_ellipse(aes(group=Case.Control, color=Case.Control)) +
      theme(legend.title = element_blank()) +
      xlab(PC1_lab) +
      ylab(PC2_lab) +
      ggtitle(title) +
      facet_grid(~ facet)
    
    return(dist_plot)
    
  }else{
      
  dist_plot <- ggplot(dist_plot_data, aes(x=PC1, y=PC2, fill=Case.Control, group=Case.Control, color=Case.Control)) +
    geom_point() +
    stat_ellipse() +
    theme(legend.title = element_blank()) +
    xlab(PC1_lab) +
    ylab(PC2_lab) +
    ggtitle(title)
  
  return(dist_plot)
    
  }

}


run_adonis_by_facet <- function(dist, meta, facet, covariates, main_variable){
  
  formula <- paste(covariates, main_variable, sep=" + ")
  final_formula <- as.formula(paste("temp_dist", formula, sep="~"))
  message(final_formula)
  message(facet)
  meta_splits <- group_split(meta, !!ensym(facet))
  adonis_res <- list()

  for(i in 1:length(meta_splits)){
    name <- as.character(meta_splits[[i]][1,facet,drop=T])
    message(name)
    samps <- as.data.frame(meta_splits[[i]][,"X"])
    temp_dist <- dist[samps$X, samps$X]
    message("running adonis")
    
    temp_res<- adonis(formula=final_formula, data=meta_splits[[i]], by="margin")
    temp_res <- as.data.frame(temp_res$aov.tab)
    temp_res$feature <- rownames(temp_res)
    
    adonis_res[[name]] <- temp_res
  }
  
  main_vars_p <- c()
  for(i in 1:length(adonis_res)){
    temp_p <- adonis_res[[i]] %>% filter(feature==main_variable) %>% select(`Pr(>F)`)
    main_vars_p <- c(main_vars_p, paste("p: ",as.character(temp_p), sep=""))
  }
  
  annotation_df <- data.frame(col1=levels(meta[,facet]),
                              label=main_vars_p)
  colnames(annotation_df)[1] <- "facet"
  return(list(annotation_df,adonis_res))
}



make_all_plots_and_adonis <- function(list_dist, list_title, metadata, facet, covariate, main_variable){
  
  pca_plots <- list()
  adonis_res <- list()
  
  for(i in names(list_dist)){
    pca_plots[[i]] <- plot_pca_all(dist=list_dist[[i]], meta = metadata, title = list_title[[i]], facet_type = facet)
    adonis_res[[i]] <- run_adonis_by_facet(dist=list_dist[[i]], meta=metadata, facet = facet, covariates = covariate, main_variable = main_variable) 
  }
  
  return(list(pca_plots, adonis_res))
}
```


```{r}
weighted_comb_plot <- plot_pca_all(weighted_uni_comb, Combined_data, "Weighted UniFrac")
weighted_comb_plot

saveRDS(weighted_comb_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_beta_wuni.RDS")


unweighted_comb_plot <- plot_pca_all(unweighted_uni_comb, Combined_data, "Unweighted UniFrac")
unweighted_comb_plot
saveRDS(unweighted_comb_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_beta_uuni.RDS")


bray_comb_plot <- plot_pca_all(bray_comb, Combined_data, "Bray Curtis")
saveRDS(bray_comb_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_beta_bray.RDS")

```


```{r}
library(vegan)
adonis(weighted_uni_comb ~ Combined_data$Case.Control_type)
adonis(bray_comb ~ Combined_data$Case.Control_type)
adonis(unweighted_uni_comb ~ Combined_data$Case.Control_type)
```

### time filt

```{r}
weighted_comb_time_plot <- plot_pca_all(weighted_uni_comb, Combined_data_filt, "Weighted UniFrac")
saveRDS(weighted_comb_time_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_beta_wuni_time.RDS")


unweighted_comb_time_plot <- plot_pca_all(unweighted_uni_comb, Combined_data_filt, "Unweighted UniFrac")
saveRDS(unweighted_comb_time_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_beta_uuni_time.RDS")

bray_comb_time_plot <- plot_pca_all(bray_comb, Combined_data_filt, "Bray Curtis")
saveRDS(bray_comb_time_plot, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_beta_bray_time.RDS")
```



### Individual
```{r}
dist_list <- list(
  'W_uni' = weighted_uni_comb,
  'U_uni' =  unweighted_uni_comb,
  'bray' = bray_comb,
  'rpca' = rpca_comb
)

title_list <- list(
  'W_uni' = "Weighted UniFrac",
  'U_uni' = "Unweighted UniFrac",
  'bray' = "Bray Curtis",
  'rpca' = "Robust Aitchisons"
)

```

#### No time filt

```{r}
Breast_data_comb <- Combined_data %>% filter(Type=="Breast")
Breast_data_comb$Case.Control_type <- Breast_data_comb$Case.Control
Breast_data_comb$Type <- factor(Breast_data_comb$Type)

Breast_plots <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Breast_data_comb, facet = "Type", covariate = NULL, main_variable = "Case.Control")



saveRDS(Breast_plots, "~/Private/CHAPTER_4/Revised_Figures/RDS/PATH_Pro_Breast_beta.RDS")
```

##### Breast with covariates
```{r}
Br_unadjusted_stat <- list()
Br_adjusted_stat_age <- list()
Br_adjusted_stat <- list()

covars_age <- "SDC_AGE_CALC"
covars <- "SDC_AGE_CALC + PM_STANDING_HEIGHT_AVG + PM_WAIST_HIP_RATIO"

#need to filter metadata so that it only has samples that are fully complete...

Breast_data_comb_noNA <- Breast_data_comb[-which(is.na(Breast_data_comb$NUT_VEG_QTY)),]


dim(Breast_data_comb_noNA)
dim(Breast_data_comb)
table(Breast_data_comb$Case.Control)
table(Breast_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  Br_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Br_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Br_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars)
  
  
  
}

names(Br_unadjusted_stat)
Br_unadjusted_stat

names(Br_adjusted_stat_age)
Br_adjusted_stat_age

names(Br_adjusted_stat)
Br_adjusted_stat

```


```{r}
Prostate_data_comb <- Combined_data %>% filter(Type=="Prostate")
Prostate_data_comb$Case.Control_type <- Prostate_data_comb$Case.Control
Prostate_data_comb$Type <- factor(Prostate_data_comb$Type)

Prostate_plots <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Prostate_data_comb, facet="Type", covariate = NULL, main_variable = "Case.Control")

saveRDS(Prostate_plots, "~/Private/CHAPTER_4/Revised_Figures/RDS/PATH_Pro_Prostate_beta_all.RDS")
```


### Prostate with covarites
```{r}
Pr_unadjusted_stat <- list()
Pr_adjusted_stat_age <- list()
Pr_adjusted_stat <- list()


#need to filter metadata so that it only has samples that are fully complete...

Prostate_data_comb_noNA <- Prostate_data_comb[-which(is.na(Prostate_data_comb$NUT_VEG_QTY)),]
table(Prostate_data_comb_noNA$Case.Control)
table(Prostate_data_comb$Case.Control)

for(i in 1:length(dist_list)){
  
  Pr_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Pr_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Pr_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars)
  
  
  
}
names(Pr_unadjusted_stat)
Pr_unadjusted_stat

names(Pr_adjusted_stat_age)
Pr_adjusted_stat_age

names(Pr_adjusted_stat)
Pr_adjusted_stat
```


```{r}
CRC_data_comb <- Combined_data %>% filter(Type=="Colon")
CRC_data_comb$Case.Control_type <- CRC_data_comb$Case.Control
CRC_data_comb$Type <- factor(CRC_data_comb$Type)

CRC_plots <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=CRC_data_comb, facet="Type", covariate = NULL, main_variable = "Case.Control")

saveRDS(CRC_plots, "~/Private/CHAPTER_4/Revised_Figures/RDS/PATH_Pro_CRC_beta_all.RDS")
```

```{r}
CRC_unadjusted_stat <- list()
CRC_adjusted_stat_age <- list()
CRC_adjusted_stat <- list()

covars_age <- "SDC_AGE_CALC + SDC_GENDER"
covars <- "SDC_AGE_CALC + PM_STANDING_HEIGHT_AVG + PM_WAIST_HIP_RATIO + SDC_GENDER + NUT_VEG_QTY"

#need to filter metadata so that it only has samples that are fully complete...
CRC_data_comb_noNA <- CRC_data_comb[-which(is.na(CRC_data_comb$NUT_VEG_QTY)),]
table(CRC_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  CRC_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  CRC_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  CRC_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars)
  
  
  
}

names(CRC_unadjusted_stat)
CRC_unadjusted_stat

CRC_adjusted_stat_age


CRC_adjusted_stat
```



```{r}
Breast_plots <- readRDS("~/Private/CHAPTER_4/Revised_Figures/RDS/PATH_Pro_Breast_beta.RDS")
Prostate_plots <- readRDS("~/Private/CHAPTER_4/Revised_Figures/RDS/PATH_Pro_Prostate_beta_all.RDS")
CRC_plots <- readRDS("~/Private/CHAPTER_4/Revised_Figures/RDS/PATH_Pro_CRC_beta_all.RDS")

Breast_beta_plot <- plot_grid(#Breast_plots[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                              Breast_plots[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                              Breast_plots[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                              Breast_plots[[1]][[4]] + theme_cowplot() + theme(legend.position = "none"),
                              nrow=1)


Prostate_beta_plot <- plot_grid(#Prostate_plots[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                                Prostate_plots[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                                Prostate_plots[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                                Prostate_plots[[1]][[4]] + theme_cowplot() + theme(legend.position = "none"),
                                nrow=1)


Colon_beta_plot <- plot_grid(#CRC_plots[[1]][[1]] + theme_cowplot() + theme(legend.position = "none"),
                             CRC_plots[[1]][[2]] + theme_cowplot() + theme(legend.position = "none"),
                             CRC_plots[[1]][[3]] + theme_cowplot() + theme(legend.position = "none"),
                             CRC_plots[[1]][[4]] + theme_cowplot() + theme(legend.position = "none"),
                             nrow=1)


sup_beta_plot <- plot_grid(Breast_beta_plot,
                           Prostate_beta_plot,
                           Colon_beta_plot,
                           nrow=3,
                           labels = c("A", "B", "C"))
sup_beta_plot

sup_beta_plot_leg <- plot_grid(sup_beta_plot, 
                               get_legend(CRC_plots[[1]][[1]]),
                               nrow=1,
                               rel_widths = c(1,.1))
sup_beta_plot_leg

ggsave("~/Private/CHAPTER_4/Revised_Figures/Display_items/Supplemental/PATH_Pro_beta_sup.pdf",
       width=9, height=9)
```

#### Time filt

```{r}
Breast_data_comb <- Combined_data_filt %>% filter(Type=="Breast")
Breast_data_comb$Case.Control_type <- Breast_data_comb$Case.Control
Breast_data_comb$Type <- factor(Breast_data_comb$Type)

Breast_plots_time4 <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Breast_data_comb, facet="Type", covariate = NULL, main_variable = "Case.Control")
saveRDS(Breast_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_breast_beta_time4.RDS")
```

```{r}
Br_unadjusted_stat <- list()
Br_adjusted_stat_age <- list()
Br_adjusted_stat <- list()

covars_age <- "SDC_AGE_CALC"
covars <- "SDC_AGE_CALC + PM_STANDING_HEIGHT_AVG + PM_WAIST_HIP_RATIO"

#need to filter metadata so that it only has samples that are fully complete...

Breast_data_comb_noNA <- Breast_data_comb[-which(is.na(Breast_data_comb$NUT_VEG_QTY)),]


dim(Breast_data_comb_noNA)
dim(Breast_data_comb)
table(Breast_data_comb$Case.Control)
table(Breast_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  Br_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Br_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Br_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Breast_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars)
  
  
  
}

names(Br_unadjusted_stat)
Br_unadjusted_stat

names(Br_adjusted_stat_age)
Br_adjusted_stat_age

names(Br_adjusted_stat)
Br_adjusted_stat

```

```{r}
Prostate_data_comb <- Combined_data_filt %>% filter(Type=="Prostate")
Prostate_data_comb$Case.Control_type <- Prostate_data_comb$Case.Control_type
Prostate_data_comb$Type <- factor(Prostate_data_comb$Type)

Prostate_plots_time4 <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=Prostate_data_comb, facet="Type", covariate = NULL,
                                                  main_variable = "Case.Control")
saveRDS(Prostate_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_prostate_beta_time4.RDS")
```

```{r}
Pr_unadjusted_stat <- list()
Pr_adjusted_stat_age <- list()
Pr_adjusted_stat <- list()


#need to filter metadata so that it only has samples that are fully complete...

Prostate_data_comb_noNA <- Prostate_data_comb[-which(is.na(Prostate_data_comb$NUT_VEG_QTY)),]
table(Prostate_data_comb_noNA$Case.Control)
table(Prostate_data_comb$Case.Control)

for(i in 1:length(dist_list)){
  
  Pr_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  Pr_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  Pr_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = Prostate_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars)
  
  
  
}
names(Pr_unadjusted_stat)
Pr_unadjusted_stat

names(Pr_adjusted_stat_age)
Pr_adjusted_stat_age

names(Pr_adjusted_stat)
Pr_adjusted_stat
```

```{r}
CRC_data_comb <- Combined_data_filt %>% filter(Type=="Colon")
CRC_data_comb$Case.Control_type <- CRC_data_comb$Case.Control
CRC_data_comb$Type <- factor(CRC_data_comb$Type)

CRC_plots_time4 <- make_all_plots_and_adonis(list_dist = dist_list, list_title = title_list, metadata=CRC_data_comb, facet="Type", covariate = NULL,
                                             main_variable = "Case.Control")

saveRDS(CRC_plots_time4, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_PATH_CRC_beta_time4.RDS")
```

```{r}
CRC_unadjusted_stat <- list()
CRC_adjusted_stat_age <- list()
CRC_adjusted_stat <- list()

covars_age <- "SDC_AGE_CALC + SDC_GENDER"
covars <- "SDC_AGE_CALC + PM_STANDING_HEIGHT_AVG + PM_WAIST_HIP_RATIO + SDC_GENDER + NUT_VEG_QTY"

#need to filter metadata so that it only has samples that are fully complete...
CRC_data_comb_noNA <- CRC_data_comb[-which(is.na(CRC_data_comb$NUT_VEG_QTY)),]
table(CRC_data_comb_noNA$Case.Control)

for(i in 1:length(dist_list)){
  
  CRC_unadjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = NULL)
  
  CRC_adjusted_stat_age[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars_age)
  
  ## this becomes problematic when not all features have that data...
  CRC_adjusted_stat[[names(dist_list)[[i]]]] <- run_adonis_by_facet(dist = dist_list[[i]], meta = CRC_data_comb_noNA, 
                                                 facet = "Type", main_variable = "Case.Control", 
                                                 covariates = covars)
  
  
  
}

names(CRC_unadjusted_stat)
CRC_unadjusted_stat

CRC_adjusted_stat_age


CRC_adjusted_stat
```

# time vs. alpha

```{r}
Combined_data %>% filter(Case.Control=="Control", Type=="Breast") %>% summarize(mean(faith_pd))
Combined_data %>% filter(Case.Control=="Control", Type=="Prostate") %>% summarize(mean(faith_pd))
Combined_data %>% filter(Case.Control=="Control", Type=="Colon") %>% summarize(mean(faith_pd))

Case_samples <- Combined_data %>% filter(Case.Control=="Case")

Case_samples$mean_faith <- 10.59
Case_samples$mean_faith[which(Case_samples$Type=="Prostate")] <- 9.91
Case_samples$mean_faith[which(Case_samples$Type=="Colon")] <- 10.78



faiths_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=faith_pd)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_faith), color="red", linetype="dashed") +
  ylab("Faith's Phylogenetic Diversity") + xlab("Time since diagnosis")

faiths_cor_data

Combined_data %>% filter(Case.Control=="Control", Type=="Breast") %>% summarize(mean(observed_features))
Combined_data %>% filter(Case.Control=="Control", Type=="Prostate") %>% summarize(mean(observed_features))
Combined_data %>% filter(Case.Control=="Control", Type=="Colon") %>% summarize(mean(observed_features))

Case_samples$mean_rich <- 102.6111
Case_samples$mean_rich[which(Case_samples$Type=="Prostate")] <- 92.68
Case_samples$mean_rich[which(Case_samples$Type=="Colon")] <- 109.50


richness_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=observed_features)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_rich), color="red", linetype="dashed") +
  ylab("Richness") + xlab("Time since diagnosis")


Combined_data %>% filter(Case.Control=="Control", Type=="Breast") %>% summarize(mean(shannon_entropy))
Combined_data %>% filter(Case.Control=="Control", Type=="Prostate") %>% summarize(mean(shannon_entropy))
Combined_data %>% filter(Case.Control=="Control", Type=="Colon") %>% summarize(mean(shannon_entropy))

Case_samples$mean_shannon <- 4.292
Case_samples$mean_shannon[which(Case_samples$Type=="Prostate")] <- 4.153
Case_samples$mean_shannon[which(Case_samples$Type=="Colon")] <- 4.122

shannon_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=shannon_entropy)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_shannon), color="red", linetype="dashed") +
  ylab("Shannon Diversity") + xlab("Time since diagnosis")


Combined_data %>% filter(Case.Control=="Control", Type=="Breast") %>% summarize(mean(pielou_evenness))
Combined_data %>% filter(Case.Control=="Control", Type=="Prostate") %>% summarize(mean(pielou_evenness))
Combined_data %>% filter(Case.Control=="Control", Type=="Colon") %>% summarize(mean(pielou_evenness))


Case_samples$mean_even <- 0.645
Case_samples$mean_even[which(Case_samples$Type=="Prostate")] <- 0.640
Case_samples$mean_even[which(Case_samples$Type=="Colon")] <- 0.613

even_cor_data <- ggplot(Case_samples, aes(x=age_diff, y=pielou_evenness)) + geom_point() +
  facet_grid(~ Type) + geom_line(aes(y=mean_even), color="red", linetype="dashed") +
  ylab("Evenness") + xlab("Time since diagnosis")

```

```{r}
cor_plot_fin <- plot_grid(faiths_cor_data, richness_cor_data, shannon_cor_data, even_cor_data)
cor_plot_fin

ggsave("~/Private/CHAPTER_4/Revised_Figures/Display_items/Supplemental/PATH_Pro_alpha_cor.pdf",
       width=9, height=9, dpi=600)
```

```{r}
Breast_case <- Case_data %>% filter(Type=="Breast")

cor.test(Breast_case$age_diff, Breast_case$faith_pd, method="spearman")
cor.test(Breast_case$age_diff, Breast_case$pielou_evenness, method="spearman")
cor.test(Breast_case$age_diff, Breast_case$shannon_entropy, method="spearman")
cor.test(Breast_case$age_diff, Breast_case$observed_features, method="spearman")
```

```{r}
Prostate_case <- Case_data %>% filter(Type=="Prostate")

cor.test(Prostate_case$age_diff, Prostate_case$faith_pd, method="spearman")
cor.test(Prostate_case$age_diff, Prostate_case$pielou_evenness, method="spearman")
cor.test(Prostate_case$age_diff, Prostate_case$shannon_entropy, method="spearman")
cor.test(Prostate_case$age_diff, Prostate_case$observed_features, method="spearman")



```


```{r}
Colon_case <- Case_data %>% filter(Type=="Colon")

cor.test(Colon_case$age_diff, Colon_case$faith_pd, method="spearman")
cor.test(Colon_case$age_diff, Colon_case$pielou_evenness, method="spearman")
cor.test(Colon_case$age_diff, Colon_case$shannon_entropy, method="spearman")
cor.test(Colon_case$age_diff, Colon_case$observed_features, method="spearman")
```