---
title: "Breast_RF_LOOCV_PATH"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(randomForest)
library(cvAUC)
library(caret)
library(rfUtilities)

library(doParallel)

cl <- makePSOCKcluster(40)
registerDoParallel(cl)


remove_rare_features <- function( table , cutoff_pro=0.1, parallel=1 ) {
  if(cutoff_pro<=0){
    message("No filtering will be done due to cutoff_pro set to 0 or below")
    return(table)
  }
  row2keep <- c()
  cutoff <- ceiling( cutoff_pro * ncol(table) )
  if(parallel <= 1){
    for ( i in 1:nrow(table) ) {
      row_nonzero <- length( which( table[ i , ]  > 0 ) )
      if ( row_nonzero > cutoff ) {
        row2keep <- c( row2keep , i)
      }
    }
    return( table [ row2keep , , drop=F ])
  }else{
    `%dopar%` <- foreach::`%dopar%`
    cl <- parallel::makeCluster(parallel)
    doParallel::registerDoParallel(cl)
    message("Running with: ", foreach::getDoParWorkers(), " cores")

    res <- foreach::foreach(i = 1:nrow(table), .combine = c) %dopar% {
      row_nonzero <- length( which ( table[ i , ] > 0))
      if(row_nonzero > cutoff){
        i
      }else
        NULL
    }
    parallel::stopCluster(cl)
    return( table[res, , drop=F])

  }

}

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(((is.na(df[i,'age_diff']) | df[i,'age_diff'] < 0)) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}


repeated_cv_RF <- function(classes, data, repeats=10, folds=5, down=F, seeds){
  
  #we ultimately want to return a list of models
  # a list of test_labels
  # a list of test_preds
  model_list <- list()
  test_lab_list <- list()
  test_preds_list <- list()
  
  if(down){
    down_data <- downSample(data, classes, list=T)
    data <- down_data[[1]]
    classes <- down_data[[2]]
  }
  
  index <- 0
  for(i in 1:repeats){
    set.seed(seeds[i])
    fold <- createFolds(classes, k=folds, returnTrain = T)
    
    for(j in 1:length(fold)){
      index <- index+1
      message(index)
      train_labs <- classes[fold[[j]]]
      train_data <- data[fold[[j]],]
      test_labs <- classes[-fold[[j]]]
      test_data <- data[-fold[[j]],]
      
      model <- randomForest(x=train_data, y=train_labs, xtest = test_data, ytest = test_labs, ntree = 1001, importance=T)
      model_list[[index]] <- model
      test_lab_list[[index]] <- test_labs
      test_preds_list[[index]] <- model$test$votes[,2]
    }
  }
  all_model <- randomForest(x=data, y=classes, ntree=1001)
  return(list(model_list, test_lab_list, test_preds_list, all_model))
  
}

```

```{r}
Metadata_Breast <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_Breast.RDS")
Metadata_Breast$Case_Control <- as.character(Metadata_Breast$`Case/Control`)
Metadata_Prostate <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_Prostate.RDS")
Metadata_Prostate$Case_Control <- as.character(Metadata_Prostate$`Case/Control`)
Metadata_CRC <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Metadata/Metadata_CRC.RDS")
Metadata_CRC$Case_Control <- as.character(Metadata_CRC$`Case/Control`)

Metadata_Breast$Case.Control <- ifelse(Metadata_Breast$`CASE/CONTROL`==1, "Case", "Control")
Metadata_Prostate$Case.Control <- ifelse(Metadata_Prostate$`CASE/CONTROL`==1, "Case", "Control")
Metadata_CRC$Case.Control <- ifelse(Metadata_CRC$`CASE/CONTROL`==1, "Case", "Control")

Metadata_Breast$Case.Control <- factor(Metadata_Breast$Case.Control, levels=c("Control", "Case"))
Metadata_Prostate$Case.Control <- factor(Metadata_Prostate$Case.Control, levels=c("Control", "Case"))
Metadata_CRC$Case.Control <- factor(Metadata_CRC$Case.Control, levels=c("Control", "Case"))

Faiths <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/faiths/alpha-diversity.tsv",
                     header=T, row.names=1)
Evenness <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/evenness/alpha-diversity.tsv",
                        header=T, row.names = 1)

Richness <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/richness/alpha-diversity.tsv", 
                       header=T, row.names = 1)

Shannon <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/diversity_3000/raw_alpha/shannon/alpha-diversity.tsv",
                      header=T, row.names = 1)

Alpha_data <- cbind(Faiths, Evenness, Richness, Shannon)

Alpha_data$`Saliva ID Ship` <- rownames(Alpha_data)

Alpha_Breast <- Alpha_data %>% inner_join(Metadata_Breast, by="Saliva ID Ship")
Alpha_Prostate <- Alpha_data %>% inner_join(Metadata_Prostate, by="Saliva ID Ship")
Alpha_CRC  <- Alpha_data %>% inner_join(Metadata_CRC, by="Saliva ID Ship")

Alpha_Breast$X <- Alpha_Breast$`Saliva ID Ship`
Alpha_Prostate$X <- Alpha_Prostate$`Saliva ID Ship`
Alpha_CRC$X <- Alpha_CRC$`Saliva ID Ship`

Alpha_Breast$age_diff <- Alpha_Breast$F1_DIS_CANCER1_AGE - Alpha_Breast$SDC_AGE_CALC
Alpha_Prostate$age_diff <- Alpha_Prostate$F1_DIS_CANCER1_AGE - Alpha_Prostate$SDC_AGE_CALC
Alpha_CRC$age_diff <- Alpha_CRC$F1_DIS_CANCER1_AGE - Alpha_CRC$SDC_AGE_CALC

Alpha_Breast$Type <- "Breast"
Alpha_Prostate$Type <- "Prostate"
Alpha_CRC$Type <- "Colon"

Alpha_Breast <- remove_non_matching_caseIDS(Alpha_Breast)
Alpha_Prostate <- remove_non_matching_caseIDS(Alpha_Prostate)
Alpha_CRC <- remove_non_matching_caseIDS(Alpha_CRC)

Breast_data_comb <- Alpha_Breast %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

Prostate_data_comb <- Alpha_Prostate %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

CRC_data_comb <- Alpha_CRC %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)


Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)

Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r}


Genera <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/Taxa/genus_table/feature-table.tsv", sep="\t", header=T, row.names=1, skip=1, comment.char="",
                     check.names=F)

ASV <- read.table("~/Private/Future_Cancer_Project/Cancer_Samples/deblur_output/raw_table/feature-table.tsv", sep="\t", header=T, row.names=1, skip=1, comment.char="", check.names = F)


Breast_Genera <- Genera[,Breast_data$X]
Breast_ASV <- ASV[,Breast_data$X]

Prostate_Genera <- Genera[,Prostate_data$X]
Prostate_ASV <- ASV[,Prostate_data$X]

CRC_Genera <- Genera[,CRC_data$X]
CRC_ASV <- ASV[,CRC_data$X]
```

```{r}
ASV_Breast_CLR <- data.frame(apply(Breast_ASV + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_CRC_CLR <- data.frame(apply(CRC_ASV + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_Prostate_CLR <- data.frame(apply(Prostate_ASV + 1, 2, function(x){log(x) - mean (log(x))}), check.names = F)

ASV_Breast_CLR_flip <- data.frame(t(ASV_Breast_CLR), check.names = F)
ASV_Breast_CLR_flip$X <- rownames(ASV_Breast_CLR_flip)

ASV_CRC_CLR_flip <- data.frame(t(ASV_CRC_CLR), check.names = F)
ASV_CRC_CLR_flip$X <- rownames(ASV_CRC_CLR_flip)

ASV_Prostate_CLR_flip <- data.frame(t(ASV_Prostate_CLR), check.names = F)
ASV_Prostate_CLR_flip$X <- rownames(ASV_Prostate_CLR_flip)

Genus_Breast_CLR <- data.frame(apply(Breast_Genera + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_CRC_CLR <- data.frame(apply(CRC_Genera + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_Prostate_CLR <- data.frame(apply(Prostate_Genera + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)

Genus_Breast_CLR_flip <- data.frame(t(Genus_Breast_CLR), check.names = F)
Genus_Breast_CLR_flip$X <- rownames(Genus_Breast_CLR_flip)

Genus_CRC_CLR_flip <- data.frame(t(Genus_CRC_CLR), check.names = F)
Genus_CRC_CLR_flip$X <- rownames(Genus_CRC_CLR_flip)

Genus_Prostate_CLR_flip <- data.frame(t(Genus_Prostate_CLR), check.names = F)
Genus_Prostate_CLR_flip$X <- rownames(Genus_Prostate_CLR_flip)


ASV_Breast_RA <- sweep(Breast_ASV, 2, colSums(Breast_ASV), '/')
ASV_CRC_RA <- sweep(CRC_ASV, 2, colSums(CRC_ASV), '/')
ASV_Prostate_RA <- sweep(Prostate_ASV, 2, colSums(Prostate_ASV), '/')

ASV_Breast_RA_flip <- data.frame(t(ASV_Breast_RA), check.names=F)
ASV_Breast_RA_flip$X <- rownames(ASV_Breast_RA_flip)

ASV_CRC_RA_flip <- data.frame(t(ASV_CRC_RA), check.names = F)
ASV_CRC_RA_flip$X <- rownames(ASV_CRC_RA_flip)

ASV_Prostate_RA_flip <- data.frame(t(ASV_Prostate_RA), check.names = F)
ASV_Prostate_RA_flip$X <- rownames(ASV_Prostate_RA_flip)

Genus_Breast_RA <- sweep(Breast_Genera, 2, colSums(Breast_Genera), '/')
Genus_CRC_RA <- sweep(CRC_Genera, 2, colSums(CRC_Genera), '/')
Genus_Prostate_RA <- sweep(Prostate_Genera, 2, colSums(Prostate_Genera), '/')

Genus_Breast_RA_flip <- data.frame(t(Genus_Breast_RA), check.names = F)
Genus_Breast_RA_flip$X <- rownames(Genus_Breast_RA_flip)

Genus_CRC_RA_flip <- data.frame(t(Genus_CRC_RA), check.names = F)
Genus_CRC_RA_flip$X <- rownames(Genus_CRC_RA_flip)

Genus_Prostate_RA_flip <- data.frame(t(Genus_Prostate_RA), check.names = F)
Genus_Prostate_RA_flip$X <- rownames(Genus_Prostate_RA_flip)
```


```{r}
ASV_Breast_RA_filt <- remove_rare_features(table = ASV_Breast_RA, cutoff_pro = 0.05)
ASV_Prostate_RA_filt <- remove_rare_features(table=ASV_Prostate_RA, cutoff_pro = 0.05)
ASV_CRC_RA_filt <- remove_rare_features(table=ASV_CRC_RA, cutoff_pro = 0.05)

ASV_Breast_RA_filt_flip <- data.frame(t(ASV_Breast_RA_filt), check.names = F)
ASV_Prostate_RA_filt_flip <- data.frame(t(ASV_Prostate_RA_filt), check.names = F)
ASV_CRC_RA_filt_flip <- data.frame(t(ASV_CRC_RA_filt), check.names = F)


Genus_Breast_RA_filt <- remove_rare_features(table=Genus_Breast_RA, cutoff_pro = 0.05)
Genus_Prostate_RA_filt <- remove_rare_features(table=Genus_Prostate_RA, cutoff_pro = 0.05)
Genus_CRC_RA_filt <- remove_rare_features(table=Genus_CRC_RA, cutoff_pro = 0.05)

Genus_Breast_RA_filt_flip <- data.frame(t(Genus_Breast_RA_filt), check.names = F)
Genus_Prostate_RA_filt_flip <- data.frame(t(Genus_Prostate_RA_filt), check.names = F)
Genus_CRC_RA_filt_flip <- data.frame(t(Genus_CRC_RA_filt), check.names = F)


ASV_Breast_CLR_filt_flip <- ASV_Breast_CLR_flip[,colnames(ASV_Breast_RA_filt_flip)]
ASV_Prostate_CLR_filt_flip <- ASV_Prostate_CLR_flip[,colnames(ASV_Prostate_RA_filt_flip)]
ASV_CRC_CLR_filt_flip <- ASV_CRC_CLR_flip[,colnames(ASV_CRC_RA_filt_flip)]

Genus_Breast_CLR_filt_flip <- Genus_Breast_CLR_flip[,colnames(Genus_Breast_RA_filt_flip)]
Genus_Prostate_CLR_filt_flip <- Genus_Prostate_CLR_flip[,colnames(Genus_Prostate_RA_filt_flip)]
Genus_CRC_CLR_filt_flip <- Genus_CRC_CLR_flip[,colnames(Genus_CRC_RA_filt_flip)]


fit_control_rcv <- trainControl(method="repeatedcv", savePredictions = T, summaryFunction = twoClassSummary, classProbs = T, repeats = 100, number = 5)
```

# Breast 

## ASV RA
```{r}


stopifnot(identical(rownames(ASV_Breast_RA_filt_flip), Breast_data$X))
set.seed(10)

ASV_RCV_Breast <- train(ASV_Breast_RA_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                        tuneGrid = data.frame(mtry=21), trControl = fit_control_rcv, importance=T)

ASV_RCV_Breast
saveRDS(ASV_RCV_Breast, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/ASV_RCV_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_Breast_RA_filt_flip), Breast_data$X))
set.seed(10)

ASV_RCV_Breast_CLR <- train(ASV_Breast_CLR_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                            tuneGrid = data.frame(mtry=21), trControl = fit_control_rcv, importance=T)

ASV_RCV_Breast_CLR
saveRDS(ASV_RCV_Breast_CLR, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/ASV_RCV_CLR_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_Breast_RA_filt_flip), Breast_data$X))
set.seed(10)

Genus_RCV_Breast_RA <- train(Genus_Breast_RA_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                             tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)

Genus_RCV_Breast_RA
saveRDS(Genus_RCV_Breast_RA, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/Genus_RCV_RA_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_Breast_CLR_filt_flip), Breast_data$X))
set.seed(10)

Genus_RCV_Breast_CLR <- train(Genus_Breast_CLR_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                              tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)

Genus_RCV_Breast_CLR
saveRDS(Genus_RCV_Breast_CLR, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/Genus_RCV_CLR_caret.RDS")
```

# Prostate

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_Prostate_RA_filt_flip), Prostate_data$X))
set.seed(10)

ASV_RCV_Prostate_RA <- train(ASV_Prostate_RA_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                             tuneGrid = data.frame(mtry=20), trControl = fit_control_rcv, importance=T)
ASV_RCV_Prostate_RA
saveRDS(ASV_RCV_Prostate_RA, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/ASV_RCV_RA_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_Prostate_CLR_filt_flip), Prostate_data$X))
set.seed(10)

ASV_RCV_Prostate_CLR <- train(ASV_Prostate_CLR_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                              tuneGrid = data.frame(mtry=20), trControl = fit_control_rcv, importance=T)
ASV_RCV_Prostate_CLR
saveRDS(ASV_RCV_Prostate_CLR, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/ASV_RCV_CLR_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_Prostate_RA_filt_flip), Prostate_data$X))
set.seed(10)

Genus_RCV_Prostate_RA <- train(Genus_Prostate_RA_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                               tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)

Genus_RCV_Prostate_RA
saveRDS(Genus_RCV_Prostate_RA, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/Genus_RCV_RA_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_Prostate_CLR_filt_flip), Prostate_data$X))
set.seed(10)

Genus_RCV_Prostate_CLR <- train(Genus_Prostate_CLR_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                                tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)

Genus_RCV_Prostate_CLR
saveRDS(Genus_RCV_Prostate_CLR, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/Genus_RCV_CLR_caret.RDS")
```

# Colon

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_CRC_RA_filt_flip), CRC_data$X))
set.seed(10)

ASV_RCV_CRC_RA <- train(ASV_CRC_RA_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                        tuneGrid = data.frame(mtry=21), trControl = fit_control_rcv, importance=T)
ASV_RCV_CRC_RA
saveRDS(ASV_RCV_CRC_RA, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/ASV_RCV_RA_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_CRC_CLR_filt_flip), CRC_data$X))
set.seed(10)

ASV_RCV_CRC_CLR <- train(ASV_CRC_CLR_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                         tuneGrid = data.frame(mtry=21), trControl = fit_control_rcv, importance=T)
ASV_RCV_CRC_CLR

saveRDS(ASV_RCV_CRC_CLR, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/ASV_RCV_CLR_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_CRC_RA_filt_flip), CRC_data$X))
set.seed(10)

Genus_RCV_CRC_RA <- train(Genus_CRC_RA_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                          tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_CRC_RA

saveRDS(Genus_RCV_CRC_RA, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/Genus_RCV_RA_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_CRC_CLR_filt_flip), CRC_data$X))
set.seed(10)

Genus_RCV_CRC_CLR <- train(Genus_CRC_CLR_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                           tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)

Genus_RCV_CRC_CLR

saveRDS(Genus_RCV_CRC_CLR, "~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/Genus_RCV_CLR_caret.RDS")
```