---
title: "DA_analysis_ATP"
author: "Jacob T. Nearing"
date: "2/15/2022"
output:
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "chaos"
    code_folding: hide
    widescreen: true
    fig_height: 12
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(ggbeeswarm)
library(gridExtra)
library(cowplot)
library(kableExtra)
library(DT)

library(reshape2)
library(pheatmap)
library(RColorBrewer)
library(readxl)

remove_rare_features <- function( table , cutoff_pro=0.1, parallel=1 ) {
  if(cutoff_pro<=0){
    message("No filtering will be done due to cutoff_pro set to 0 or below")
    return(table)
  }
  row2keep <- c()
  cutoff <- ceiling( cutoff_pro * ncol(table) )
  if(parallel <= 1){
    for ( i in 1:nrow(table) ) {
      row_nonzero <- length( which( table[ i , ]  > 0 ) )
      if ( row_nonzero > cutoff ) {
        row2keep <- c( row2keep , i)
      }
    }
    return( table [ row2keep , , drop=F ])
  }else{
    `%dopar%` <- foreach::`%dopar%`
    cl <- parallel::makeCluster(parallel)
    doParallel::registerDoParallel(cl)
    message("Running with: ", foreach::getDoParWorkers(), " cores")

    res <- foreach::foreach(i = 1:nrow(table), .combine = c) %dopar% {
      row_nonzero <- length( which ( table[ i , ] > 0))
      if(row_nonzero > cutoff){
        i
      }else
        NULL
    }
    parallel::stopCluster(cl)
    return( table[res, , drop=F])

  }

}

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}
```

```{r}
Breast_ASV_aldex <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/ASV_aldex2.RDS")
Breast_ASV_ancom <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/ASV_ancom.RDS")
Breast_ASV_corncob <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/ASV_corncob.RDS")
Breast_ASV_maaslin2 <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/ASV_maaslin2.RDS")

Breast_GENUS_aldex <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/genera_aldex2.RDS")
Breast_GENUS_ancom <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/Genus_ancom.RDS")
Breast_GENUS_corncob <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/Genera_corncob.RDS")
Breast_GENUS_maaslin2 <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Breast/Genera_maaslin2.RDS")
```

```{r}
Prostate_ASV_aldex <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/ASV_aldex2.RDS")
Prostate_ASV_ancom <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/ASV_ancom.RDS")
Prostate_ASV_corncob <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/ASV_corncob.RDS")
Prostate_ASV_maaslin2 <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/ASV_maaslin2.RDS")

Prostate_GENUS_aldex <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/Genera_Aldex.RDS")
Prostate_GENUS_ancom <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/Genera_ancom")
Prostate_GENUS_corncob <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/Genera_corncob.RDS")
Prostate_GENUS_maaslin2 <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Prostate/Genera_maaslin2.RDS")
```


```{r}
Colon_ASV_aldex <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/ASV_aldex2.RDS")
Colon_ASV_ancom <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/ASV_ANCOM.RDS")
Colon_ASV_corncob <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/ASV_corncob.RDS")
Colon_ASV_maaslin2 <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/ASV_maaslin2.RDS")

Colon_GENUS_aldex <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/Genera_Aldex.RDS")
Colon_GENUS_ancom <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/Genera_ANCOM.RDS")
Colon_GENUS_corncob <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/Genera_corncob.RDS")
Colon_GENUS_maaslin2 <- readRDS("~/Private/CHAPTER_4/Prospec/ATP/data/Colon/Genera_maaslin2.RDS")


Colon_ASV_ancom <- Colon_ASV_ancom[-which(Colon_ASV_ancom$W==Inf),]
```


```{r}
base_metadata <- readRDS("~/Private/ATP/Metadata/Base_microbiome_metadata.RDS")
base_metadata$ParticipantKey <- as.character(base_metadata$ParticipantKey)
rownames(base_metadata) <- base_metadata$researcher



sheet_names <- c("ACR", "ACR_Treatment", "Core", "Core_Chronic", "HLQ", "Master_Data", "Case_Control_Match", "PANS", "PM_data", "UHLQ", "UHLQ_Cond")

Metadata <- list()

for(i in 1:length(sheet_names)){
  
  Metadata[[sheet_names[i]]] <- read_excel("~/Private/ATP/Metadata/ATP_MASTER_DATA.xls", sheet=i)
  
}


Metadata[[7]]$matchID <- seq(1:207)

case_control_match <- melt(Metadata[[7]][,-3], id.vars = 'matchID')



Shannon_div <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/shannon.tsv",
                          sep="\t", header=T)
colnames(Shannon_div)[1] <- "researcher"

#faith pd
faith_pd <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/faiths_pd.tsv",
                       sep="\t", header=T)
colnames(faith_pd)[1] <- "researcher"

#raw richness
richness <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/observed_feats.tsv",
                       sep="\t", header=T)
colnames(richness)[1] <- "researcher"

#evenness
evenness <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/evenness.tsv",
                       sep="\t", header=T)
colnames(evenness)[1] <- "researcher"


## 40 samples did not reach sequencing requirements.
Alpha_div <- Shannon_div %>% left_join(faith_pd, by="researcher") %>% left_join(richness, by="researcher") %>% left_join(evenness, by="researcher")


Full_data <- Alpha_div %>% inner_join(base_metadata, by="researcher")
Full_data$Case.Control <- factor(Full_data$ARM.x, levels=c("control", "case"))



Alpha_Breast <- Full_data %>% filter(Type=="Breast")
Alpha_Prostate <- Full_data %>% filter(Type=="Prostate")
Alpha_CRC <- Full_data %>% filter(Type=="Colon") 

Alpha_Breast$X <- Alpha_Breast$researcher
Alpha_Prostate$X <- Alpha_Prostate$researcher
Alpha_CRC$X <- Alpha_CRC$researcher

Alpha_Breast$CaseID <- case_control_match$matchID[match(Alpha_Breast$ParticipantKey, case_control_match$value)]
Alpha_Prostate$CaseID <- case_control_match$matchID[match(Alpha_Prostate$ParticipantKey, case_control_match$value)]
Alpha_CRC$CaseID <- case_control_match$matchID[match(Alpha_CRC$ParticipantKey, case_control_match$value)]

Alpha_Breast <- remove_non_matching_caseIDS(Alpha_Breast)
Alpha_Prostate <- remove_non_matching_caseIDS(Alpha_Prostate)
Alpha_CRC <- remove_non_matching_caseIDS(Alpha_CRC)

Breast_data_comb <- Alpha_Breast %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

Prostate_data_comb <- Alpha_Prostate %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

CRC_data_comb <- Alpha_CRC %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)


Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r}

genera <- read.table("~/Private/ATP/Analysis_21_12_01/taxa_tabs/level6_tabs/feature-tab.tsv",
                     sep="\t", comment.char="", skip=1, header=T, check.names = F, row.names = 1)

ASV <- read.table("~/Private/ATP/Analysis_21_12_01/deblur_output/asv_table/feature-table.tsv",
                  sep="\t", comment.char = "", skip=1, header=T, check.names = F, row.names = 1)

genera_breast <- genera[,as.character(Breast_data$X)]
genera_prostate <- genera[,as.character(Prostate_data$X)]
genera_colon <- genera[,as.character(CRC_data$X)]

asv_breast <- ASV[,as.character(Breast_data$X)]
asv_prostate <- ASV[,as.character(Prostate_data$X)]
asv_colon <- ASV[,as.character(CRC_data$X)]

genera_breast_filt <- remove_rare_features(genera_breast, 0.05)
genera_prostate_filt <- remove_rare_features(genera_prostate, 0.05)
genera_colon_filt <- remove_rare_features(genera_colon, 0.05)

asv_breast_filt <- remove_rare_features(asv_breast, 0.05)
asv_prostate_filt <- remove_rare_features(asv_prostate, 0.05)
asv_colon_filt <- remove_rare_features(asv_colon, 0.05)
```

```{r}
ASV_Breast_CLR <- data.frame(apply(asv_breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_CRC_CLR <- data.frame(apply(asv_colon + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_Prostate_CLR <- data.frame(apply(asv_prostate + 1, 2, function(x){log(x) - mean (log(x))}), check.names = F)

ASV_Breast_CLR_flip <- data.frame(t(ASV_Breast_CLR), check.names = F)
ASV_Breast_CLR_flip$X <- rownames(ASV_Breast_CLR_flip)

ASV_CRC_CLR_flip <- data.frame(t(ASV_CRC_CLR), check.names = F)
ASV_CRC_CLR_flip$X <- rownames(ASV_CRC_CLR_flip)

ASV_Prostate_CLR_flip <- data.frame(t(ASV_Prostate_CLR), check.names = F)
ASV_Prostate_CLR_flip$X <- rownames(ASV_Prostate_CLR_flip)

Genus_Breast_CLR <- data.frame(apply(genera_breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_CRC_CLR <- data.frame(apply(genera_colon + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_Prostate_CLR <- data.frame(apply(genera_prostate + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)

Genus_Breast_CLR_flip <- data.frame(t(Genus_Breast_CLR), check.names = F)
Genus_Breast_CLR_flip$X <- rownames(Genus_Breast_CLR_flip)

Genus_CRC_CLR_flip <- data.frame(t(Genus_CRC_CLR), check.names = F)
Genus_CRC_CLR_flip$X <- rownames(Genus_CRC_CLR_flip)

Genus_Prostate_CLR_flip <- data.frame(t(Genus_Prostate_CLR), check.names = F)
Genus_Prostate_CLR_flip$X <- rownames(Genus_Prostate_CLR_flip)


ASV_Breast_RA <- sweep(asv_breast, 2, colSums(asv_breast), '/')
ASV_CRC_RA <- sweep(asv_colon, 2, colSums(asv_colon), '/')
ASV_Prostate_RA <- sweep(asv_prostate, 2, colSums(asv_prostate), '/')

ASV_Breast_RA_flip <- data.frame(t(ASV_Breast_RA), check.names=F)
ASV_Breast_RA_flip$X <- rownames(ASV_Breast_RA_flip)

ASV_CRC_RA_flip <- data.frame(t(ASV_CRC_RA), check.names = F)
ASV_CRC_RA_flip$X <- rownames(ASV_CRC_RA_flip)

ASV_Prostate_RA_flip <- data.frame(t(ASV_Prostate_RA), check.names = F)
ASV_Prostate_RA_flip$X <- rownames(ASV_Prostate_RA_flip)

Genus_Breast_RA <- sweep(genera_breast, 2, colSums(genera_breast), '/')
Genus_CRC_RA <- sweep(genera_colon, 2, colSums(genera_colon), '/')
Genus_Prostate_RA <- sweep(genera_prostate, 2, colSums(genera_prostate), '/')

Genus_Breast_RA_flip <- data.frame(t(Genus_Breast_RA), check.names = F)
Genus_Breast_RA_flip$X <- rownames(Genus_Breast_RA_flip)

Genus_CRC_RA_flip <- data.frame(t(Genus_CRC_RA), check.names = F)
Genus_CRC_RA_flip$X <- rownames(Genus_CRC_RA_flip)

Genus_Prostate_RA_flip <- data.frame(t(Genus_Prostate_RA), check.names = F)
Genus_Prostate_RA_flip$X <- rownames(Genus_Prostate_RA_flip)
```

```{r}

## takes in four RDS and returns a DF containing p-values in rows for each tool

Comb_p_vals <- function(aldex,ancom,corncob,maaslin2, feat_list){
  aldex$feature <- rownames(aldex)
  aldex <- aldex[intersect(feat_list,rownames(aldex)),]
  ## we need to sort them all into the same order
  if(sum(grepl("Controlcase", colnames(aldex)))){
    aldex_sub <- aldex[,c('feature', 'model.Case.Controlcase Pr(>|t|)')]
  }else{
    aldex_sub <- aldex[,c('feature', 'model.Case.Control Pr(>|t|)')]
  }
  
  aldex_sub[,2] <- p.adjust(aldex_sub[,2], method="BH")
  
  ancom_sub <- ancom[,c('taxa_id', 'detected_0.8', 'detected_0.7')]
  rownames(ancom_sub) <- ancom_sub[,"taxa_id"]
  ancom_sub <- ancom_sub[intersect(feat_list,rownames(ancom_sub)),]
  
  ## have to clean up ancom_sub so that sig=0 and non-sig=1
  ancom_sub$detected_0.8 <- ifelse(ancom_sub$detected_0.8==TRUE, 0, 1)
  ancom_sub$detected_0.7 <- ifelse(ancom_sub$detected_0.7==TRUE, 0, 1)
  
  corncob_sub <- data.frame(feature=names(corncob$p),
                            p_fdr=corncob$p)
  
  rownames(corncob_sub) <- corncob_sub$feature
  
  corncob_sub <- corncob_sub[intersect(feat_list,rownames(corncob_sub)),]
  
  corncob_sub[,2] <- p.adjust(corncob_sub[,2], method="BH")
  ## fix corncob NAs and set them as 1 for our purpose... although this isn't totally correct...
  corncob_sub$p_fdr[is.na(corncob_sub$p_fdr)] <- 1

  maaslin2_p <- maaslin2[,c("feature", "pval")]
  rownames(maaslin2_p) <- maaslin2_p$feature
  maaslin2_p <- maaslin2_p[intersect(feat_list, rownames(maaslin2_p)),]
  maaslin2_p[,2] <- p.adjust(maaslin2_p[,2], method="BH")
  
  merge1 <- merge(x=aldex_sub, y=ancom_sub, by.x='feature', by.y='taxa_id', all=T)
  merge2 <- merge(x=merge1, y=corncob_sub, by.x='feature', by.y='feature', all=T)
  merge3 <- merge(x=merge2, y=maaslin2_p, by.x='feature', by.y='feature', all=T)
  merge3$detected_0.8[is.na(merge3$detected_0.8)] <- 1
  merge3$detected_0.7[is.na(merge3$detected_0.7)] <- 1
  merge3$pval[is.na(merge3$pval)] <- 1
  return(merge3)
  
}


Comb_est_vals <- function(aldex, ancom, corncob, maaslin2, feat_list, clr_tab, meta, bin=T){
  
  aldex$feature <- rownames(aldex)
  aldex <- aldex[intersect(feat_list,rownames(aldex)),]
  ## we need to sort them all into the same order
  if(sum(grepl("Controlcase", colnames(aldex)))){
    aldex_sub <- aldex[,c('feature', 'model.Case.Controlcase Estimate')]
  }else{
    aldex_sub <- aldex[,c('feature', 'model.Case.Control Estimate')]
  }
  
  message("done aldex")
  #ancom will need to be calculated from the CLR values as it does not by default output CLR values...
    
  clr_tab <- clr_tab[,feat_list]
  clr_tab$X <- rownames(clr_tab)
  
  clr_tab <- clr_tab %>% left_join(meta[,c("X", "Case.Control")])
  clr_tab <- clr_tab %>% group_by(Case.Control) %>% summarize_if(is.numeric, mean, na.rm=T)
  ancom_ests <- unlist(clr_tab[2,]) - unlist(clr_tab[1,])
  
  message("done ancom")
  
  corncob_sub <- extract_CC_Est(corncob)
  rownames(corncob_sub) <- corncob_sub$feat
  corncob_sub <- corncob_sub[intersect(feat_list, rownames(corncob_sub)),]
  
  maaslin2_p <- maaslin2[,c("feature", "coef")]
  rownames(maaslin2_p) <- maaslin2_p$feature
  maaslin2_p <- maaslin2_p[intersect(feat_list, rownames(maaslin2_p)),]
  message("done getting all tables now comb")

  comb_tab <- aldex_sub %>% full_join(data.frame(feature=names(ancom_ests), ancom_est=ancom_ests))
  comb_tab <- comb_tab %>% full_join(corncob_sub, by="feature")
  comb_tab <- comb_tab %>% full_join(maaslin2_p, by="feature")
  
  if(bin){
    
    comb_tab$aldex_bin <- sapply(comb_tab[,2], bin_cov)
    comb_tab$ancom_bin <- sapply(comb_tab[,3], bin_cov)
    comb_tab$cc_bin <- sapply(comb_tab[,4], bin_cov)
    comb_tab$ma_bin <- sapply(comb_tab[,5], bin_cov)
  }
  return(comb_tab)
}


bin_cov <- function(x){
  
  if(is.na(x)){
    return(x)
  }
  
  if(x > 0){
    x <- 1
  }else if(x < 0){
    x <- -1
  }

  
  return(x)
}

extract_CC_Est <- function(corncob){
  
  ret_df <- data.frame(feature=names(corncob$p))
  ret_df$cc_est <- NA
  for(i in 1:length(names(corncob$p))){
    if(is.na(corncob$all_models[[i]]))
      est_val <- NA
    else
      est_val <- corncob$all_models[[i]]$coefficients["mu.Case.Controlcase",1]
    
    ret_df[i,"cc_est"] <- est_val
  }
  
  return(ret_df)
}

## set non-sig estimates to 0

filt_non_sig_est <- function(pvals, ests, pval_thres){
  ret_ests <- ests
  
  stopifnot(identical(pvals[,1], ests[,1]))
  for(i in 1:nrow(pvals)){
    for(j in 2:ncol(pvals)){
      if(pvals[i,j] > pval_thres){
        ret_ests[i,j] <- 0
        ret_ests[i,j+4] <- 0
      }
    }
  }
  return(ret_ests)
}

```

# ASV heats

```{r}
make_all_three_heat <- function(list_abund, list_pval, list_est, log=F, display_val=F){
  
  heat_list <- list()
  
  max_abund=-1
  
  for(i in names(list_abund)){
    temp_abund <- get_max_abund(list_abund[[i]], log)
    if(temp_abund > max_abund)
      max_abund <- temp_abund
  }
  
  
  if(log){
        for(i in names(list_abund)){
          heat_list[[i]] <- heatmap_function(abund=list_abund[[i]], pval = list_pval[[i]], est=list_est[[i]], gradient = seq(-5, max_abund, by=0.1), main = i, show_row=F,
                                         show_legend = F, log=T, display_vals=display_val)
        }
  
  #draw labels
        labs_heat <- heatmap_function(abund=list_abund[[1]], pval = list_pval[[i]], est=list_est[[i]], gradient = seq(-5, max_abund, by=0.1), main = "", show_row=T,
                                         show_legend = T, log=T, display_vals=display_val)
  }else{
      for(i in names(list_abund)){
        heat_list[[i]] <- heatmap_function(abund=list_abund[[i]], pval = list_pval[[i]], est=list_est[[i]], gradient = seq(0, max_abund, by=0.001), main = i, show_row=F,
                                         show_legend = F, display_vals=display_val)
      }
  
  #draw labels
      labs_heat <- heatmap_function(abund=list_abund[[1]], pval = list_pval[[i]], est=list_est[[i]], gradient = seq(0, max_abund, by=0.001), main = "", show_row=T,
                                         show_legend = T, display_vals=display_val)
  }

  # not the best way to do this...
  row_labs <- labs_heat$gtable
  #row_labs <- gtable_remove_grobs(row_labs, "main")
  row_labs <- gtable_remove_grobs(row_labs, "matrix")
  row_labs <- gtable_remove_grobs(row_labs, "col_names")
  row_labs <- gtable_remove_grobs(row_labs, "row_annotation")
  row_labs <- gtable_remove_grobs(row_labs, "row_annotation_names")
  
  final_plot <- plot_grid(heat_list[[1]]$gtable, heat_list[[2]]$gtable, heat_list[[3]]$gtable, row_labs,
                          ncol=4, rel_widths = c(1,1,1,2))
  return(final_plot)
}


heatmap_function <- function(abund, pval, est, gradient, main, show_row=T, show_legend=T, log=F, display_vals=F){
  abund <- abund %>% select(-age_diff, -shannon_entropy, -pielou_evenness, -observed_features, -faith_pd, -CaseID)
  mean_abund <- abund %>% group_by(Case.Control) %>% summarize(across(where(is.numeric), ~ mean(.x))) %>% as.data.frame()
  mean_abund[mean_abund==0] <- NA
  rownames(mean_abund) <- mean_abund[,1]
  mean_abund <- mean_abund[,-1]
  mean_abund_flip <- t(mean_abund)
  # if(log){
  #     message(max(log(mean_abund_flip)))
  # }else{
  #     message(max(mean_abund_flip))
  # }

  
  mean_abund_flip_full <- data.frame(mean_abund_flip)
  mean_abund_flip_full$feature <- rownames(mean_abund_flip)
  
  
  #full_data <- mean_abund_flip_full %>% left_join(pval)
  #full_data <- full_data %>% select(-detected_0.8) %>% mutate_if(is.numeric, funs(ifelse(is.na(.), 1, .)))
  #full_data <- full_data %>% mutate_at(vars('model.Case.ControlCase Pr(>|t|)', 'detected_0.7', 'p_fdr', 'pval'),
                    #                                   function(x) ifelse(x <= 0.1, 1, 0))
  
  full_data <- mean_abund_flip_full %>% left_join(est)
  full_data <- full_data %>% mutate_if(is.numeric, funs(ifelse(is.na(.), 0, .)))
  
  
  rownames(full_data) <- full_data$feature
  
    
  colnames(full_data)[8:11] <- c("ALDEx2", "ANCOMII", "Corncob", "MaAsLin2")
  

  
  anno_cols <- list()
  ## possibly that all are postive or negative assocations...
  
  aldex2_range <- range(full_data$ALDEx2)
  ancom_range <- range(full_data$ANCOMII)
  corncob_range <- range(full_data$Corncob)
  maaslin_range <- range(full_data$MaAsLin2)
  
  if(identical(aldex2_range,c(-1, 1))){
    anno_cols[["ALDEx2"]] <- c("blue", "white", "red")
  }else if(identical(aldex2_range,c(-1, 0))){
        anno_cols[["ALDEx2"]] <- c("blue", "white")
  }else if(identical(aldex2_range,c(0, 0))){
        anno_cols[["ALDEx2"]] <- c("white")
  }else if(identical(aldex2_range,c(0, 1))){
        anno_cols[["ALDEx2"]] <- c("white", "red")
  }else if(identical(aldex2_range,c(-1,-1))){
        anno_cols[["ALDEx2"]] <- c("blue")
  }else if(identical(aldex2_range,c(1,1))){
        anno_cols[["ALDEx2"]] <- c("red")
  }

  if(identical(ancom_range,c(-1, 1))){
    anno_cols[["ANCOMII"]] <- c("blue", "white", "red")
  }else if(identical(ancom_range,c(-1, 0))){
        anno_cols[["ANCOMII"]] <- c("blue", "white")
  }else if(identical(ancom_range,c(0, 0))){
        anno_cols[["ANCOMII"]] <- c("white")
  }else if(identical(ancom_range,c(0, 1))){
        anno_cols[["ANCOMII"]] <- c("white", "red")
  }else if(identical(ancom_range,c(-1,-1))){
        anno_cols[["ANCOMII"]] <- c("blue")
  }else if(identical(ancom_range,c(1,1))){
        anno_cols[["ANCOMII"]] <- c("red")
  }
  
  if(identical(corncob_range,c(-1, 1))){
    anno_cols[["Corncob"]] <- c("blue", "white", "red")
  }else if(identical(corncob_range,c(-1, 0))){
        anno_cols[["Corncob"]] <- c("blue", "white")
  }else if(identical(corncob_range,c(0, 0))){
        anno_cols[["Corncob"]] <- c("white")
  }else if(identical(corncob_range,c(0, 1))){
        anno_cols[["Corncob"]] <- c("white", "red")
  }else if(identical(corncob_range,c(-1,-1))){
        anno_cols[["Corncob"]] <- c("blue")
  }else if(identical(corncob_range,c(1,1))){
        anno_cols[["Corncob"]] <- c("red")
  }

  if(identical(maaslin_range,c(-1, 1))){
    anno_cols[["MaAsLin2"]] <- c("blue", "white", "red")
  }else if(identical(maaslin_range,c(-1, 0))){
        anno_cols[["MaAsLin2"]] <- c("blue", "white")
  }else if(identical(maaslin_range,c(0, 0))){
        anno_cols[["MaAsLin2"]] <- c("white")
  }else if(identical(maaslin_range,c(0, 1))){
        anno_cols[["MaAsLin2"]] <- c("white")
  }else if(identical(maaslin_range,c(-1,-1))){
        anno_cols[["MaAsLin2"]] <- c("blue")
  }else if(identical(maaslin_range,c(1,1))){
        anno_cols[["MaAsLin2"]] <- c("red")
  }
  

  
  if(!show_row){
    row_labs <- rep("", nrow(mean_abund_flip))
  }else{
   row_labs <- rownames(mean_abund_flip)
  }
  if(log){
      pheatmap(log10(mean_abund_flip),
         cluster_cols = F,
         cluster_rows = F,
         angle_col=90,
         annotation_row = full_data[,8:11],
         annotation_colors = anno_cols,
         annotation_legend = FALSE,
         main=main,
         color= colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(gradient)),
         breaks=gradient,
         labels_row = row_labs,
         legend=show_legend,
         display_numbers = display_vals,
         na_col = "grey")
    
  }else{
      pheatmap(mean_abund_flip,
         cluster_cols = F,
         cluster_rows = F,
         angle_col=90,
         annotation_row = full_data[,8:11],
         annotation_colors = anno_cols,
         annotation_legend = FALSE,
         main=main,
         color= colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(gradient)),
         breaks=gradient,
         labels_row = row_labs,
         legend=show_legend,
         display_number=display_vals,
         number_format = "%.1e",
         na_col="grey")
  }

}

get_max_abund <- function(x, log=F){
  x <- x %>% select(-age_diff, -shannon_entropy, -pielou_evenness, -observed_features, -faith_pd, -CaseID)
  mean_abund <- x %>% group_by(Case.Control) %>% summarize(across(where(is.numeric), ~ mean(.x))) %>% as.data.frame()
  
  rownames(mean_abund) <- mean_abund[,1]
  mean_abund <- mean_abund[,-1]
  mean_abund_flip <- t(mean_abund)
  if(log)
    return(max(log10(mean_abund_flip)))
  return(max(mean_abund_flip))
  
}
```


# ASV

```{r}
Breast_ASVs <- rownames(asv_breast_filt)
Colon_ASVs <- rownames(asv_colon_filt)
Prostate_ASVs <- rownames(asv_prostate_filt)
```

```{r}
Comb_Breast_ASV <- Comb_p_vals(aldex = Breast_ASV_aldex, 
                               ancom = Breast_ASV_ancom$out, 
                               corncob = Breast_ASV_corncob, 
                               maaslin2 = Breast_ASV_maaslin2$results,
                               feat_list=Breast_ASVs)



Sig_Breast_ASV <- Comb_Breast_ASV %>% filter("model.Case.Controlcase Pr(>|t|)" < 0.05 | pval < 0.05 | p_fdr < 0.05 | detected_0.7 < 0.05) %>% 
  mutate_if(is.numeric, round, 4)

Breast_data$X <- as.character(Breast_data$X)

Comb_Breast_ASV_est <- Comb_est_vals(aldex = Breast_ASV_aldex,
                                     ancom = Breast_ASV_ancom$out,
                                     corncob = Breast_ASV_corncob,
                                     maaslin2 = Breast_ASV_maaslin2$results, 
                                     feat_list = Breast_ASVs, clr_tab = ASV_Breast_CLR_flip, meta = Breast_data, bin = T)


Sig_Breast_ASV_est <- Comb_Breast_ASV_est %>% filter(feature %in% Sig_Breast_ASV$feature)
Sig_Breast_ASV_est <- filt_non_sig_est(Sig_Breast_ASV[,-3], Sig_Breast_ASV_est, 0.05)

Comb_Prostate_ASV <- Comb_p_vals(aldex=Prostate_ASV_aldex,
                                 ancom=Prostate_ASV_ancom,
                                 corncob = Prostate_ASV_corncob,
                                 maaslin2 = Prostate_ASV_maaslin2$results,
                                 feat_list=Prostate_ASVs)

Sig_Prostate_ASV <- Comb_Prostate_ASV %>% filter("model.Case.Controlcase Pr(>|t|)" < 0.05 | pval < 0.05 | p_fdr < 0.05 | detected_0.7 < 0.05) %>% 
  mutate_if(is.numeric, round, 4)

Prostate_data$X <- as.character(Prostate_data$X)

Comb_Prostate_ASV_est <- Comb_est_vals(aldex=Prostate_ASV_aldex,
                                       ancom=Prostate_ASV_ancom,
                                       corncob = Prostate_ASV_corncob,
                                       maaslin2 = Prostate_ASV_maaslin2$results,
                                       feat_list = Prostate_ASVs, clr_tab = ASV_Prostate_CLR_flip, meta=Prostate_data, bin=T)

Sig_Prostate_ASV_est <- Comb_Prostate_ASV_est %>% filter(feature %in% Sig_Prostate_ASV$feature)



Comb_CRC_ASV <- Comb_p_vals(aldex=Colon_ASV_aldex,
                            ancom=Colon_ASV_ancom,
                            corncob = Colon_ASV_corncob,
                            maaslin2 = Colon_ASV_maaslin2$results,
                            feat_list=Colon_ASVs)

Sig_CRC_ASV <- Comb_CRC_ASV %>% filter("model.Case.Controlcase Pr(>|t|)" < 0.05 | pval < 0.05 | p_fdr < 0.05 |
                                         detected_0.7 < 0.05) %>% mutate_if(is.numeric, round, 4)

CRC_data$X <- as.character(CRC_data$X)

Comb_CRC_ASV_est <- Comb_est_vals(aldex = Colon_ASV_aldex,
                                  ancom= Colon_ASV_ancom,
                                  corncob = Colon_ASV_corncob,
                                  maaslin2 = Colon_ASV_maaslin2$results,
                                  feat_list = Colon_ASVs, clr_tab = ASV_CRC_CLR_flip, meta=CRC_data, bin=T)

Sig_CRC_ASV_est <- Comb_CRC_ASV_est %>% filter(feature %in% Sig_CRC_ASV$feature) %>% arrange(match(feature, Sig_CRC_ASV$feature))

Sig_CRC_ASV_est <- filt_non_sig_est(Sig_CRC_ASV[,-3], Sig_CRC_ASV_est, 0.05)
```


```{r}

all_sig_asvs <- c(Sig_Breast_ASV$feature, Sig_Prostate_ASV$feature, Sig_CRC_ASV$feature)
all_sig_asvs <- unique(all_sig_asvs)


Prostate_sig_abundances <- ASV_Prostate_RA_flip[,all_sig_asvs]
Breast_sig_abundances <- ASV_Breast_RA_flip[,all_sig_asvs]
Colon_sig_abundances <- ASV_CRC_RA_flip[,all_sig_asvs]

Prostate_sig_abundances$X <- rownames(Prostate_sig_abundances)
Breast_sig_abundances$X <- rownames(Breast_sig_abundances)
Colon_sig_abundances$X <- rownames(Colon_sig_abundances)
```

```{r}
Taxa_classifications <- read.table("~/Private/ATP/Analysis_21_12_01/taxa/taxonomy/taxonomy.tsv", sep="\t",
                                   header=T, stringsAsFactors = F)

Taxa_classifications$Taxon <- gsub(".*__(?=.*__)", "", Taxa_classifications$Taxon, perl=T)
Taxa_classifications$Taxon <- make.unique(Taxa_classifications$Taxon)


Rename_Prostate_sig_abundances <- Prostate_sig_abundances
Rename_Breast_sig_abundances <- Breast_sig_abundances
Rename_Colon_sig_abundances <- Colon_sig_abundances


colnames(Rename_Prostate_sig_abundances)[-ncol(Rename_Prostate_sig_abundances)] <- 
  Taxa_classifications$Taxon[match(colnames(Prostate_sig_abundances)[-ncol(Rename_Prostate_sig_abundances)], Taxa_classifications$Feature.ID)]


colnames(Rename_Breast_sig_abundances)[-ncol(Rename_Prostate_sig_abundances)] <- 
  Taxa_classifications$Taxon[match(colnames(Breast_sig_abundances)[-ncol(Rename_Prostate_sig_abundances)], Taxa_classifications$Feature.ID)]

colnames(Rename_Colon_sig_abundances)[-ncol(Rename_Colon_sig_abundances)] <- Taxa_classifications$Taxon[match(colnames(Colon_sig_abundances)[-ncol(Rename_Colon_sig_abundances)], Taxa_classifications$Feature.ID)]

Rename_Sig_Breast_ASV <- Sig_Breast_ASV
Rename_Sig_Prostate_ASV <- Sig_Prostate_ASV
Rename_Sig_Colon_ASV <- Sig_CRC_ASV

Rename_Sig_Breast_ASV$feature <- Taxa_classifications$Taxon[match(Sig_Breast_ASV$feature, Taxa_classifications$Feature.ID)]
Rename_Sig_Prostate_ASV$feature <- Taxa_classifications$Taxon[match(Sig_Prostate_ASV$feature, Taxa_classifications$Feature.ID)]
Rename_Sig_Colon_ASV$feature <- Taxa_classifications$Taxon[match(Sig_CRC_ASV$feature, Taxa_classifications$Feature.ID)]

Rename_Sig_Breast_ASV_est <- Sig_Breast_ASV_est
Rename_Sig_Prostate_ASV_est <- Sig_Prostate_ASV_est
Rename_Sig_Colon_ASV_est <- Sig_CRC_ASV_est

Rename_Sig_Breast_ASV_est$feature <- Taxa_classifications$Taxon[match(Sig_Breast_ASV_est$feature, Taxa_classifications$Feature.ID)]

Rename_Sig_Prostate_ASV_est$feature <- Taxa_classifications$Taxon[match(Sig_Prostate_ASV_est$feature, Taxa_classifications$Feature.ID)]

Rename_Sig_Colon_ASV_est$feature <- Taxa_classifications$Taxon[match(Sig_CRC_ASV_est$feature, Taxa_classifications$Feature.ID)]


Prostate_data$X <- as.character(Prostate_data$X)
Full_Prostate_data <- Prostate_data %>% full_join(Rename_Prostate_sig_abundances, by="X")

Breast_data$X <- as.character(Breast_data$X)
Full_Breast_Data <- Breast_data %>% full_join(Rename_Breast_sig_abundances, by="X")

CRC_data$X <- as.character(CRC_data$X)
Full_Colon_Data <- CRC_data %>% full_join(Rename_Colon_sig_abundances, by="X")

ASV_abund_list <- list(
  Breast=Full_Breast_Data,
  Prostate=Full_Prostate_data,
  Colon=Full_Colon_Data
)


ASV_p_list <- list(
  Breast=Rename_Sig_Breast_ASV,
  Prostate=Rename_Sig_Prostate_ASV,
  Colon=Rename_Sig_Colon_ASV
)

ASV_est_list <- list(
  Breast=Rename_Sig_Breast_ASV_est,
  Prostate=Rename_Sig_Prostate_ASV_est,
  Colon=Rename_Sig_Colon_ASV_est
)


test <- heatmap_function(Full_Colon_Data, Rename_Sig_Colon_ASV, Rename_Sig_Colon_ASV_est, main="", show_row = T,
                         show_legend = T, log=T, display_vals = T, gradient = seq(-5, 0, by=0.1))

test


asv_da_heat <- make_all_three_heat(list_abund = ASV_abund_list, list_pval = ASV_p_list, list_est = ASV_est_list, log = T, display_val = T)

asv_da_heat

saveRDS(asv_da_heat, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Pro_ATP_asv_DA_heat.RDS")
```

# Genus Heatmap


No Significant Genera


```{r}
Breast_genus <- rownames(genera_breast_filt)
Prostate_genus <- rownames(genera_prostate_filt)
CRC_genus <- rownames(genera_colon_filt)
```

```{r}
Comb_Breast_Genera <- Comb_p_vals(aldex = Breast_GENUS_aldex, 
                               ancom = Breast_GENUS_ancom$out, 
                               corncob = Breast_GENUS_corncob, 
                               maaslin2 = Breast_GENUS_maaslin2$results,
                               feat_list = Breast_genus)


Sig_Breast_Genera <- Comb_Breast_Genera %>% filter("model.Case.Controlcase Pr(>|t|)" < 0.05 | pval < 0.05 | p_fdr < 0.05 | detected_0.7 < 0.05) %>% mutate_if(is.numeric, round, 4)

Sig_Breast_Genera
#none

Comb_Prostate_Genus <- Comb_p_vals(aldex=Prostate_GENUS_aldex,
                                 ancom=Prostate_GENUS_ancom,
                                 corncob = Prostate_GENUS_corncob,
                                 maaslin2 = Prostate_GENUS_maaslin2$results,
                                 feat_list = Prostate_genus)

Sig_Prostate_Genus <- Comb_Prostate_Genus %>% filter("model.Case.Controlcase Pr(>|t|)" < 0.05 | pval < 0.05 | detected_0.7 < 0.05 | p_fdr < 0.05) %>%
  mutate_if(is.numeric, round, 4)

Sig_Prostate_Genus
#none

Comb_CRC_Genus <- Comb_p_vals(aldex=Colon_GENUS_aldex,
                              ancom=Colon_GENUS_ancom$out,
                              corncob = Colon_GENUS_corncob,
                              maaslin2 = Colon_GENUS_maaslin2$results,
                              feat_list = CRC_genus)

Sig_CRC_Genus <- Comb_CRC_Genus %>% filter("model.Case.Controlcase Pr(>|t|)" < 0.05 | pval < 0.05 | p_fdr < 0.05 | detected_0.7 < 0.05) %>% mutate_if(is.numeric, round, 4)

Sig_CRC_Genus
#none
```




# Combined_plots

```{r}
make_comb_plots <- function(df){
  plot_list <- list()
  
  for(i in 10:ncol(df)){
    temp_df <- df
    colnames(temp_df)[i] <- "plot_var"
    plot_list[[colnames(df)[i]]] <- make_plot(temp_df)
    
  }
  return(plot_list)
}

make_plot <- function(df){
  
  ret_plot <- df %>% ggplot(aes(x=Case.Control, y=log10(plot_var + 0.00001))) +
    geom_violin(alpha=0.2, aes(fill=Case.Control)) +
    geom_quasirandom(alpha=0.2) +
    geom_boxplot(width=0.1, alpha=1, outlier.alpha = 0, aes(fill=Case.Control)) +
    xlab("") +
    ylab("log10(RA)") +
    facet_wrap(~ Type) +
    theme_cowplot()
  
  return(ret_plot)
}

```


## ASV



```{r}
Comb_ASV_data <- Full_Breast_Data %>% full_join(Full_Prostate_data) %>% full_join(Full_Colon_Data)
Comb_ASV_plots <- make_comb_plots(Comb_ASV_data)
Comb_ASV_plots[[1]]



saveRDS(Comb_ASV_plots, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS/Pro_ATP_ASV_box.RDS")
```



```{r}
sup_fig <- plot_grid(Comb_ASV_plots[[1]] + ggtitle("Stomatobaculum uncultured") + theme(legend.position = "none"),
                     Comb_ASV_plots[[2]] + ggtitle("Prevotella loescheii") + theme(legend.position = "none"),
                     Comb_ASV_plots[[3]] + ggtitle("Alloprevotella rava") + theme(legend.position = "none"),
                     nrow=3)

sup_fig_leg <- plot_grid(sup_fig,
                         get_legend(Comb_ASV_plots[[1]]),
                         nrow=1,
                         rel_widths = c(1,.1))
sup_fig_leg
```