---
title: "Pro_PATH_RF_Model_Performance_caret"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(caret)
library(pROC)
library(dplyr)

library(cvAUC)

library(cowplot)
library(randomForest)
library(ggbeeswarm)
library(reshape2)

col_list <- col_list <- c('#b74a8c',
              '#8c7029',
              '#7464c0',
              '#ac5a51')

make_pROC_curve_mean <- function(list_of_models, col_list, legend=F){
  
  text_pos <- c(0.3,0.25,0.2,0.15)
  add <- F
  
  roc_list <- list()
  for(i in 1:length(list_of_models)){
    name <- names(list_of_models)[i]
    mean_votes <- list_of_models[[i]]$pred %>% group_by(rowIndex) %>% summarize_if(is.numeric, list(name=mean))
    mean_votes$obs <- list_of_models[[i]]$trainingData$.outcome[mean_votes$rowIndex]
    
    temp_roc <- roc(response=mean_votes$obs, predictor = mean_votes$Case_name, ci=T, levels=c("Control", "Case"),
                    direction="<")
    roc_list[[name]] <- temp_roc
  }
  ci.list <- lapply(roc_list, ci.se, specificities=seq(0,1,0.05))
  
  dat.ci.list <- lapply(ci.list, function(ciobj)
    data.frame(x=as.numeric(rownames(ciobj)),
               lower=ciobj[,1],
               upper=ciobj[,3]))
  
  dat.auc.list <- lapply(roc_list, function(x)
    data.frame(lower=x$ci[1],
               mid=x$ci[2],
               upper=x$ci[3]))
  
  p <- ggroc(roc_list) + theme_minimal() + 
   geom_abline(slope=1, intercept = 1, linetype = "dashed", alpha=0.7, color = "grey") +
   coord_equal() +
     scale_color_manual("Feature type", values=col_list) +
     scale_fill_manual("Feature type", values=col_list)
  


  
  for(i in 1:length(dat.ci.list)) {
    dat.ci.list[[i]]$name <- factor(names(dat.ci.list)[i], levels=c("ASV RA", "ASV CLR", "Genus CLR", "Genus RA"))
    
    p <- p + geom_ribbon(
      data = dat.ci.list[[i]],
      aes(x = x, ymin = lower, ymax = upper, fill=name),
      alpha = .1,
      inherit.aes = F)
  
    dat.auc.list[[i]]$name <- factor(names(dat.ci.list)[i], levels=c("ASV RA", "ASV CLR", "Genus CLR", "Genus RA"))
    

    p <- p + geom_text(
      data=dat.auc.list[[i]],
      aes(x=.25,
          label = paste("AUC: ", round(mid, 3), " (", round(lower, 3), " - ", round(upper, 3), ")", sep=""),
          color=name),
      inherit.aes=F,
      y=text_pos[i],
      show.legend=FALSE)
    message(text_pos[i])
  } 
  
  return(p)
}


```


# ROC Models

## Breast
```{r}
Br_ASV_RA <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/ASV_RCV_caret.RDS")
Br_ASV_CLR <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/ASV_RCV_CLR_caret.RDS")

Br_Genus_RA <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/Genus_RCV_RA_caret.RDS")
Br_Genus_CLR <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Breast/Genus_RCV_CLR_caret.RDS")


Br_models <- list("ASV CLR"=Br_ASV_CLR, 
                  "ASV RA"=Br_ASV_RA, 
                  "Genus CLR"=Br_Genus_CLR, 
                  "Genus RA"=Br_Genus_RA)

Br_plot_mean <- make_pROC_curve_mean(Br_models, col_list)
Br_plot_mean
```

## Prostate
```{r}
Pr_ASV_RA <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/ASV_RCV_RA_caret.RDS")
Pr_ASV_CLR <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/ASV_RCV_CLR_caret.RDS")

Pr_Genus_RA <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/Genus_RCV_RA_caret.RDS")
Pr_Genus_CLR <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/Prostate/Genus_RCV_CLR_caret.RDS")


Pr_models <- list("ASV CLR"=Pr_ASV_CLR, 
                  "ASV RA"=Pr_ASV_RA, 
                  "Genus CLR"=Pr_Genus_CLR, 
                  "Genus RA"=Pr_Genus_RA)

Pr_plot <- make_pROC_curve_mean(Pr_models, col_list)
Pr_plot

```

## Colon
```{r}
Cr_ASV_RA <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/ASV_RCV_RA_caret.RDS")
Cr_ASV_CLR <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/ASV_RCV_CLR_caret.RDS")

Cr_Genus_RA <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/Genus_RCV_RA_caret.RDS")
Cr_Genus_CLR <- readRDS("~/Private/CHAPTER_4/Prospec/PATH/Random_Forest/CRC/Genus_RCV_CLR_caret.RDS")

Cr_models <- list("ASV CLR"=Cr_ASV_CLR, 
                  "ASV RA"=Cr_ASV_RA, 
                  "Genus CLR"=Cr_Genus_CLR, 
                  "Genus RA"=Cr_Genus_RA)


Cr_plot_mean <- make_pROC_curve_mean(Cr_models, col_list)
Cr_plot_mean

saveRDS(Cr_plot_mean, "~/Private/CHAPTER_4/Publication_Markdowns/Display_items/intermediate_RDS2/Cr_plot_PATH_caret.RDS")
```

## Final Plot
```{r}
Ret_AUC_plot <- plot_grid(Br_plot_mean + ggtitle("Breast") + 
                            theme(legend.position = "none", plot.title = element_text(hjust=0.5)), 
                          Pr_plot + ggtitle("Prostate") + 
                            theme(legend.position = "none", plot.title = element_text(hjust=0.5)), 
                          # Cr_plot_mean + ggtitle("Colon") + 
                          #   theme(legend.position = "none", plot.title = element_text(hjust=0.5)), 
                          nrow=1, labels=c("A", "B"),
                          label_y=.1)

Ret_AUC_plot

Ret_AUC_plot_leg <- plot_grid(NULL,
                              Ret_AUC_plot, 
                              NULL,
                              get_legend(Br_plot_mean + theme(legend.position = "bottom")),
                              nrow=4,
                              rel_heights = c(-.3, 1,-.4, .2))
Ret_AUC_plot_leg

```