---
title: "ANCOM_Analysis"
author: "Jacob T. Nearing"
date: "4/23/2021"
output: 
  rmdformats::downcute:
    self_contained: true
    default_style: "light"
    downcute_theme: "chaos"
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(exactRankTests)
library(nlme)
library(dplyr)
library(ggplot2)
library(compositions)
library(kableExtra)
library(beeswarm)

source("~/GitHub_Repos/Clean_Hackathon/Pipeline_scripts/Ancom2_Script/ancom_v2.1.R")



remove_rare_features <- function( table , cutoff_pro=0.1, parallel=1 ) {
  if(cutoff_pro<=0){
    message("No filtering will be done due to cutoff_pro set to 0 or below")
    return(table)
  }
  row2keep <- c()
  cutoff <- ceiling( cutoff_pro * ncol(table) )
  if(parallel <= 1){
    for ( i in 1:nrow(table) ) {
      row_nonzero <- length( which( table[ i , ]  > 0 ) )
      if ( row_nonzero > cutoff ) {
        row2keep <- c( row2keep , i)
      }
    }
    return( table [ row2keep , , drop=F ])
  }else{
    `%dopar%` <- foreach::`%dopar%`
    cl <- parallel::makeCluster(parallel)
    doParallel::registerDoParallel(cl)
    message("Running with: ", foreach::getDoParWorkers(), " cores")

    res <- foreach::foreach(i = 1:nrow(table), .combine = c) %dopar% {
      row_nonzero <- length( which ( table[ i , ] > 0))
      if(row_nonzero > cutoff){
        i
      }else
        NULL
    }
    parallel::stopCluster(cl)
    return( table[res, , drop=F])

  }

}

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="Case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="Case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="Control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}
```

```{r load_metadata}

Metadata_Breast <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Breast_21_03_11.csv", row.names = 1)
Metadata_CRC <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_CRC_21_03_11.csv", row.names = 1)
Metadata_Prostate <- read.csv("~/Private/Previous_Cancer_Project/Metadata/Metadata_Prostate_21_03_11.csv", row.names = 1)


### Load in alpha data

Alpha_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_Breast.RDS")
Alpha_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_CRC.RDS")
Alpha_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Alpha_data_prostate.RDS")


Metadata_Breast <- Metadata_Breast[rownames(Alpha_Breast),]
Metadata_CRC <- Metadata_CRC[rownames(Alpha_CRC),]
Metadata_Prostate <- Metadata_Prostate[rownames(Alpha_Prostate),]

Metadata_Breast_Cases <- Metadata_Breast[which(Metadata_Breast$Case.Control==1),]
Metadata_CRC_Cases <- Metadata_CRC[which(Metadata_CRC$Case.Control==1),]
Metadata_Prostate_Cases <- Metadata_Prostate[which(Metadata_Prostate$Case.Control==1),]

Alpha_Breast_Cases <- Alpha_Breast[rownames(Metadata_Breast_Cases),]
Alpha_CRC_Cases <- Alpha_CRC[rownames(Metadata_CRC_Cases),]
Alpha_Prostate_Cases <- Alpha_Prostate[rownames(Metadata_Prostate_Cases),]

Alpha_Breast$X <- rownames(Alpha_Breast)
Breast_data <- Alpha_Breast %>% left_join(Metadata_Breast, by="X")
Breast_data$Case.Control <- ifelse(Breast_data$Case.Control==1, "Case", "Control")

Alpha_Prostate$X <- rownames(Alpha_Prostate)
Prostate_data <- Alpha_Prostate %>% left_join(Metadata_Prostate, by="X")
Prostate_data$Case.Control <- ifelse(Prostate_data$Case.Control==1, "Case", "Control")

Alpha_CRC$X <- rownames(Alpha_CRC)
CRC_data <- Alpha_CRC %>% left_join(Metadata_CRC, by="X")
CRC_data$Case.Control <- ifelse(CRC_data$Case.Control==1, "Case", "Control")

Alpha_Breast_Cases$X <- rownames(Alpha_Breast_Cases)
Breast_case_data <- Alpha_Breast_Cases %>% left_join(Metadata_Breast_Cases, by="X")
Breast_case_data$Case.Control <- ifelse(Breast_case_data$Case.Control==1, "Case", "Control")

Alpha_Prostate_Cases$X <- rownames(Alpha_Prostate_Cases)
Prostate_case_data <- Alpha_Prostate_Cases %>% left_join(Metadata_Prostate_Cases, by="X")
Prostate_case_data$Case.Control <- ifelse(Prostate_case_data$Case.Control==1, "Case", "Control")

Alpha_CRC_Cases$X <- rownames(Alpha_CRC_Cases)
CRC_case_data <- Alpha_CRC_Cases %>% left_join(Metadata_CRC_Cases, by="X")
CRC_case_data$Case.Control <- ifelse(CRC_case_data$Case.Control==1, "Case", "Control")


Breast_data$age_diff <- Breast_data$YEARS_SINCE_BC
Prostate_data$age_diff <- Prostate_data$YEARS_SINCE_PC
CRC_data$age_diff <- CRC_data$YEARS_SINCE_CRC_CANCER

Breast_data$Type <- "Breast"
Prostate_data$Type <- "Prostate"
CRC_data$Type <- "Colon"

Breast_data$Case.Control <- factor(Breast_data$Case.Control, levels=c("Control", "Case"))
Prostate_data$Case.Control <- factor(Prostate_data$Case.Control, levels=c("Control", "Case"))
CRC_data$Case.Control <- factor(CRC_data$Case.Control, levels=c("Control","Case"))

Breast_data <- remove_non_matching_caseIDS(Breast_data)
Prostate_data <- remove_non_matching_caseIDS(Prostate_data)
CRC_data <- remove_non_matching_caseIDS(CRC_data)

Breast_data_comb <- Breast_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)
Prostate_data_comb <- Prostate_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)
CRC_data_comb <- CRC_data %>% select(faith_pd, shannon, pielou_e, observed_otus, X, Case.Control, age_diff, Type, CaseID, Extraction_Number)


Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)

Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r load_feature_data}

ASV_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_breast.RDS")
ASV_Breast <- ASV_Breast[-which(rowSums(ASV_Breast)==0),]

ASV_Breast <- ASV_Breast[,Breast_data$X]


ASV_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_CRC.RDS")
ASV_CRC <- ASV_CRC[-which(rowSums(ASV_CRC)==0),]
ASV_CRC <- ASV_CRC[,CRC_data$X]


ASV_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/ASV_table_Prostate.RDS")
ASV_Prostate <- ASV_Prostate[-which(rowSums(ASV_Prostate)==0),]
ASV_Prostate <- ASV_Prostate[,Prostate_data$X]



## load in Genus
Genus_Breast <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_breast.RDS")
Genus_Breast <- Genus_Breast[-which(rowSums(Genus_Breast)==0),]
Genus_Breast <- Genus_Breast[,Breast_data$X]


Genus_CRC <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_CRC.RDS")
Genus_CRC <- Genus_CRC[-which(rowSums(Genus_CRC)==0),]
Genus_CRC <- Genus_CRC[,CRC_data$X]

Genus_Prostate <- readRDS("~/Private/Previous_Cancer_Project/Data/Genus_table_prostate.RDS")
Genus_Prostate <- Genus_Prostate[-which(rowSums(Genus_Prostate)==0),]
Genus_Prostate <- Genus_Prostate[,Prostate_data$X]

```



# Breast Cancer

## ASVs {.tabset}

```{r}
identical(Breast_data$X, colnames(ASV_Breast_filt))

prepro_breast_ASV <- feature_table_pre_process(feature_table = ASV_Breast, meta_data = Breast_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_breast_ASV <- ANCOM(feature_table = prepro_breast_ASV$feature_table,
                        meta_data = prepro_breast_ASV$meta_data,
                        struc_zero = prepro_breast_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_breast_ASV$out, "~/Private/CHAPTER_4/Retero/PATH/DA_Analysis/data/Breast/ASV_ANCOM2.RDS")
```

## Genus
```{r}
prepro_breast_Genus <- feature_table_pre_process(feature_table = Genus_Breast, meta_data = Breast_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_breast_Genus <- ANCOM(feature_table = prepro_breast_Genus$feature_table,
                          meta_data=prepro_breast_Genus$meta_data,
                          struc_zero = prepro_breast_Genus$structure_zeros,
                          main_var='Case.Control',
                          p_adj_method = 'BH',
                          alpha=0.05,
                          adj_formula = 'Extraction_Number',
                          rand_formula = NULL)

saveRDS(res_breast_Genus$out, "~/Private/CHAPTER_4/Retero/PATH/DA_Analysis/data/Breast/Genus_ANCOM2.RDS")
```

# Prostate Cancer

## ASV
```{r}

identical(Prostate_data$X, colnames(ASV_Prostate_filt))

prepro_prostate_ASV <- feature_table_pre_process(feature_table = ASV_Prostate, meta_data = Prostate_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)


res_prostate_ASV <- ANCOM(feature_table = prepro_prostate_ASV$feature_table,
                        meta_data = prepro_prostate_ASV$meta_data,
                        struc_zero = prepro_prostate_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_prostate_ASV$out, "~/Private/CHAPTER_4/Retero/PATH/DA_Analysis/data/Prostate/ASV_ANCOM2.RDS")
```

## Genus
```{r}

prepro_prostate_Genus <- feature_table_pre_process(feature_table = Genus_Prostate, meta_data = Prostate_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_prostate_Genus <- ANCOM(feature_table = prepro_prostate_Genus$feature_table,
                        meta_data = prepro_prostate_Genus$meta_data,
                        struc_zero = prepro_prostate_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_prostate_Genus$out, "~/Private/CHAPTER_4/Retero/PATH/DA_Analysis/data/Prostate/Genus_ANCOM2.RDS")
```


# CRC Analysis

## ASV {.tabset}

```{r}

identical(CRC_data$X, colnames(ASV_CRC_filt))


prepro_CRC_ASV <- feature_table_pre_process(feature_table = ASV_CRC, meta_data = CRC_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_CRC_ASV <- ANCOM(feature_table = prepro_CRC_ASV$feature_table,
                        meta_data = prepro_CRC_ASV$meta_data,
                        struc_zero = prepro_CRC_ASV$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_CRC_ASV$out, "~/Private/CHAPTER_4/Retero/PATH/DA_Analysis/data/Colon/ASV_ANCOM2.RDS")
```

## Genus

```{r}
prepro_CRC_Genus <- feature_table_pre_process(feature_table = Genus_CRC, meta_data = CRC_data, sample_var = 'X',
                                    group_var = "Case.Control", out_cut = 0.05, zero_cut = 0.90,
                                    lib_cut = 1000, neg_lb=FALSE)

res_CRC_Genus <- ANCOM(feature_table = prepro_CRC_Genus$feature_table,
                        meta_data = prepro_CRC_Genus$meta_data,
                        struc_zero = prepro_CRC_Genus$structure_zeros,
                        main_var = 'Case.Control',
                        p_adj_method = 'BH',
                        alpha=0.05,
                        adj_formula = 'Extraction_Number',
                        rand_formula = NULL)

saveRDS(res_CRC_Genus$out, "~/Private/CHAPTER_4/Retero/PATH/DA_Analysis/data/Colon/Genus_ANCOM2.RDS")
```

