---
title: "Breast_RF_LOOCV"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(dplyr)
library(readxl)
library(reshape2)
library(randomForest)
library(cvAUC)
library(caret)
library(doMC)
library(rfUtilities)
library(pROC)

library(doParallel)

cl <- makePSOCKcluster(40)
registerDoParallel(cl)



remove_rare_features <- function( table , cutoff_pro=0.1, parallel=1 ) {
  if(cutoff_pro<=0){
    message("No filtering will be done due to cutoff_pro set to 0 or below")
    return(table)
  }
  row2keep <- c()
  cutoff <- ceiling( cutoff_pro * ncol(table) )
  if(parallel <= 1){
    for ( i in 1:nrow(table) ) {
      row_nonzero <- length( which( table[ i , ]  > 0 ) )
      if ( row_nonzero > cutoff ) {
        row2keep <- c( row2keep , i)
      }
    }
    return( table [ row2keep , , drop=F ])
  }else{
    `%dopar%` <- foreach::`%dopar%`
    cl <- parallel::makeCluster(parallel)
    doParallel::registerDoParallel(cl)
    message("Running with: ", foreach::getDoParWorkers(), " cores")

    res <- foreach::foreach(i = 1:nrow(table), .combine = c) %dopar% {
      row_nonzero <- length( which ( table[ i , ] > 0))
      if(row_nonzero > cutoff){
        i
      }else
        NULL
    }
    parallel::stopCluster(cl)
    return( table[res, , drop=F])

  }

}

remove_non_matching_caseIDS <- function(df){
  
    ## remove controls that don;t have associated case samples b/c they were removed due to poor sequencing
    df_cases <- df %>% filter(Case.Control=="case")
    CaseIDs <- df_cases$CaseID
    df_filt <- df %>% filter(CaseID %in% CaseIDs)

    ## remove cases that don't have any controls associtated because they were removed due to poor sequencing 
    ## these cases can only happen when the total number of samples with that CASEID is 1 
    Summ_data <- df_filt %>% group_by(CaseID) %>% summarize(n())
    remove_cases <- Summ_data$CaseID[which(Summ_data$`n()`==1)]
    
    if(length(remove_cases!=0)){
      message(paste0("removing ", remove_cases, " Case samples due to no controls"))
      test <- df_filt[-which(df_filt$CaseID %in% remove_cases),]
      return(test)  
    }

    
    return(df_filt)
  
}

match_age_diff <- function(df){
  
  case_df <- df %>% filter(Case.Control=="case")
  for(i in 1:nrow(df)){
    
    if(is.na(df[i,'age_diff']) & df[i,'Case.Control']=="control"){
      temp_caseID <- df[i,'CaseID']
      message(temp_caseID)
      temp_age_diff <- case_df$age_diff[which(case_df$CaseID==temp_caseID)]
      message(temp_age_diff)
      df[i,'age_diff'] <- temp_age_diff
    }
  }
  return(df)
}
```

```{r}
base_metadata <- readRDS("~/Private/ATP/Metadata/Base_microbiome_metadata.RDS")
base_metadata$ParticipantKey <- as.character(base_metadata$ParticipantKey)
rownames(base_metadata) <- base_metadata$researcher



sheet_names <- c("ACR", "ACR_Treatment", "Core", "Core_Chronic", "HLQ", "Master_Data", "Case_Control_Match", "PANS", "PM_data", "UHLQ", "UHLQ_Cond")

Metadata <- list()

for(i in 1:length(sheet_names)){
  
  Metadata[[sheet_names[i]]] <- read_excel("~/Private/ATP/Metadata/ATP_MASTER_DATA.xls", sheet=i)
  
}


Metadata[[7]]$matchID <- seq(1:207)

case_control_match <- melt(Metadata[[7]][,-3], id.vars = 'matchID')



Shannon_div <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/shannon.tsv",
                          sep="\t", header=T)
colnames(Shannon_div)[1] <- "researcher"

#faith pd
faith_pd <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/faiths_pd.tsv",
                       sep="\t", header=T)
colnames(faith_pd)[1] <- "researcher"

#raw richness
richness <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/observed_feats.tsv",
                       sep="\t", header=T)
colnames(richness)[1] <- "researcher"

#evenness
evenness <- read.table("~/Private/ATP/Analysis_21_12_01/core-div-3000/raw_alpha/evenness.tsv",
                       sep="\t", header=T)
colnames(evenness)[1] <- "researcher"


## 40 samples did not reach sequencing requirements.
Alpha_div <- Shannon_div %>% left_join(faith_pd, by="researcher") %>% left_join(richness, by="researcher") %>% left_join(evenness, by="researcher")


Full_data <- Alpha_div %>% inner_join(base_metadata, by="researcher")
Full_data$Case.Control <- factor(Full_data$ARM.x, levels=c("control", "case"))



Alpha_Breast <- Full_data %>% filter(Type=="Breast")
Alpha_Prostate <- Full_data %>% filter(Type=="Prostate")
Alpha_CRC <- Full_data %>% filter(Type=="Colon") 

Alpha_Breast$X <- Alpha_Breast$researcher
Alpha_Prostate$X <- Alpha_Prostate$researcher
Alpha_CRC$X <- Alpha_CRC$researcher

Alpha_Breast$CaseID <- case_control_match$matchID[match(Alpha_Breast$ParticipantKey, case_control_match$value)]
Alpha_Prostate$CaseID <- case_control_match$matchID[match(Alpha_Prostate$ParticipantKey, case_control_match$value)]
Alpha_CRC$CaseID <- case_control_match$matchID[match(Alpha_CRC$ParticipantKey, case_control_match$value)]

Alpha_Breast <- remove_non_matching_caseIDS(Alpha_Breast)
Alpha_Prostate <- remove_non_matching_caseIDS(Alpha_Prostate)
Alpha_CRC <- remove_non_matching_caseIDS(Alpha_CRC)

Breast_data_comb <- Alpha_Breast %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

Prostate_data_comb <- Alpha_Prostate %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

CRC_data_comb <- Alpha_CRC %>% select(faith_pd, shannon_entropy, pielou_evenness, observed_features, X, Case.Control, age_diff, Type, CaseID)

Combined_data <- rbind(Breast_data_comb, Prostate_data_comb, CRC_data_comb)


Breast_data <- Combined_data %>% filter(Type=="Breast")
CRC_data <- Combined_data %>% filter(Type=="Colon")
Prostate_data <- Combined_data %>% filter(Type=="Prostate")
```

```{r}

genera <- read.table("~/Private/ATP/Analysis_21_12_01/taxa_tabs/level6_tabs/feature-tab.tsv",
                     sep="\t", comment.char="", skip=1, header=T, check.names = F, row.names = 1)

ASV <- read.table("~/Private/ATP/Analysis_21_12_01/deblur_output/asv_table/feature-table.tsv",
                  sep="\t", comment.char = "", skip=1, header=T, check.names = F, row.names = 1)

genera_breast <- genera[,as.character(Breast_data$X)]
genera_prostate <- genera[,as.character(Prostate_data$X)]
genera_colon <- genera[,as.character(CRC_data$X)]

asv_breast <- ASV[,as.character(Breast_data$X)]
asv_prostate <- ASV[,as.character(Prostate_data$X)]
asv_colon <- ASV[,as.character(CRC_data$X)]
```


```{r}
ASV_Breast_CLR <- data.frame(apply(asv_breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_CRC_CLR <- data.frame(apply(asv_colon + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
ASV_Prostate_CLR <- data.frame(apply(asv_prostate + 1, 2, function(x){log(x) - mean (log(x))}), check.names = F)

ASV_Breast_CLR_flip <- data.frame(t(ASV_Breast_CLR), check.names = F)
ASV_Breast_CLR_flip$X <- rownames(ASV_Breast_CLR_flip)

ASV_CRC_CLR_flip <- data.frame(t(ASV_CRC_CLR), check.names = F)
ASV_CRC_CLR_flip$X <- rownames(ASV_CRC_CLR_flip)

ASV_Prostate_CLR_flip <- data.frame(t(ASV_Prostate_CLR), check.names = F)
ASV_Prostate_CLR_flip$X <- rownames(ASV_Prostate_CLR_flip)

Genus_Breast_CLR <- data.frame(apply(genera_breast + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_CRC_CLR <- data.frame(apply(genera_colon + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)
Genus_Prostate_CLR <- data.frame(apply(genera_prostate + 1, 2, function(x){log(x) - mean(log(x))}), check.names = F)

Genus_Breast_CLR_flip <- data.frame(t(Genus_Breast_CLR), check.names = F)
Genus_Breast_CLR_flip$X <- rownames(Genus_Breast_CLR_flip)

Genus_CRC_CLR_flip <- data.frame(t(Genus_CRC_CLR), check.names = F)
Genus_CRC_CLR_flip$X <- rownames(Genus_CRC_CLR_flip)

Genus_Prostate_CLR_flip <- data.frame(t(Genus_Prostate_CLR), check.names = F)
Genus_Prostate_CLR_flip$X <- rownames(Genus_Prostate_CLR_flip)


ASV_Breast_RA <- sweep(asv_breast, 2, colSums(asv_breast), '/')
ASV_CRC_RA <- sweep(asv_colon, 2, colSums(asv_colon), '/')
ASV_Prostate_RA <- sweep(asv_prostate, 2, colSums(asv_prostate), '/')

ASV_Breast_RA_flip <- data.frame(t(ASV_Breast_RA), check.names=F)
ASV_Breast_RA_flip$X <- rownames(ASV_Breast_RA_flip)

ASV_CRC_RA_flip <- data.frame(t(ASV_CRC_RA), check.names = F)
ASV_CRC_RA_flip$X <- rownames(ASV_CRC_RA_flip)

ASV_Prostate_RA_flip <- data.frame(t(ASV_Prostate_RA), check.names = F)
ASV_Prostate_RA_flip$X <- rownames(ASV_Prostate_RA_flip)

Genus_Breast_RA <- sweep(genera_breast, 2, colSums(genera_breast), '/')
Genus_CRC_RA <- sweep(genera_colon, 2, colSums(genera_colon), '/')
Genus_Prostate_RA <- sweep(genera_prostate, 2, colSums(genera_prostate), '/')

Genus_Breast_RA_flip <- data.frame(t(Genus_Breast_RA), check.names = F)
Genus_Breast_RA_flip$X <- rownames(Genus_Breast_RA_flip)

Genus_CRC_RA_flip <- data.frame(t(Genus_CRC_RA), check.names = F)
Genus_CRC_RA_flip$X <- rownames(Genus_CRC_RA_flip)

Genus_Prostate_RA_flip <- data.frame(t(Genus_Prostate_RA), check.names = F)
Genus_Prostate_RA_flip$X <- rownames(Genus_Prostate_RA_flip)
```

```{r}
ASV_Breast_RA_filt <- remove_rare_features(table = ASV_Breast_RA, cutoff_pro = 0.05)
ASV_Prostate_RA_filt <- remove_rare_features(table=ASV_Prostate_RA, cutoff_pro = 0.05)
ASV_CRC_RA_filt <- remove_rare_features(table=ASV_CRC_RA, cutoff_pro = 0.05)

ASV_Breast_RA_filt_flip <- data.frame(t(ASV_Breast_RA_filt), check.names = F)
ASV_Prostate_RA_filt_flip <- data.frame(t(ASV_Prostate_RA_filt), check.names = F)
ASV_CRC_RA_filt_flip <- data.frame(t(ASV_CRC_RA_filt), check.names = F)


Genus_Breast_RA_filt <- remove_rare_features(table=Genus_Breast_RA, cutoff_pro = 0.05)
Genus_Prostate_RA_filt <- remove_rare_features(table=Genus_Prostate_RA, cutoff_pro = 0.05)
Genus_CRC_RA_filt <- remove_rare_features(table=Genus_CRC_RA, cutoff_pro = 0.05)

Genus_Breast_RA_filt_flip <- data.frame(t(Genus_Breast_RA_filt), check.names = F)
Genus_Prostate_RA_filt_flip <- data.frame(t(Genus_Prostate_RA_filt), check.names = F)
Genus_CRC_RA_filt_flip <- data.frame(t(Genus_CRC_RA_filt), check.names = F)


ASV_Breast_CLR_filt_flip <- ASV_Breast_CLR_flip[,colnames(ASV_Breast_RA_filt_flip)]
ASV_Prostate_CLR_filt_flip <- ASV_Prostate_CLR_flip[,colnames(ASV_Prostate_RA_filt_flip)]
ASV_CRC_CLR_filt_flip <- ASV_CRC_CLR_flip[,colnames(ASV_CRC_RA_filt_flip)]

Genus_Breast_CLR_filt_flip <- Genus_Breast_CLR_flip[,colnames(Genus_Breast_RA_filt_flip)]
Genus_Prostate_CLR_filt_flip <- Genus_Prostate_CLR_flip[,colnames(Genus_Prostate_RA_filt_flip)]
Genus_CRC_CLR_filt_flip <- Genus_CRC_CLR_flip[,colnames(Genus_CRC_RA_filt_flip)]

fit_control_rcv <- trainControl(method="repeatedcv", savePredictions = T, summaryFunction = twoClassSummary, classProbs = T, repeats = 100, number = 5)
```

# Breast

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_Breast_RA_filt_flip), as.character(Breast_data$X)))
set.seed(10)

ASV_RCV_Breast_RA <- train(ASV_Breast_RA_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                           tuneGrid = data.frame(mtry=20), trControl = fit_control_rcv, importance=T)

ASV_RCV_Breast_RA

saveRDS(ASV_RCV_Breast_RA, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Breast/ASV_RCV_RA_caret.RDS")
```


## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_Breast_CLR_filt_flip), as.character(Breast_data$X)))
set.seed(10)

ASV_RCV_Breast_CLR <- train(ASV_Breast_CLR_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                            tuneGrid = data.frame(mtry=20), trControl = fit_control_rcv, importance=T)
ASV_RCV_Breast_CLR
saveRDS(ASV_RCV_Breast_CLR, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Breast/ASV_RCV_CLR_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_Breast_RA_filt_flip), as.character(Breast_data$X)))
set.seed(10)

Genus_RCV_Breast_RA <- train(Genus_Breast_RA_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                             tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_Breast_RA
saveRDS(Genus_RCV_Breast_RA, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Breast/Genus_RCV_RA_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_Breast_CLR_filt_flip), as.character(Breast_data$X)))
set.seed(10)

Genus_RCV_Breast_CLR <- train(Genus_Breast_CLR_filt_flip, y=Breast_data$Case.Control, method="rf", ntree=1001,
                              tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_Breast_CLR
saveRDS(Genus_RCV_Breast_CLR, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Breast/Genus_RCV_CLR_caret.RDS")
```

# Prostate

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_Prostate_RA_filt_flip), as.character(Prostate_data$X)))
set.seed(10)

ASV_RCV_Prostate_RA <- train(ASV_Prostate_RA_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                             tuneGrid = data.frame(mtry=20), trControl = fit_control_rcv, importance=T)

ASV_RCV_Prostate_RA
saveRDS(ASV_RCV_Prostate_RA, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Prostate/ASV_RCV_RA_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_Prostate_CLR_filt_flip), as.character(Prostate_data$X)))
set.seed(10)

ASV_RCV_Prostate_CLR <- train(ASV_Prostate_CLR_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                              tuneGrid = data.frame(mtry=20), trControl = fit_control_rcv, importance=T)
ASV_RCV_Prostate_CLR
saveRDS(ASV_RCV_Prostate_CLR, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Prostate/ASV_RCV_CLR_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_Prostate_RA_filt_flip), as.character(Prostate_data$X)))
set.seed(10)

Genus_RCV_Prostate_RA <- train(Genus_Prostate_RA_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                               tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_Prostate_RA
saveRDS(Genus_RCV_Prostate_RA, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Prostate/Genus_RCV_RA_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_Prostate_CLR_filt_flip), as.character(Prostate_data$X)))
set.seed(10)

Genus_RCV_Prostate_CLR <- train(Genus_Prostate_CLR_filt_flip, y=Prostate_data$Case.Control, method="rf", ntree=1001,
                                tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_Prostate_CLR
saveRDS(Genus_RCV_Prostate_CLR, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/Prostate/Genus_RCV_CLR_caret.RDS")
```

# Colon

## ASV RA
```{r}
stopifnot(identical(rownames(ASV_CRC_RA_filt_flip), as.character(CRC_data$X)))
set.seed(10)

ASV_RCV_CRC_RA <- train(ASV_CRC_RA_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                        tuneGrid = data.frame(mtry=19), trControl = fit_control_rcv, importance=T)
ASV_RCV_CRC_RA
saveRDS(ASV_RCV_CRC_RA, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/CRC/ASV_RCV_RA_caret.RDS")
```

## ASV CLR
```{r}
stopifnot(identical(rownames(ASV_CRC_CLR_filt_flip), as.character(CRC_data$X)))
set.seed(10)

ASV_RCV_CRC_CLR <- train(ASV_CRC_CLR_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                         tuneGrid = data.frame(mtry=19), trControl = fit_control_rcv, importance=T)
ASV_RCV_CRC_CLR
saveRDS(ASV_RCV_CRC_CLR, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/CRC/ASV_RCV_CLR_caret.RDS")
```

## Genus RA
```{r}
stopifnot(identical(rownames(Genus_CRC_RA_filt_flip), as.character(CRC_data$X)))
set.seed(10)

Genus_RCV_CRC_RA <- train(Genus_CRC_RA_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                          tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_CRC_RA
saveRDS(Genus_RCV_CRC_RA, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/CRC/Genus_RCV_RA_caret.RDS")
```

## Genus CLR
```{r}
stopifnot(identical(rownames(Genus_CRC_CLR_filt_flip), as.character(CRC_data$X)))
set.seed(10)

Genus_RCV_CRC_CLR <- train(Genus_CRC_CLR_filt_flip, y=CRC_data$Case.Control, method="rf", ntree=1001,
                           tuneGrid = data.frame(mtry=9), trControl = fit_control_rcv, importance=T)
Genus_RCV_CRC_CLR
saveRDS(Genus_RCV_CRC_CLR, "~/Private/CHAPTER_4/Prospec/ATP/Random_Forest/CRC/Genus_RCV_CLR_caret.RDS")
```
